table Medidas
	lineageTag: 4dcd545f-1501-4690-a2ef-224284d1164d

	measure 'HTML Card Base' = ```
			
			VAR _Title = "Total Medals"
			VAR _Value = FORMAT([Total Medals], "#,0")
			VAR _Subtitle = "All Olympic History"
			RETURN
			"<div style='background:#ffffff;border-radius:16px;padding:16px;box-shadow:0 2px 6px rgba(0,0,0,0.15);font-family:Segoe UI;width:100%;height:100%;'>" &
			"<div style='font-size:13px;color:#6b7280;margin-bottom:6px;'>" & _Title & "</div>" &
			"<div style='font-size:32px;font-weight:700;color:#111827;margin-bottom:6px;'>" & _Value & "</div>" &
			"<div style='font-size:12px;color:#10b981;'>" & _Subtitle & "</div>" &
			"</div>"
			
			```
		displayFolder: Dash 1
		lineageTag: 3004d375-4d20-45dc-ba57-8231cc0e4e1f

	measure 'Total Medals' =
			
			SUM('athlete medals'[Medal Value])
		formatString: 0
		displayFolder: Dash 1
		lineageTag: 6aa8c259-d89b-424c-a5a7-57c3407ab0b2

	measure 'Medal Score' = ```
			
			SUM ( results[Medal Value] )
			
			```
		formatString: #,0
		displayFolder: Dash 1
		lineageTag: 2eb2a114-a953-4245-8947-0896ed31c484

	measure Countries = ```
			
			DISTINCTCOUNT ( results[NOC] )
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: f0230b6e-32b7-4392-8a8b-59b562a0ff9e

	measure Athletes = ```
			
			DISTINCTCOUNT ( athletes[Athlete URL] )
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: 61a44eca-fd29-475c-923b-db94906794a1

	measure Games = ```
			
			DISTINCTCOUNT ( hosts[Game Slug] )
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: 45f42e58-25f6-42e5-ad9e-83b93aa2c479

	measure 'Card Total Medals' = ```
			
			VAR _Value = FORMAT([Total Medals], "#,0")
			
			RETURN
			"<div style='background:#ffffff;border-radius:18px;overflow:hidden;
			box-shadow:0 6px 14px rgba(0,0,0,0.15);font-family:Segoe UI;'>
			
			<div style='background:linear-gradient(90deg,#2563eb,#0ea5e9);
			padding:10px;color:white;font-size:13px;font-weight:600;'>
			🏅 TOTAL MEDALS
			</div>
			
			<div style='padding:18px;'>
			
			<div style='font-size:36px;font-weight:800;color:#111827;'>" &
			_Value &
			"</div>
			
			<div style='font-size:12px;color:#6b7280;margin-top:4px;'>
			All Olympic Games
			</div>
			
			</div></div>"
			
			```
		displayFolder: Dash 1
		lineageTag: 5791e535-0e82-480f-a8a8-615ba128b2ee

	measure 'Card Leading Nation' = ```
			
			VAR _Country =
			    CALCULATE(
			        SELECTEDVALUE(results[NOC]),
			        TOPN(1, ALL(results[NOC]), [Medal Score], DESC)
			    )
			
			VAR _Score =
			    CALCULATE([Medal Score], results[NOC] = _Country)
			
			RETURN
			"<div style='background:#ffffff;border-radius:16px;padding:18px;box-shadow:0 4px 10px rgba(0,0,0,0.12);font-family:Segoe UI;'>" &
			"<div style='font-size:13px;color:#6b7280;'>🥇 Leading Nation</div>" &
			"<div style='font-size:28px;font-weight:700;color:#111827;'>" & _Country & "</div>" &
			"<div style='font-size:12px;color:#059669;'>Score: " & FORMAT(_Score,"#,0") & "</div>" &
			"</div>"
			
			```
		displayFolder: Dash 1
		lineageTag: 6731ec70-9b3e-40e3-a15c-554d16960a20

	measure 'Card Top Athlete' = ```
			
			VAR _Athlete =
			    CALCULATE(
			        SELECTEDVALUE(athletes[Athlete]),
			        TOPN(1, ALL(athletes[Athlete]), [Total Medals], DESC)
			    )
			
			VAR _Medals =
			    CALCULATE([Total Medals], athletes[Athlete] = _Athlete)
			
			RETURN
			"<div style='background:#ffffff;border-radius:16px;padding:18px;box-shadow:0 4px 10px rgba(0,0,0,0.12);font-family:Segoe UI;'>" &
			"<div style='font-size:13px;color:#6b7280;'>🏆 Top Athlete</div>" &
			"<div style='font-size:22px;font-weight:700;color:#111827;'>" & _Athlete & "</div>" &
			"<div style='font-size:12px;color:#7c3aed;'>" & FORMAT(_Medals,"#,0") & " medals</div>" &
			"</div>"
			
			```
		displayFolder: Dash 1
		lineageTag: 9958f2af-82d9-417b-9209-4745b7a8adab

	measure 'Card Momentum' = ```
			
			VAR _Growth = [Medal Growth]
			
			VAR _Icon =
			    IF(_Growth > 0.15,"🚀",
			    IF(_Growth < -0.1,"📉","➖"))
			
			VAR _Color =
			    IF(_Growth > 0.15,"#059669",
			    IF(_Growth < -0.1,"#dc2626","#6b7280"))
			
			RETURN
			"<div style='background:#ffffff;border-radius:16px;padding:18px;box-shadow:0 4px 10px rgba(0,0,0,0.12);font-family:Segoe UI;'>" &
			"<div style='font-size:13px;color:#6b7280;'>Momentum</div>" &
			"<div style='font-size:26px;font-weight:700;color:" & _Color & ";'>" &
			_Icon & " " & FORMAT(_Growth,"0.0%") &
			"</div>" &
			"</div>"
			
			```
		displayFolder: Dash 1
		lineageTag: bbb52403-82fb-416f-ac5d-c6b49e674877

	measure 'Silver Medals' = ```
			
			CALCULATE(
			    COUNTROWS(results),
			    results[Medal (Raw)] = "Silver"
			)
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: b9aeb953-7943-4286-89e0-34b37370d22e

	measure 'Medal Growth' = ```
			
			VAR CurrentYear =
			    MAX ( hosts[Year] )
			
			VAR PrevYear =
			    CurrentYear - 4
			
			VAR CurrentValue =
			    CALCULATE (
			        [Medal Score],
			        hosts[Year] = CurrentYear
			    )
			
			VAR PrevValue =
			    CALCULATE (
			        [Medal Score],
			        hosts[Year] = PrevYear
			    )
			
			RETURN
			DIVIDE ( CurrentValue - PrevValue, PrevValue )
			
			```
		displayFolder: Dash 1
		lineageTag: 073eedac-8187-4715-943f-689db77fbf0e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Card Narrative' = ```
			
			VAR _TopCountry =
			    CALCULATE(
			        SELECTEDVALUE(results[NOC]),
			        TOPN(1, ALL(results[NOC]), [Medal Score], DESC)
			    )
			
			VAR _Growth = [Medal Growth]
			
			VAR _Trend =
			    IF(
			        _Growth > 0.1, "accelerated growth",
			        IF(_Growth < -0.05, "performance decline", "stable performance")
			    )
			
			RETURN
			"<div style='background:#f9fafb;border-radius:14px;padding:16px;font-family:Segoe UI;'>" &
			"<div style='font-size:14px;font-weight:600;color:#111827;margin-bottom:6px;'>📊 Key Insight</div>" &
			"<div style='font-size:13px;color:#374151;line-height:1.5;'>" &
			"Over the last Olympic cycles, <b>" & _TopCountry & "</b> has demonstrated " &
			_Trend & ", reinforcing its position in global competition. " &
			"This trend highlights shifting dynamics in elite sports performance." &
			"</div></div>"
			
			```
		displayFolder: Dash 1
		lineageTag: 14353d68-b7dc-42d7-a50b-5e42b55c4623

	measure 'Olympic Header Cards' = ```
			
			VAR _Total = FORMAT([Total Medals], "#,0")
			
			VAR _Country =
			    CALCULATE(
			        SELECTEDVALUE(results[NOC]),
			        TOPN(1,ALL(results[NOC]),[Medal Score],DESC)
			    )
			
			VAR _Score =
			    CALCULATE([Medal Score],results[NOC]=_Country)
			
			VAR _Athlete =
			    CALCULATE(
			        SELECTEDVALUE(athletes[Athlete]),
			        TOPN(1,ALL(athletes[Athlete]),[Total Medals],DESC)
			    )
			
			VAR _Medals =
			    CALCULATE([Total Medals],athletes[Athlete]=_Athlete)
			
			VAR _Growth = [Medal Growth]
			
			VAR _Icon =
			    IF(_Growth>0.15,"🚀",
			    IF(_Growth<-0.1,"📉","➖"))
			
			VAR _Color =
			    IF(_Growth>0.15,"#059669",
			    IF(_Growth<-0.1,"#dc2626","#6b7280"))
			
			RETURN
			
			"<div style='display:flex;flex-wrap:wrap;gap:14px;width:100%;
			font-family:Segoe UI;'>
			
			<!-- TOTAL MEDALS -->
			<div style='flex:1 1 220px;min-width:200px;
			background:#ffffff;border-radius:18px;overflow:hidden;
			box-shadow:0 6px 14px rgba(0,0,0,0.15);'>
			
			<div style='background:linear-gradient(90deg,#2563eb,#0ea5e9);
			padding:10px;color:white;font-size:13px;font-weight:600;'>
			🏅 TOTAL MEDALS
			</div>
			
			<div style='padding:16px;'>
			<div style='font-size:34px;font-weight:800;color:#111827;'>" &
			_Total &
			"</div>
			<div style='font-size:12px;color:#6b7280;'>All Olympic Games</div>
			</div>
			</div>
			
			<!-- LEADING NATION -->
			<div style='flex:1 1 220px;min-width:200px;
			background:#ffffff;border-radius:18px;overflow:hidden;
			box-shadow:0 6px 14px rgba(0,0,0,0.15);'>
			
			<div style='background:linear-gradient(90deg,#f59e0b,#fbbf24);
			padding:10px;color:#111827;font-size:13px;font-weight:600;'>
			🥇 LEADING NATION
			</div>
			
			<div style='padding:16px;'>
			<div style='font-size:26px;font-weight:700;color:#111827;'>" &
			_Country &
			"</div>
			<div style='font-size:13px;color:#059669;'>
			Score: " & FORMAT(_Score,"#,0") & "
			</div>
			</div>
			</div>
			
			<!-- TOP ATHLETE -->
			<div style='flex:1 1 220px;min-width:200px;
			background:#ffffff;border-radius:18px;overflow:hidden;
			box-shadow:0 6px 14px rgba(0,0,0,0.15);'>
			
			<div style='background:linear-gradient(90deg,#7c3aed,#a78bfa);
			padding:10px;color:white;font-size:13px;font-weight:600;'>
			🏆 TOP ATHLETE
			</div>
			
			<div style='padding:16px;'>
			<div style='font-size:22px;font-weight:700;color:#111827;'>" &
			_Athlete &
			"</div>
			<div style='font-size:13px;color:#7c3aed;'>" &
			FORMAT(_Medals,"#,0") & " Medals
			</div>
			</div>
			</div>
			
			<!-- MOMENTUM -->
			<div style='flex:1 1 220px;min-width:200px;
			background:#ffffff;border-radius:18px;overflow:hidden;
			box-shadow:0 6px 14px rgba(0,0,0,0.15);'>
			
			<div style='background:" & _Color & ";
			padding:10px;color:white;font-size:13px;font-weight:600;'>
			MOMENTUM
			</div>
			
			<div style='padding:16px;'>
			<div style='font-size:26px;font-weight:700;color:" & _Color & ";'>" &
			_Icon & " " & FORMAT(_Growth,"0.0%") &
			"</div>
			<div style='font-size:12px;color:#6b7280;'>Cycle Trend</div>
			</div>
			</div>
			
			</div>"
			
			```
		displayFolder: Dash 1
		lineageTag: 4305a51c-423b-4992-aed7-de485be60116

	measure 'Rank Country' = ```
			
			RANKX(
			    ALL(results[NOC]),
			    [Medal Score],
			    ,
			    DESC,
			    DENSE
			)
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: 053109b7-ca33-4bb3-bdb3-d85ab425b79f

	measure 'Olympic Ranking Table' = ```
			
			VAR TableHTML =
			
			CONCATENATEX(
			
			    TOPN(
			        20,
			        ADDCOLUMNS(
			            VALUES(results[NOC]),
			
			            "Rank", [Rank Country],
			            "Score", [Medal Score],
			            "Gold", [Gold Medals],
			            "Silver", [Silver Medals],
			            "Bronze", [Bronze Medals]
			        ),
			        [Rank],
			        ASC
			    ),
			
			    VAR _Rank = [Rank]
			    VAR _NOC = results[NOC]
			    VAR _Score = FORMAT([Score],"#,0")
			    VAR _Gold = FORMAT([Gold],"0")
			    VAR _Silver = FORMAT([Silver],"0")
			    VAR _Bronze = FORMAT([Bronze],"0")
			
			    VAR _BG =
			        IF(_Rank=1,"#fef3c7",
			        IF(_Rank=2,"#e5e7eb",
			        IF(_Rank=3,"#fde68a","#ffffff")))
			
			    VAR _Icon =
			        IF(_Rank=1,"🥇",
			        IF(_Rank=2,"🥈",
			        IF(_Rank=3,"🥉",_Rank)))
			
			    RETURN
			
			    "<tr style='background:" & _BG & ";border-bottom:1px solid #e5e7eb;'>
			
			        <td style='padding:8px;font-weight:700;text-align:center;'>" &
			            _Icon &
			        "</td>
			
			        <td style='padding:8px;font-weight:600;'>" &
			            _NOC &
			        "</td>
			
			        <td style='padding:8px;text-align:right;font-weight:700;'>" &
			            _Score &
			        "</td>
			
			        <td style='padding:8px;text-align:center;color:#f59e0b;'>" &
			            _Gold &
			        "</td>
			
			        <td style='padding:8px;text-align:center;color:#9ca3af;'>" &
			            _Silver &
			        "</td>
			
			        <td style='padding:8px;text-align:center;color:#b45309;'>" &
			            _Bronze &
			        "</td>
			
			    </tr>",
			
			    ""
			)
			
			RETURN
			
			"<div style='font-family:Segoe UI;background:#ffffff;
			border-radius:18px;box-shadow:0 6px 14px rgba(0,0,0,0.15);
			padding:14px;'>
			
			<div style='font-size:16px;font-weight:700;color:#111827;
			margin-bottom:10px;'>
			🏆 Olympic Nations Ranking
			</div>
			
			<div style='overflow-x:auto;'>
			
			<table style='width:100%;border-collapse:collapse;font-size:13px;'>
			
			<thead>
			
			<tr style='background:#111827;color:white;'>
			
			<th style='padding:8px;'>#</th>
			<th style='padding:8px;text-align:left;'>Nation</th>
			<th style='padding:8px;text-align:right;'>Score</th>
			<th style='padding:8px;'>🥇</th>
			<th style='padding:8px;'>🥈</th>
			<th style='padding:8px;'>🥉</th>
			
			</tr>
			
			</thead>
			
			<tbody>" &
			
			TableHTML &
			
			"</tbody>
			
			</table>
			
			</div>
			
			</div>"
			
			```
		displayFolder: Dash 1
		lineageTag: 5ff8189d-6596-428e-bcc1-1cda3150e07b

	measure 'Gold Medals' = ```
			
			CALCULATE(
			    COUNTROWS(results),
			    results[Medal (Raw)] = "Gold"
			)
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: 71f39375-6ece-4532-b27c-61def5409b1d

	measure 'Bronze Medals' = ```
			
			CALCULATE(
			    COUNTROWS(results),
			    results[Medal (Raw)] = "Bronze"
			)
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: 3387af06-2c38-4a55-adff-849c03e88363

	measure 'Olympic Banner Cards Glass Pro' = ```
			
			VAR _Total = FORMAT([Total Medals], "#,0")
			
			VAR _Country =
			    CALCULATE(
			        SELECTEDVALUE(results[NOC]),
			        TOPN(1,ALL(results[NOC]),[Medal Score],DESC)
			    )
			
			VAR _Score =
			    CALCULATE([Medal Score],results[NOC]=_Country)
			
			VAR _Athlete =
			    CALCULATE(
			        SELECTEDVALUE(athletes[Athlete]),
			        TOPN(1,ALL(athletes[Athlete]),[Total Medals],DESC)
			    )
			
			VAR _Medals =
			    CALCULATE([Total Medals],athletes[Athlete]=_Athlete)
			
			VAR _Growth = [Medal Growth]
			
			VAR _Icon =
			    IF(_Growth>0.15,"🚀",
			    IF(_Growth<-0.1,"📉","➖"))
			
			VAR _Color =
			    IF(_Growth>0.15,"#059669",
			    IF(_Growth<-0.1,"#dc2626","#6b7280"))
			
			RETURN
			
			"
			<div style='width:100%;font-family:Segoe UI;'>
			
			<!-- BANNER -->
			<div style='
			background:linear-gradient(90deg,#2563eb,#0ea5e9,#22d3ee);
			border-radius:20px;
			padding:20px 20px 26px 20px;
			color:white;
			box-shadow:0 8px 20px rgba(0,0,0,0.18);
			'>
			
			<!-- HEADER -->
			<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;'>
			
			<div>
			<div style='font-size:22px;font-weight:800;'>🏅 Olympic Performance Dashboard</div>
			<div style='font-size:12px;opacity:0.85;'>1896–2022 • Global Overview</div>
			</div>
			
			<div style='
			background:rgba(255,255,255,0.22);
			padding:6px 16px;
			border-radius:14px;
			text-align:center;
			'>
			<div style='font-size:11px;'>Latest</div>
			<div style='font-size:18px;font-weight:800;color:#fde68a;'>2022</div>
			</div>
			
			</div>
			
			<!-- CARDS -->
			<div style='display:flex;gap:16px;flex-wrap:wrap;'>
			
			<!-- TOTAL -->
			<div style='
			flex:1 1 220px;
			background:rgba(255,255,255,0.88);
			backdrop-filter:blur(6px);
			border-radius:16px;
			overflow:hidden;
			box-shadow:0 4px 12px rgba(0,0,0,0.15);
			'>
			
			<div style='
			background:#0ea5e9;
			padding:10px;
			font-size:12px;
			font-weight:700;
			color:white;
			text-align:center;
			'>
			🏅 TOTAL MEDALS
			</div>
			
			<div style='padding:14px;'>
			
			<div style='font-size:28px;font-weight:800;color:#111827;'>
			" & _Total & "
			</div>
			
			<div style='font-size:12px;color:#6b7280;'>All Olympic Games</div>
			
			</div>
			</div>
			
			<!-- COUNTRY -->
			<div style='
			flex:1 1 220px;
			background:rgba(255,255,255,0.88);
			backdrop-filter:blur(6px);
			border-radius:16px;
			overflow:hidden;
			box-shadow:0 4px 12px rgba(0,0,0,0.15);
			'>
			
			<div style='
			background:#fbbf24;
			padding:10px;
			font-size:12px;
			font-weight:700;
			color:#111827;
			text-align:center;
			'>
			🥇 LEADING NATION
			</div>
			
			<div style='padding:14px;'>
			
			<div style='font-size:22px;font-weight:800;color:#111827;'>
			" & _Country & "
			</div>
			
			<div style='font-size:12px;color:#059669;'>
			Score: " & FORMAT(_Score,"#,0") & "
			</div>
			
			</div>
			</div>
			
			<!-- ATHLETE -->
			<div style='
			flex:1 1 220px;
			background:rgba(255,255,255,0.88);
			backdrop-filter:blur(6px);
			border-radius:16px;
			overflow:hidden;
			box-shadow:0 4px 12px rgba(0,0,0,0.15);
			'>
			
			<div style='
			background:#8b5cf6;
			padding:10px;
			font-size:12px;
			font-weight:700;
			color:white;
			text-align:center;
			'>
			🏆 TOP ATHLETE
			</div>
			
			<div style='padding:14px;'>
			
			<div style='font-size:18px;font-weight:800;color:#111827;'>
			" & _Athlete & "
			</div>
			
			<div style='font-size:12px;color:#7c3aed;'>
			" & FORMAT(_Medals,"#,0") & " Medals
			</div>
			
			</div>
			</div>
			
			<!-- MOMENTUM -->
			<div style='
			flex:1 1 220px;
			background:rgba(255,255,255,0.88);
			backdrop-filter:blur(6px);
			border-radius:16px;
			overflow:hidden;
			box-shadow:0 4px 12px rgba(0,0,0,0.15);
			'>
			
			<div style='
			background:" & _Color & ";
			padding:10px;
			font-size:12px;
			font-weight:700;
			color:white;
			text-align:center;
			'>
			📈 MOMENTUM
			</div>
			
			<div style='padding:14px;'>
			
			<div style='font-size:24px;font-weight:800;color:" & _Color & ";'>
			" & _Icon & " " & FORMAT(_Growth,"0.0%") & "
			</div>
			
			<div style='font-size:12px;color:#6b7280;'>Cycle Trend</div>
			
			</div>
			</div>
			
			</div>
			
			</div>
			
			</div>
			"
			
			
			```
		displayFolder: Dash 1
		lineageTag: a85ddfec-83c3-439a-b0af-4f7149c40603

	measure 'Olympic Banner Cards Final Clean' = ```
			
			VAR _Total = FORMAT([Total Medals], "#,0")
			
			VAR _Country =
			    CALCULATE(
			        SELECTEDVALUE(results[NOC]),
			        TOPN(1,ALL(results[NOC]),[Medal Score],DESC)
			    )
			
			VAR _Score =
			    CALCULATE([Medal Score],results[NOC]=_Country)
			
			VAR _Athlete =
			    CALCULATE(
			        SELECTEDVALUE(athletes[Athlete]),
			        TOPN(1,ALL(athletes[Athlete]),[Total Medals],DESC)
			    )
			
			VAR _Medals =
			    CALCULATE([Total Medals],athletes[Athlete]=_Athlete)
			
			VAR _Growth = [Medal Growth]
			
			VAR _Icon =
			    IF(_Growth>0.15,"🚀",
			    IF(_Growth<-0.1,"📉","➖"))
			
			VAR _TrendColor =
			    IF(_Growth>0.15,"#22c55e",
			    IF(_Growth<-0.1,"#ef4444","#38bdf8"))
			
			RETURN
			
			"
			<style>
			
			/* Top line animation */
			@keyframes lineRun {
			  0%   { transform: translateX(-120%); opacity:0; }
			  20%  { opacity:1; }
			  80%  { opacity:1; }
			  100% { transform: translateX(120%); opacity:0; }
			}
			
			/* Card */
			.cardBox {
			  position: relative;
			  border-radius: 16px;
			  overflow: hidden;
			  backdrop-filter: blur(6px);
			  background: rgba(255,255,255,0.75);
			  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
			}
			
			/* Animated line */
			.topLine {
			  position: absolute;
			  top: 0;
			  left: -40%;
			  height: 6px;
			  width: 60%;
			  background: linear-gradient(
			    90deg,
			    transparent,
			    #ffffff,
			    #ffffff,
			    transparent
			  );
			  filter: drop-shadow(0 0 6px rgba(255,255,255,0.9));
			  animation: lineRun 5s ease-in-out infinite;
			}
			
			/* Wave delay */
			.card1 .topLine { animation-delay: 0s; }
			.card2 .topLine { animation-delay: 1.2s; }
			.card3 .topLine { animation-delay: 2.4s; }
			.card4 .topLine { animation-delay: 3.6s; }
			
			/* Card header */
			.cardTitle {
			  white-space: nowrap;
			  overflow: hidden;
			  text-overflow: ellipsis;
			}
			
			</style>
			
			
			<div style='width:100%;font-family:Segoe UI;'>
			
			<!-- MAIN BANNER -->
			<div style='
			background:linear-gradient(90deg,#1e3a8a,#0ea5e9,#22d3ee);
			border-radius:22px;
			padding:16px 20px;
			box-shadow:0 8px 20px rgba(0,0,0,0.22);
			color:white;
			'>
			
			<!-- GRID -->
			<div style='display:grid;grid-template-columns:300px 1fr;gap:18px;align-items:center;'>
			
			<!-- LEFT -->
			<div>
			
			<div style='font-size:22px;font-weight:900;margin-bottom:4px;'>
			🏅 Olympic Performance Dashboard
			</div>
			
			<div style='font-size:13px;font-weight:600;opacity:0.9;'>
			Global Overview • 1896–2022
			</div>
			
			</div>
			
			
			<!-- CARDS -->
			<div style='display:flex;gap:14px;flex-wrap:wrap;'>
			
			<!-- TOTAL -->
			<div class='cardBox card1' style='flex:1 1 185px;'>
			
			<div class='topLine' style='background:#0ea5e9;'></div>
			
			<div class='cardTitle'
			style='background:#0ea5e9;padding:7px;font-size:12px;font-weight:800;color:white;text-align:center;'>
			TOTAL MEDALS
			</div>
			
			<div style='padding:10px 12px;'>
			<div style='font-size:28px;font-weight:900;color:#0f172a;'>" & _Total & "</div>
			<div style='font-size:12px;color:#475569;'>All Games</div>
			</div>
			
			</div>
			
			
			<!-- COUNTRY -->
			<div class='cardBox card2' style='flex:1 1 185px;'>
			
			<div class='topLine' style='background:#fbbf24;'></div>
			
			<div class='cardTitle'
			style='background:#fbbf24;padding:7px;font-size:12px;font-weight:800;color:#1f2937;text-align:center;'>
			LEADING NATION
			</div>
			
			<div style='padding:10px 12px;'>
			<div style='font-size:22px;font-weight:900;color:#0f172a;'>" & _Country & "</div>
			<div style='font-size:12px;color:#059669;'>Score: " & FORMAT(_Score,"#,0") & "</div>
			</div>
			
			</div>
			
			
			<!-- ATHLETE -->
			<div class='cardBox card3' style='flex:1 1 185px;'>
			
			<div class='topLine' style='background:#8b5cf6;'></div>
			
			<div class='cardTitle'
			style='background:#8b5cf6;padding:7px;font-size:12px;font-weight:800;color:white;text-align:center;'>
			TOP ATHLETE
			</div>
			
			<div style='padding:10px 12px;'>
			<div style='font-size:18px;font-weight:900;color:#0f172a;'>" & _Athlete & "</div>
			<div style='font-size:12px;color:#7c3aed;'>" & FORMAT(_Medals,"#,0") & " Medals</div>
			</div>
			
			</div>
			
			
			<!-- MOMENTUM -->
			<div class='cardBox card4' style='flex:1 1 185px;'>
			
			<div class='topLine' style='background:" & _TrendColor & ";'></div>
			
			<div class='cardTitle'
			style='background:" & _TrendColor & ";padding:7px;font-size:12px;font-weight:800;color:white;text-align:center;'>
			MOMENTUM
			</div>
			
			<div style='padding:10px 12px;'>
			<div style='font-size:24px;font-weight:900;color:" & _TrendColor & ";'>" &
			_Icon & " " & FORMAT(_Growth,"0.0%") & "</div>
			<div style='font-size:12px;color:#475569;'>Cycle Trend</div>
			</div>
			
			</div>
			
			</div>
			
			</div>
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 03108aa2-b1a3-49a8-8224-b48434e01cbb

	measure 'Olympic Banner ESPN Style' = ```
			
			VAR _Total = FORMAT([Total Medals], "#,0")
			
			VAR _Country =
			    CALCULATE(
			        SELECTEDVALUE(results[NOC]),
			        TOPN(1,ALL(results[NOC]),[Medal Score],DESC)
			    )
			
			VAR _Score =
			    CALCULATE([Medal Score],results[NOC]=_Country)
			
			VAR _Athlete =
			    CALCULATE(
			        SELECTEDVALUE(athletes[Athlete]),
			        TOPN(1,ALL(athletes[Athlete]),[Total Medals],DESC)
			    )
			
			VAR _Medals =
			    CALCULATE([Total Medals],athletes[Athlete]=_Athlete)
			
			RETURN
			
			"
			<style>
			
			.espnCard{
			  background:#ffffff;
			  border-radius:12px;
			  box-shadow:0 2px 8px rgba(0,0,0,0.12);
			  padding:12px;
			  min-width:180px;
			}
			
			.espnHeader{
			  font-size:12px;
			  font-weight:700;
			  color:#dc2626;
			  text-transform:uppercase;
			  border-bottom:2px solid #dc2626;
			  padding-bottom:4px;
			  margin-bottom:6px;
			}
			
			</style>
			
			
			<div style='width:100%;font-family:Segoe UI;'>
			
			<div style='
			background:#f8fafc;
			border-radius:18px;
			padding:18px;
			border:1px solid #e5e7eb;
			'>
			
			<!-- HEADER -->
			<div style='margin-bottom:14px;'>
			
			<div style='font-size:24px;font-weight:900;color:#111827;'>
			🏅 Olympic Performance
			</div>
			
			<div style='font-size:13px;color:#6b7280;'>
			Global Overview • 1896–2022
			</div>
			
			</div>
			
			
			<!-- CARDS -->
			<div style='display:flex;gap:14px;flex-wrap:wrap;'>
			
			<div class='espnCard'>
			<div class='espnHeader'>Total Medals</div>
			<div style='font-size:26px;font-weight:800;'>" & _Total & "</div>
			<div style='font-size:12px;color:#6b7280;'>All Games</div>
			</div>
			
			
			<div class='espnCard'>
			<div class='espnHeader'>Leading Nation</div>
			<div style='font-size:22px;font-weight:800;'>" & _Country & "</div>
			<div style='font-size:12px;color:#16a34a;'>Score: " & FORMAT(_Score,"#,0") & "</div>
			</div>
			
			
			<div class='espnCard'>
			<div class='espnHeader'>Top Athlete</div>
			<div style='font-size:18px;font-weight:800;'>" & _Athlete & "</div>
			<div style='font-size:12px;color:#7c3aed;'>" & FORMAT(_Medals,"#,0") & " Medals</div>
			</div>
			
			</div>
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 820ef22f-8bc4-468d-a07f-b8581f8926a0

	measure 'Olympic Banner Cards Final Clean Broadcast' = ```
			
			VAR _Total = FORMAT([Total Medals], "#,0")
			
			VAR _Country =
			    CALCULATE(
			        SELECTEDVALUE(results[NOC]),
			        TOPN(1,ALL(results[NOC]),[Medal Score],DESC)
			    )
			
			VAR _Score =
			    CALCULATE([Medal Score],results[NOC]=_Country)
			
			VAR _Athlete =
			    CALCULATE(
			        SELECTEDVALUE(athletes[Athlete]),
			        TOPN(1,ALL(athletes[Athlete]),[Total Medals],DESC)
			    )
			
			VAR _Medals =
			    CALCULATE([Total Medals],athletes[Athlete]=_Athlete)
			
			VAR _Growth = [Medal Growth]
			
			VAR _Icon =
			    IF(_Growth>0.15,"🚀",
			    IF(_Growth<-0.1,"📉","➖"))
			
			VAR _TrendColor =
			    IF(_Growth>0.15,"#22c55e",
			    IF(_Growth<-0.1,"#ef4444","#38bdf8"))
			
			RETURN
			
			"
			<style>
			
			/* =========================
			   BROADCAST EFFECTS
			=========================*/
			
			@keyframes glowPulse {
			  0%   { box-shadow:0 0 6px rgba(56,189,248,.3); }
			  50%  { box-shadow:0 0 18px rgba(56,189,248,.8); }
			  100% { box-shadow:0 0 6px rgba(56,189,248,.3); }
			}
			
			@keyframes lineRun {
			  0%   { transform: translateX(-120%); opacity:0; }
			  20%  { opacity:1; }
			  80%  { opacity:1; }
			  100% { transform: translateX(120%); opacity:0; }
			}
			
			/* =========================
			   MAIN CARD
			=========================*/
			
			.cardBox {
			  position: relative;
			  border-radius: 16px;
			  overflow: hidden;
			  backdrop-filter: blur(6px);
			  background: linear-gradient(180deg,#020617,#020617,#020617);
			  box-shadow:0 0 18px rgba(56,189,248,0.35);
			  animation:glowPulse 5s ease-in-out infinite;
			}
			
			/* =========================
			   TOP LINE
			=========================*/
			
			.topLine {
			  position: absolute;
			  top: 0;
			  left: -40%;
			  height: 6px;
			  width: 60%;
			  background: linear-gradient(
			    90deg,
			    transparent,
			    #38bdf8,
			    #ffffff,
			    #38bdf8,
			    transparent
			  );
			  filter: drop-shadow(0 0 10px #38bdf8);
			  animation: lineRun 5s ease-in-out infinite;
			}
			
			/* =========================
			   WAVE DELAY
			=========================*/
			
			.card1 .topLine { animation-delay: 0s; }
			.card2 .topLine { animation-delay: 1.2s; }
			.card3 .topLine { animation-delay: 2.4s; }
			.card4 .topLine { animation-delay: 3.6s; }
			
			/* =========================
			   HEADERS
			=========================*/
			
			.cardTitle {
			  white-space: nowrap;
			  overflow: hidden;
			  text-overflow: ellipsis;
			  text-transform: uppercase;
			  letter-spacing: .6px;
			}
			
			/* =========================
			   TEXT
			=========================*/
			
			.cardValue {
			  color:#e5f3ff;
			}
			
			.cardSub {
			  color:#94a3b8;
			}
			
			</style>
			
			
			<div style='width:100%;font-family:Segoe UI;'>
			
			<!-- MAIN BANNER -->
			<div style='
			background:linear-gradient(90deg,#020617,#020617,#020617);
			border-radius:22px;
			padding:16px 20px;
			box-shadow:0 0 30px rgba(56,189,248,0.45);
			color:white;
			'>
			
			<!-- GRID -->
			<div style='display:grid;grid-template-columns:300px 1fr;gap:18px;align-items:center;'>
			
			<!-- LEFT -->
			<div>
			
			<div style='
			font-size:22px;
			font-weight:900;
			margin-bottom:4px;
			color:#38bdf8;
			text-shadow:0 0 8px rgba(56,189,248,.7);
			'>
			🏟️ OLYMPIC LIVE PERFORMANCE
			</div>
			
			<div style='
			font-size:13px;
			font-weight:600;
			opacity:0.9;
			color:#cbd5f5;
			'>
			GLOBAL OVERVIEW • 1896–2022
			</div>
			
			</div>
			
			
			<!-- CARDS -->
			<div style='display:flex;gap:14px;flex-wrap:wrap;'>
			
			
			<!-- TOTAL -->
			<div class='cardBox card1' style='flex:1 1 185px;'>
			
			<div class='topLine'></div>
			
			<div class='cardTitle'
			style='background:#0284c7;padding:7px;font-size:12px;font-weight:800;color:white;text-align:center;'>
			TOTAL MEDALS
			</div>
			
			<div style='padding:10px 12px;'>
			
			<div class='cardValue' style='font-size:28px;font-weight:900;'>" & _Total & "</div>
			<div class='cardSub' style='font-size:12px;'>All Games</div>
			
			</div>
			</div>
			
			
			<!-- COUNTRY -->
			<div class='cardBox card2' style='flex:1 1 185px;'>
			
			<div class='topLine'></div>
			
			<div class='cardTitle'
			style='background:#facc15;padding:7px;font-size:12px;font-weight:800;color:#020617;text-align:center;'>
			LEADING NATION
			</div>
			
			<div style='padding:10px 12px;'>
			
			<div class='cardValue' style='font-size:22px;font-weight:900;'>" & _Country & "</div>
			<div class='cardSub' style='font-size:12px;color:#22c55e;'>Score: " & FORMAT(_Score,"#,0") & "</div>
			
			</div>
			</div>
			
			
			<!-- ATHLETE -->
			<div class='cardBox card3' style='flex:1 1 185px;'>
			
			<div class='topLine'></div>
			
			<div class='cardTitle'
			style='background:#7c3aed;padding:7px;font-size:12px;font-weight:800;color:white;text-align:center;'>
			TOP ATHLETE
			</div>
			
			<div style='padding:10px 12px;'>
			
			<div class='cardValue' style='font-size:18px;font-weight:900;'>" & _Athlete & "</div>
			<div class='cardSub' style='font-size:12px;color:#a78bfa;'>" & FORMAT(_Medals,"#,0") & " Medals</div>
			
			</div>
			</div>
			
			
			<!-- MOMENTUM -->
			<div class='cardBox card4' style='flex:1 1 185px;'>
			
			<div class='topLine'></div>
			
			<div class='cardTitle'
			style='background:" & _TrendColor & ";padding:7px;font-size:12px;font-weight:800;color:white;text-align:center;'>
			MOMENTUM
			</div>
			
			<div style='padding:10px 12px;'>
			
			<div class='cardValue'
			style='font-size:24px;font-weight:900;color:" & _TrendColor & ";'>" &
			_Icon & " " & FORMAT(_Growth,"0.0%") & "</div>
			
			<div class='cardSub' style='font-size:12px;'>Cycle Trend</div>
			
			</div>
			</div>
			
			</div>
			
			</div>
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 2667afec-a5b4-4145-9334-750e3e6ac919

	measure 'Olympic Medal Table Broadcast Fixed Header' = ```
			
			VAR _BaseTable =
			    SUMMARIZE(
			        'athlete medals',
			        'athlete medals'[NOC],
			
			        "Gold",
			            CALCULATE(
			                COUNTROWS('athlete medals'),
			                'athlete medals'[Medal] = "Gold"
			            ),
			
			        "Silver",
			            CALCULATE(
			                COUNTROWS('athlete medals'),
			                'athlete medals'[Medal] = "Silver"
			            ),
			
			        "Bronze",
			            CALCULATE(
			                COUNTROWS('athlete medals'),
			                'athlete medals'[Medal] = "Bronze"
			            ),
			
			        "Total",
			            COUNTROWS('athlete medals'),
			
			        "Score",
			            SUM('athlete medals'[Medal Value])
			    )
			
			VAR _Table =
			    ADDCOLUMNS(
			        _BaseTable,
			        "Rank",
			        RANKX(_BaseTable,[Score],,DESC,DENSE)
			    )
			
			VAR _Top10 =
			    TOPN(10,_Table,[Score],DESC)
			
			RETURN
			
			"
			<style>
			
			/* =========================
			   ANIMATIONS
			=========================*/
			
			@keyframes glowPulse {
			  0% { box-shadow:0 0 8px rgba(56,189,248,.3); }
			  50%{ box-shadow:0 0 22px rgba(56,189,248,.8); }
			  100%{ box-shadow:0 0 8px rgba(56,189,248,.3); }
			}
			
			@keyframes scanLine {
			  0% { transform:translateY(-120%); opacity:0; }
			  40%{ opacity:.7; }
			  100%{ transform:translateY(140%); opacity:0; }
			}
			
			@keyframes scrollBody {
			  0% { transform:translateY(0); }
			  100% { transform:translateY(-60%); }
			}
			
			/* =========================
			   CONTAINER
			=========================*/
			
			.tableBox {
			  background:#020617;
			  border-radius:20px;
			  padding:14px;
			  box-shadow:0 0 30px rgba(56,189,248,.45);
			  animation:glowPulse 6s infinite;
			  position:relative;
			  overflow:hidden;
			}
			
			/* Scan only on body */
			.scan {
			  position:absolute;
			  top:82px;
			  left:0;
			  right:0;
			  bottom:0;
			  background:linear-gradient(
			    transparent,
			    rgba(56,189,248,.12),
			    transparent
			  );
			  animation:scanLine 7s linear infinite;
			  pointer-events:none;
			  z-index:1;
			}
			
			/* =========================
			   HEADER
			=========================*/
			
			.tableHeader {
			  font-size:20px;
			  font-weight:900;
			  color:#38bdf8;
			  margin-bottom:6px;
			  text-shadow:0 0 8px rgba(56,189,248,.8);
			  display:flex;
			  align-items:center;
			  gap:10px;
			  position:relative;
			  z-index:3;
			}
			
			.medalIcons {
			  font-size:20px;
			}
			
			/* =========================
			   TABLE
			=========================*/
			
			.tableWrap {
			  position:relative;
			  z-index:2;
			}
			
			/* Fixed header table */
			.tableHead {
			  width:100%;
			  border-collapse:collapse;
			  font-size:13px;
			  color:#94a3b8;
			}
			
			.tableHead th {
			  padding:6px;
			  border-bottom:1px solid #1e293b;
			  text-align:left;
			}
			
			/* Scroll body */
			.bodyWrap {
			  max-height:220px;
			  overflow:hidden;
			}
			
			.tableBody {
			  width:100%;
			  border-collapse:collapse;
			  font-size:13px;
			  color:#e5f3ff;
			}
			
			.tableBody td {
			  padding:6px;
			  border-bottom:1px solid #020617;
			}
			
			.scrollContent {
			  animation:scrollBody 26s linear infinite;
			}
			
			/* Top 3 */
			.rank1 { background:rgba(250,204,21,.18); }
			.rank2 { background:rgba(148,163,184,.18); }
			.rank3 { background:rgba(244,114,182,.18); }
			
			.rankCol {
			  color:#38bdf8;
			  font-weight:800;
			}
			
			</style>
			
			
			<div style='width:100%;font-family:Segoe UI;'>
			
			<div class='tableBox'>
			
			<div class='scan'></div>
			
			
			<!-- HEADER -->
			<div class='tableHeader'>
			
			<span>🏆 MEDAL TABLE — LIVE RANKING</span>
			
			<span class='medalIcons'>🥇🥈🥉</span>
			
			</div>
			
			
			<!-- TABLE -->
			<div class='tableWrap'>
			
			
			<!-- FIXED HEADER -->
			<table class='tableHead'>
			
			<thead>
			<tr>
			  <th>#</th>
			  <th>NOC</th>
			  <th>🥇</th>
			  <th>🥈</th>
			  <th>🥉</th>
			  <th>Total</th>
			  <th>Score</th>
			</tr>
			</thead>
			
			</table>
			
			
			<!-- BODY -->
			<div class='bodyWrap'>
			
			<table class='tableBody'>
			
			<tbody class='scrollContent'>
			" &
			
			CONCATENATEX(
			
			    _Top10,
			
			    VAR _Rank = [Rank]
			
			    VAR _Class =
			        IF(
			            _Rank=1,"rank1",
			            IF(_Rank=2,"rank2",
			            IF(_Rank=3,"rank3",""))
			        )
			
			    RETURN
			
			"
			<tr class='" & _Class & "'>
			
			  <td class='rankCol'>" & _Rank & "</td>
			
			  <td><b>" & [NOC] & "</b></td>
			
			  <td>" & [Gold] & "</td>
			
			  <td>" & [Silver] & "</td>
			
			  <td>" & [Bronze] & "</td>
			
			  <td><b>" & [Total] & "</b></td>
			
			  <td style='color:#38bdf8;font-weight:800;'>" &
			        FORMAT([Score],"#,0") &
			  "</td>
			
			</tr>
			",
			
			"",
			[Rank], ASC
			
			)
			
			&
			
			"
			</tbody>
			
			</table>
			
			</div>
			
			</div>
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 1683f9af-7934-45b0-af04-9567e9c197f5

	measure 'Olympic Flip Card Test' = ```
			
			VAR _Total = FORMAT([Total Medals], "#,0")
			
			VAR _TopCountry =
			    CALCULATE(
			        SELECTEDVALUE(results[NOC]),
			        TOPN(1,ALL(results[NOC]),[Medal Score],DESC)
			    )
			
			VAR _Score =
			    CALCULATE([Medal Score],results[NOC]=_TopCountry)
			
			RETURN
			
			"
			<style>
			
			/* =====================
			   FLIP EFFECT
			=====================*/
			
			.flipCard {
			  background: transparent;
			  width: 220px;
			  height: 140px;
			  perspective: 1200px;
			}
			
			.flipInner {
			  position: relative;
			  width: 100%;
			  height: 100%;
			  text-align: center;
			  transition: transform 0.9s cubic-bezier(.4,.2,.2,1);
			  transform-style: preserve-3d;
			}
			
			/* Hover flip */
			.flipCard:hover .flipInner {
			  transform: rotateY(180deg);
			}
			
			/* Faces */
			.flipFront,
			.flipBack {
			  position: absolute;
			  width: 100%;
			  height: 100%;
			  backface-visibility: hidden;
			  border-radius: 16px;
			  overflow: hidden;
			  box-shadow:0 0 18px rgba(56,189,248,.5);
			}
			
			/* FRONT */
			.flipFront {
			  background: linear-gradient(180deg,#020617,#020617);
			  color: white;
			  border:1px solid #38bdf8;
			}
			
			/* BACK */
			.flipBack {
			  background: linear-gradient(180deg,#020617,#020617);
			  color: white;
			  transform: rotateY(180deg);
			  border:1px solid #22c55e;
			}
			
			/* Header */
			.flipHeader {
			  background:#0284c7;
			  padding:6px;
			  font-size:12px;
			  font-weight:800;
			  text-transform:uppercase;
			}
			
			/* Content */
			.flipContent {
			  padding:12px;
			}
			
			/* Glow */
			@keyframes glow {
			  0% { box-shadow:0 0 6px rgba(56,189,248,.4); }
			  50%{ box-shadow:0 0 16px rgba(56,189,248,.9); }
			  100%{ box-shadow:0 0 6px rgba(56,189,248,.4); }
			}
			
			.flipFront,
			.flipBack {
			  animation:glow 4s infinite;
			}
			
			</style>
			
			
			<div style='font-family:Segoe UI;'>
			
			<div class='flipCard'>
			
			<div class='flipInner'>
			
			<!-- FRONT -->
			<div class='flipFront'>
			
			<div class='flipHeader'>
			🏅 TOTAL MEDALS
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:34px;font-weight:900;color:#e5f3ff;'>
			" & _Total & "
			</div>
			
			<div style='font-size:12px;color:#94a3b8;'>
			All Olympic Games
			</div>
			
			</div>
			
			</div>
			
			
			<!-- BACK -->
			<div class='flipBack'>
			
			<div class='flipHeader' style='background:#22c55e;color:#020617;'>
			📊 TOP NATION
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:20px;font-weight:800;'>
			" & _TopCountry & "
			</div>
			
			<div style='font-size:13px;color:#22c55e;margin-top:4px;'>
			Score: " & FORMAT(_Score,"#,0") & "
			</div>
			
			<div style='font-size:11px;color:#94a3b8;margin-top:8px;'>
			Leading Olympic power
			</div>
			
			</div>
			
			</div>
			
			</div>
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 51a738f7-c6de-42b2-bb16-24f6a4af7ff1

	measure 'Flip Card Template' = ```
			
			VAR _Value = "123"
			
			RETURN
			
			"
			<style>
			
			/* FLIP CARD ENGINE */
			
			.flipCard {
			  width:220px;
			  height:140px;
			  perspective:1200px;
			}
			
			.flipInner {
			  width:100%;
			  height:100%;
			  position:relative;
			  transition:transform .9s cubic-bezier(.4,.2,.2,1);
			  transform-style:preserve-3d;
			}
			
			.flipCard:hover .flipInner {
			  transform:rotateY(180deg);
			}
			
			.flipFront,
			.flipBack {
			  position:absolute;
			  width:100%;
			  height:100%;
			  border-radius:16px;
			  backface-visibility:hidden;
			  background:#020617;
			  border:1px solid #38bdf8;
			  box-shadow:0 0 18px rgba(56,189,248,.5);
			  color:white;
			}
			
			.flipBack {
			  transform:rotateY(180deg);
			  border-color:#22c55e;
			}
			
			.flipHeader {
			  background:#0284c7;
			  padding:6px;
			  font-size:12px;
			  font-weight:800;
			  text-align:center;
			}
			
			.flipContent {
			  padding:12px;
			}
			
			/* Glow */
			
			@keyframes glow {
			  0%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			  50%{box-shadow:0 0 16px rgba(56,189,248,.9);}
			  100%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			}
			
			.flipFront,
			.flipBack {
			  animation:glow 4s infinite;
			}
			
			</style>
			
			
			<div class='flipCard'>
			
			<div class='flipInner'>
			
			<!-- FRONT -->
			<div class='flipFront'>
			
			<div class='flipHeader'>
			TITLE
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:28px;font-weight:900;'>
			" & _Value & "
			</div>
			
			</div>
			
			</div>
			
			
			<!-- BACK -->
			<div class='flipBack'>
			
			<div class='flipHeader' style='background:#22c55e;color:#020617;'>
			DETAIL
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:18px;font-weight:800;'>
			More Info
			</div>
			
			</div>
			
			</div>
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: b5d60f81-0a21-48c8-8571-e38cdab81bfb

	measure 'Flip Card Edition Performance' = ```
			
			VAR _Avg =
			FORMAT(
			AVERAGEX(
			VALUES('athlete medals'[Game Slug]),
			[Total Medals]
			),
			"#,0"
			)
			
			VAR _Max =
			FORMAT(
			MAXX(
			VALUES('athlete medals'[Game Slug]),
			[Total Medals]
			),
			"#,0"
			)
			
			RETURN
			
			"
			<style>
			
			/* =====================
			   FLIP EFFECT
			=====================*/
			
			.flipCard {
			  background: transparent;
			  width: 220px;
			  height: 140px;
			  perspective: 1200px;
			}
			
			.flipInner {
			  position: relative;
			  width: 100%;
			  height: 100%;
			  text-align: center;
			  transition: transform 0.9s cubic-bezier(.4,.2,.2,1);
			  transform-style: preserve-3d;
			}
			
			/* Hover flip */
			.flipCard:hover .flipInner {
			  transform: rotateY(180deg);
			}
			
			/* Faces */
			.flipFront,
			.flipBack {
			  position: absolute;
			  width: 100%;
			  height: 100%;
			  backface-visibility: hidden;
			  border-radius: 16px;
			  overflow: hidden;
			  box-shadow:0 0 18px rgba(56,189,248,.5);
			}
			
			/* FRONT */
			.flipFront {
			  background: linear-gradient(180deg,#020617,#020617);
			  color: white;
			  border:1px solid #38bdf8;
			}
			
			/* BACK */
			.flipBack {
			  background: linear-gradient(180deg,#020617,#020617);
			  color: white;
			  transform: rotateY(180deg);
			  border:1px solid #22c55e;
			}
			
			/* Header */
			.flipHeader {
			  background:#0284c7;
			  padding:6px;
			  font-size:12px;
			  font-weight:800;
			  text-transform:uppercase;
			}
			
			/* Content */
			.flipContent {
			  padding:12px;
			}
			
			/* Glow */
			@keyframes glow {
			  0% { box-shadow:0 0 6px rgba(56,189,248,.4); }
			  50%{ box-shadow:0 0 16px rgba(56,189,248,.9); }
			  100%{ box-shadow:0 0 6px rgba(56,189,248,.4); }
			}
			
			.flipFront,
			.flipBack {
			  animation:glow 4s infinite;
			}
			
			</style>
			
			
			<div style='font-family:Segoe UI;'>
			
			<div class='flipCard'>
			
			<div class='flipInner'>
			
			<!-- FRONT -->
			<div class='flipFront'>
			
			<div class='flipHeader'>
			📊 AVG PER EDITION
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:30px;font-weight:900;color:#e5f3ff;'>
			" & _Avg & "
			</div>
			
			<div style='font-size:12px;color:#94a3b8;'>
			Medals / Games
			</div>
			
			</div>
			
			</div>
			
			
			<!-- BACK -->
			<div class='flipBack'>
			
			<div class='flipHeader' style='background:#22c55e;color:#020617;'>
			🏆 RECORD EDITION
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:22px;font-weight:800;'>
			" & _Max & "
			</div>
			
			<div style='font-size:11px;color:#94a3b8;'>
			Highest medal event
			</div>
			
			</div>
			
			</div>
			
			</div>
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 0651f7db-b8ec-4c17-8272-50d036f570d1

	measure 'Olympic Master Header ESPN Live v7' = ```
			
			
			/* =====================
			   CORE METRICS
			=====================*/
			
			VAR _Total = FORMAT([Total Medals], "#,0")
			
			VAR _Country =
			CALCULATE(
			    SELECTEDVALUE(results[NOC]),
			    TOPN(1,ALL(results[NOC]),[Medal Score],DESC)
			)
			
			VAR _Score =
			CALCULATE([Medal Score],results[NOC]=_Country)
			
			VAR _TopDiscipline =
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(1,ALL(results[Discipline]),[Medal Score],DESC)
			)
			
			VAR _DisciplineScore =
			CALCULATE([Medal Score],results[Discipline]=_TopDiscipline)
			
			VAR _Growth = FORMAT([Medal Growth],"0.0%")
			
			VAR _Editions =
			DISTINCTCOUNT(hosts[Game Slug])
			
			
			/* =====================
			   COUNTDOWN — WINTER
			=====================*/
			
			VAR _WinterDate = DATE(2026,2,6)
			
			VAR _Now = NOW()
			
			VAR _DiffW = _WinterDate - _Now
			VAR _SecW = INT(_DiffW * 86400)
			
			VAR _DaysW = INT(_SecW / 86400)
			VAR _HoursW = INT(MOD(_SecW,86400)/3600)
			VAR _MinW = INT(MOD(_SecW,3600)/60)
			VAR _SecR = MOD(_SecW,60)
			
			VAR _ClockW =
			IF(
			    _SecW > 0,
			    FORMAT(_DaysW,"0") & "d " &
			    FORMAT(_HoursW,"00") & ":" &
			    FORMAT(_MinW,"00") & ":" &
			    FORMAT(_SecR,"00"),
			    "LIVE"
			)
			
			
			/* =====================
			   COUNTDOWN — SUMMER
			=====================*/
			
			VAR _SummerDate = DATE(2028,7,14)
			
			VAR _DiffS = _SummerDate - _Now
			VAR _SecS = INT(_DiffS * 86400)
			
			VAR _DaysS = INT(_SecS / 86400)
			VAR _HoursS = INT(MOD(_SecS,86400)/3600)
			VAR _MinS = INT(MOD(_SecS,3600)/60)
			VAR _SecS2 = MOD(_SecS,60)
			
			VAR _ClockS =
			IF(
			    _SecS > 0,
			    FORMAT(_DaysS,"0") & "d " &
			    FORMAT(_HoursS,"00") & ":" &
			    FORMAT(_MinS,"00") & ":" &
			    FORMAT(_SecS2,"00"),
			    "LIVE"
			)
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   MASTER
			=====================*/
			
			.masterBox{
			  width:100%;
			  background:#ffffff;
			  border-radius:16px;
			  border:1px solid #e5e7eb;
			
			  padding:10px 12px;
			
			  box-shadow:0 2px 6px rgba(0,0,0,.07);
			  font-family:Segoe UI;
			}
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.pageHeader{
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			
			  margin-bottom:8px;
			
			  flex-wrap:wrap;
			  gap:8px;
			}
			
			.headerLeft{
			  display:flex;
			  flex-direction:column;
			}
			
			.mainTitle{
			  font-size:17px;
			  font-weight:900;
			  color:#111827;
			
			  display:flex;
			  align-items:center;
			  gap:6px;
			}
			
			.badgeLive{
			  background:#dc2626;
			  color:white;
			
			  font-size:9px;
			  font-weight:800;
			
			  padding:2px 5px;
			  border-radius:4px;
			}
			
			.subTitle{
			  font-size:9px;
			  color:#6b7280;
			  margin-top:1px;
			}
			
			
			/* =====================
			   COUNTDOWN
			=====================*/
			
			.countWrap{
			  display:flex;
			  gap:10px;
			}
			
			.countBox{
			  text-align:right;
			  min-width:100px;
			}
			
			.countTitle{
			  font-size:8px;
			  font-weight:700;
			  color:#dc2626;
			  text-transform:uppercase;
			}
			
			.countTime{
			  font-size:12px;
			  font-weight:900;
			  color:#111827;
			}
			
			.countSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   GRID
			=====================*/
			
			.flipGrid{
			  display:grid;
			  grid-template-columns:repeat(auto-fit,minmax(120px,1fr));
			  gap:7px;
			}
			
			
			/* =====================
			   CARD
			=====================*/
			
			.flipCard{
			  width:100%;
			  height:73px;
			  perspective:1000px;
			}
			
			.flipInner{
			  width:100%;
			  height:100%;
			
			  position:relative;
			
			  transition:transform .6s ease;
			  transform-style:preserve-3d;
			}
			
			.flipCard:hover .flipInner{
			  transform:rotateY(180deg);
			}
			
			
			/* =====================
			   FACES
			=====================*/
			
			.flipFront,
			.flipBack{
			  position:absolute;
			
			  width:100%;
			  height:100%;
			
			  backface-visibility:hidden;
			
			  border-radius:10px;
			  overflow:hidden;
			
			  border:1px solid #e5e7eb;
			  background:white;
			
			  box-shadow:0 2px 5px rgba(0,0,0,.07);
			
			  padding:6px;
			
			  display:flex;
			  flex-direction:column;
			  justify-content:center;
			  align-items:center;
			
			  text-align:center;
			}
			
			.flipBack{
			  transform:rotateY(180deg);
			  background:#f8fafc;
			}
			
			
			/* =====================
			   HEADER CARD (LINHA FULL)
			=====================*/
			
			.cardHeader{
			  width:100%;                 /* ocupa todo o card */
			  text-align:center;
			
			  font-size:10px;
			  font-weight:900;
			  color:#dc2626;
			
			  text-transform:uppercase;
			
			  padding-bottom:2px;
			  margin-bottom:3px;
			
			  border-bottom:2px solid #dc2626; /* LINHA DE PONTA A PONTA */
			}
			
			
			/* =====================
			   CONTENT
			=====================*/
			
			.cardValue{
			  font-size:17px;
			  font-weight:900;
			  color:#111827;
			
			  margin:2px 0;
			}
			
			.cardSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   BACK
			=====================*/
			
			.backIcon{
			  font-size:14px;
			  margin-bottom:3px;
			}
			
			.backText{
			  font-size:9px;
			  color:#374151;
			  line-height:1.25;
			
			  text-align:center;
			}
			
			</style>
			
			
			<div class='masterBox'>
			
			
			<!-- HEADER -->
			<div class='pageHeader'>
			
			
			<!-- LEFT -->
			<div class='headerLeft'>
			
			<div class='mainTitle'>
			🏅 Olympic Performance Dashboard
			<span class='badgeLive'>LIVE</span>
			</div>
			
			<div class='subTitle'>
			Global Medal History • 1896–2022 • " & _Editions & " Editions
			</div>
			
			</div>
			
			
			<!-- RIGHT -->
			<div class='countWrap'>
			
			
			<!-- WINTER -->
			<div class='countBox'>
			
			<div class='countTitle'>Winter Games</div>
			
			<div class='countTime'>
			" & _ClockW & "
			</div>
			
			<div class='countSub'>
			Milano Cortina 2026
			</div>
			
			</div>
			
			
			<!-- SUMMER -->
			<div class='countBox'>
			
			<div class='countTitle'>Summer Games</div>
			
			<div class='countTime'>
			" & _ClockS & "
			</div>
			
			<div class='countSub'>
			Los Angeles 2028
			</div>
			
			</div>
			
			</div>
			
			
			</div>
			
			
			<!-- KPI GRID -->
			<div class='flipGrid'>
			
			
			<!-- TOTAL -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Total Medals</div>
			<div class='cardValue'>" & _Total & "</div>
			<div class='cardSub'>Across " & _Editions & " Editions</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🏅</div>
			<div class='backText'>
			" & _Total & " medals across " & _Editions & " editions.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- COUNTRY -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Leading Nation</div>
			<div class='cardValue'>" & _Country & "</div>
			<div class='cardSub'>Score " & FORMAT(_Score,"#,0") & "</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🌍</div>
			<div class='backText'>
			" & _Country & " leads with " & FORMAT(_Score,"#,0") & " points.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- DISCIPLINE -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Top Discipline</div>
			<div class='cardValue' style='font-size:14px;'>" & _TopDiscipline & "</div>
			<div class='cardSub'>Score " & FORMAT(_DisciplineScore,"#,0") & "</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🏟️</div>
			<div class='backText'>
			" & _TopDiscipline & " contributes " & FORMAT(_DisciplineScore,"#,0") & " points.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- SCORE -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Medal Score</div>
			<div class='cardValue'>" & FORMAT([Medal Score],"#,0") & "</div>
			<div class='cardSub'>Weighted Index</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>📊</div>
			<div class='backText'>
			Quality-adjusted medal performance.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- MOMENTUM -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Momentum</div>
			<div class='cardValue'>" & _Growth & "</div>
			<div class='cardSub'>Recent Cycles</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>📈</div>
			<div class='backText'>
			Change of " & _Growth & " in recent cycles.
			</div>
			</div>
			
			</div></div>
			
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 5d0e0dad-8a51-44b1-93b3-96ea45806b8a

	measure 'Flip Card Avg Edition' = ```
			
			VAR _Avg =
			FORMAT(
			AVERAGEX(
			VALUES('athlete medals'[Game Slug]),
			[Total Medals]
			),
			"#,0"
			)
			
			RETURN
			
			"
			<style>
			
			/* ===== FLIP ENGINE ===== */
			
			.flipCard{width:220px;height:140px;perspective:1200px;}
			.flipInner{width:100%;height:100%;transition:.9s;transform-style:preserve-3d;}
			.flipCard:hover .flipInner{transform:rotateY(180deg);}
			
			.flipFront,.flipBack{
			position:absolute;width:100%;height:100%;
			border-radius:16px;
			background:#020617;
			border:1px solid #38bdf8;
			box-shadow:0 0 18px rgba(56,189,248,.5);
			color:white;backface-visibility:hidden;
			}
			
			.flipBack{transform:rotateY(180deg);border-color:#22c55e;}
			
			.flipHeader{
			background:#0284c7;padding:6px;
			font-size:12px;font-weight:800;text-align:center;
			}
			
			.flipContent{padding:12px;}
			
			@keyframes glow{
			0%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			50%{box-shadow:0 0 16px rgba(56,189,248,.9);}
			100%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			}
			
			.flipFront,.flipBack{animation:glow 4s infinite;}
			
			</style>
			
			
			<div class='flipCard'>
			<div class='flipInner'>
			
			<!-- FRONT -->
			<div class='flipFront'>
			
			<div class='flipHeader'>📊 AVG PER EDITION</div>
			
			<div class='flipContent'>
			
			<div style='font-size:30px;font-weight:900;'>" & _Avg & "</div>
			<div style='font-size:12px;color:#94a3b8;'>Medals / Games</div>
			
			</div>
			</div>
			
			
			<!-- BACK -->
			<div class='flipBack'>
			
			<div class='flipHeader' style='background:#22c55e;color:#020617;'>
			🏆 CONTEXT
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:16px;font-weight:800;'>Historical Average</div>
			<div style='font-size:11px;color:#94a3b8;'>All editions</div>
			
			</div>
			</div>
			
			</div>
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 70036428-6e3c-44d4-8b57-e8ff66b10440

	measure 'Flip Card Global Share' = ```
			
			VAR _Country =
			CALCULATE(
			SELECTEDVALUE(results[NOC]),
			TOPN(1,ALL(results[NOC]),[Medal Score],DESC)
			)
			
			VAR _Share =
			FORMAT(
			DIVIDE(
			CALCULATE([Total Medals],results[NOC]=_Country),
			[Total Medals]
			),
			"0.0%"
			)
			
			RETURN
			
			"
			<style>
			
			/* ===== FLIP ENGINE ===== */
			
			.flipCard{width:220px;height:140px;perspective:1200px;}
			.flipInner{width:100%;height:100%;transition:.9s;transform-style:preserve-3d;}
			.flipCard:hover .flipInner{transform:rotateY(180deg);}
			
			.flipFront,.flipBack{
			position:absolute;width:100%;height:100%;
			border-radius:16px;
			background:#020617;
			border:1px solid #38bdf8;
			box-shadow:0 0 18px rgba(56,189,248,.5);
			color:white;backface-visibility:hidden;
			}
			
			.flipBack{transform:rotateY(180deg);border-color:#22c55e;}
			
			.flipHeader{
			background:#0284c7;padding:6px;
			font-size:12px;font-weight:800;text-align:center;
			}
			
			.flipContent{padding:12px;}
			
			@keyframes glow{
			0%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			50%{box-shadow:0 0 16px rgba(56,189,248,.9);}
			100%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			}
			
			.flipFront,.flipBack{animation:glow 4s infinite;}
			
			</style>
			
			
			<div class='flipCard'>
			<div class='flipInner'>
			
			<div class='flipFront'>
			
			<div class='flipHeader'>🌍 GLOBAL SHARE</div>
			
			<div class='flipContent'>
			
			<div style='font-size:28px;font-weight:900;'>" & _Share & "</div>
			<div style='font-size:12px;color:#94a3b8;'>Top Nation</div>
			
			</div>
			</div>
			
			
			<div class='flipBack'>
			
			<div class='flipHeader' style='background:#22c55e;color:#020617;'>
			📈 LEADER
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:16px;font-weight:800;'>" & _Country & "</div>
			<div style='font-size:11px;color:#94a3b8;'>World Dominance</div>
			
			</div>
			</div>
			
			</div>
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 941845f4-508c-4945-a659-bab020fe0b67

	measure 'Flip Card Efficiency' = ```
			
			VAR _Athlete =
			CALCULATE(
			SELECTEDVALUE(athletes[Athlete]),
			TOPN(1,ALL(athletes[Athlete]),[Total Medals],DESC)
			)
			
			VAR _Medals =
			CALCULATE(
			[Total Medals],
			athletes[Athlete]=_Athlete
			)
			
			VAR _Games =
			CALCULATE(
			DISTINCTCOUNT(results[Game Slug]),
			results[athlete_full_name]=_Athlete
			)
			
			VAR _Eff =
			FORMAT(
			DIVIDE(_Medals,_Games),
			"0.0"
			)
			
			RETURN
			
			"
			<style>
			
			/* ===== FLIP ENGINE ===== */
			
			.flipCard{width:220px;height:140px;perspective:1200px;}
			.flipInner{width:100%;height:100%;transition:.9s;transform-style:preserve-3d;}
			.flipCard:hover .flipInner{transform:rotateY(180deg);}
			
			.flipFront,.flipBack{
			position:absolute;width:100%;height:100%;
			border-radius:16px;
			background:#020617;
			border:1px solid #38bdf8;
			box-shadow:0 0 18px rgba(56,189,248,.5);
			color:white;backface-visibility:hidden;
			}
			
			.flipBack{transform:rotateY(180deg);border-color:#22c55e;}
			
			.flipHeader{
			background:#0284c7;padding:6px;
			font-size:12px;font-weight:800;text-align:center;
			}
			
			.flipContent{padding:12px;}
			
			@keyframes glow{
			0%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			50%{box-shadow:0 0 16px rgba(56,189,248,.9);}
			100%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			}
			
			.flipFront,.flipBack{animation:glow 4s infinite;}
			
			</style>
			
			
			<div class='flipCard'>
			<div class='flipInner'>
			
			<div class='flipFront'>
			
			<div class='flipHeader'>⚡ EFFICIENCY</div>
			
			<div class='flipContent'>
			
			<div style='font-size:28px;font-weight:900;'>" & _Eff & "</div>
			<div style='font-size:12px;color:#94a3b8;'>Medals / Games</div>
			
			</div>
			</div>
			
			
			<div class='flipBack'>
			
			<div class='flipHeader' style='background:#22c55e;color:#020617;'>
			👤 ATHLETE
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:15px;font-weight:800;'>" & _Athlete & "</div>
			<div style='font-size:11px;color:#94a3b8;'>Career Consistency</div>
			
			</div>
			</div>
			
			</div>
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: e9df23bc-50b5-4556-9998-f063b7105e3f

	measure 'Flip Card Stability' = ```
			
			VAR _Growth = [Medal Growth]
			
			VAR _Index =
			IF(
			ABS(_Growth)<0.05,"High Stability",
			IF(_Growth>0,"Growing","Declining")
			)
			
			RETURN
			
			"
			<style>
			
			/* ===== FLIP ENGINE ===== */
			
			.flipCard{width:220px;height:140px;perspective:1200px;}
			.flipInner{width:100%;height:100%;transition:.9s;transform-style:preserve-3d;}
			.flipCard:hover .flipInner{transform:rotateY(180deg);}
			
			.flipFront,.flipBack{
			position:absolute;width:100%;height:100%;
			border-radius:16px;
			background:#020617;
			border:1px solid #38bdf8;
			box-shadow:0 0 18px rgba(56,189,248,.5);
			color:white;backface-visibility:hidden;
			}
			
			.flipBack{transform:rotateY(180deg);border-color:#22c55e;}
			
			.flipHeader{
			background:#0284c7;padding:6px;
			font-size:12px;font-weight:800;text-align:center;
			}
			
			.flipContent{padding:12px;}
			
			@keyframes glow{
			0%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			50%{box-shadow:0 0 16px rgba(56,189,248,.9);}
			100%{box-shadow:0 0 6px rgba(56,189,248,.4);}
			}
			
			.flipFront,.flipBack{animation:glow 4s infinite;}
			
			</style>
			
			
			<div class='flipCard'>
			<div class='flipInner'>
			
			<div class='flipFront'>
			
			<div class='flipHeader'>📊 STABILITY</div>
			
			<div class='flipContent'>
			
			<div style='font-size:18px;font-weight:900;'>" & _Index & "</div>
			<div style='font-size:12px;color:#94a3b8;'>Cycle Balance</div>
			
			</div>
			</div>
			
			
			<div class='flipBack'>
			
			<div class='flipHeader' style='background:#22c55e;color:#020617;'>
			📈 TREND
			</div>
			
			<div class='flipContent'>
			
			<div style='font-size:18px;font-weight:800;'>
			" & FORMAT(_Growth,"0.0%") & "
			</div>
			
			<div style='font-size:11px;color:#94a3b8;'>Last Cycles</div>
			
			</div>
			</div>
			
			</div>
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 86eff1b4-31af-435c-90e6-046c1b3cd1df

	measure 'Olympic KPI Flip Cards ESPN Clean v2' = ```
			
			
			VAR _Total = FORMAT([Total Medals], "#,0")
			
			VAR _Country =
			CALCULATE(
			    SELECTEDVALUE(results[NOC]),
			    TOPN(1,ALL(results[NOC]),[Medal Score],DESC)
			)
			
			VAR _Score =
			CALCULATE([Medal Score],results[NOC]=_Country)
			
			VAR _TopDiscipline =
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(1,ALL(results[Discipline]),[Medal Score],DESC)
			)
			
			VAR _DisciplineScore =
			CALCULATE([Medal Score],results[Discipline]=_TopDiscipline)
			
			VAR _Growth = FORMAT([Medal Growth],"0.0%")
			
			RETURN
			
			"
			<style>
			
			/* =====================
			   GRID
			=====================*/
			
			.flipGrid{
			  display:grid;
			  grid-template-columns:repeat(auto-fit,minmax(150px,1fr));
			  gap:12px;
			  width:100%;
			}
			
			/* =====================
			   CARD
			=====================*/
			
			.flipCard{
			  width:100%;
			  max-width:170px;
			  height:130px;
			  perspective:1000px;
			}
			
			.flipInner{
			  width:100%;
			  height:100%;
			  position:relative;
			  transition:transform .7s ease;
			  transform-style:preserve-3d;
			}
			
			.flipCard:hover .flipInner{
			  transform:rotateY(180deg);
			}
			
			/* Faces */
			
			.flipFront,
			.flipBack{
			  position:absolute;
			  width:100%;
			  height:100%;
			  backface-visibility:hidden;
			  border-radius:12px;
			  overflow:hidden;
			  border:1px solid #e5e7eb;
			  background:white;
			  box-shadow:0 2px 6px rgba(0,0,0,.08);
			  padding:8px 10px;
			}
			
			/* Back */
			
			.flipBack{
			  transform:rotateY(180deg);
			  background:#f8fafc;
			}
			
			/* =====================
			   HEADER
			=====================*/
			
			.cardHeader{
			  font-size:10px;
			  font-weight:800;
			  color:#dc2626;
			  text-transform:uppercase;
			  border-bottom:2px solid #dc2626;
			  padding-bottom:2px;
			  margin-bottom:4px;
			  letter-spacing:.3px;
			}
			
			/* =====================
			   CONTENT
			=====================*/
			
			.cardValue{
			  font-size:22px;
			  font-weight:900;
			  color:#111827;
			  line-height:1.1;
			}
			
			.cardSub{
			  font-size:11px;
			  color:#6b7280;
			  margin-top:3px;
			}
			
			/* Back */
			
			.backText{
			  font-size:11px;
			  color:#374151;
			  line-height:1.4;
			}
			
			.backIcon{
			  font-size:18px;
			  margin-bottom:4px;
			}
			
			</style>
			
			
			<div class='flipGrid'>
			
			
			<!-- TOTAL MEDALS -->
			<div class='flipCard'>
			<div class='flipInner'>
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Total Medals</div>
			
			<div class='cardValue'>" & _Total & "</div>
			<div class='cardSub'>All Games</div>
			
			</div>
			
			<div class='flipBack'>
			
			<div class='backIcon'>🏅</div>
			
			<div class='backText'>
			Total number of medals awarded across all Olympic editions, reflecting historical participation.
			</div>
			
			</div>
			
			</div>
			</div>
			
			
			<!-- LEADING NATION -->
			<div class='flipCard'>
			<div class='flipInner'>
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Leading Nation</div>
			
			<div class='cardValue'>" & _Country & "</div>
			<div class='cardSub'>Top Score</div>
			
			</div>
			
			<div class='flipBack'>
			
			<div class='backIcon'>🌍</div>
			
			<div class='backText'>
			Country with the highest weighted medal score, showing sustained Olympic dominance.
			</div>
			
			</div>
			
			</div>
			</div>
			
			
			<!-- TOP DISCIPLINE -->
			<div class='flipCard'>
			<div class='flipInner'>
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Top Discipline</div>
			
			<div class='cardValue' style='font-size:16px;'>" & _TopDiscipline & "</div>
			<div class='cardSub'>Score: " & FORMAT(_DisciplineScore,"#,0") & "</div>
			
			</div>
			
			<div class='flipBack'>
			
			<div class='backIcon'>🏟️</div>
			
			<div class='backText'>
			Sport discipline with the highest medal impact, highlighting competitive specialization.
			</div>
			
			</div>
			
			</div>
			</div>
			
			
			<!-- MEDAL SCORE -->
			<div class='flipCard'>
			<div class='flipInner'>
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Medal Score</div>
			
			<div class='cardValue'>" & FORMAT([Medal Score],"#,0") & "</div>
			<div class='cardSub'>Weighted Index</div>
			
			</div>
			
			<div class='flipBack'>
			
			<div class='backIcon'>📊</div>
			
			<div class='backText'>
			Weighted index based on Gold, Silver and Bronze medals to measure performance quality.
			</div>
			
			</div>
			
			</div>
			</div>
			
			
			<!-- MOMENTUM -->
			<div class='flipCard'>
			<div class='flipInner'>
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Momentum</div>
			
			<div class='cardValue'>" & _Growth & "</div>
			<div class='cardSub'>Recent Trend</div>
			
			</div>
			
			<div class='flipBack'>
			
			<div class='backIcon'>📈</div>
			
			<div class='backText'>
			Shows recent growth or decline in medal performance across Olympic cycles.
			</div>
			
			</div>
			
			</div>
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 3305b25e-1428-4008-b890-44aae945658d

	measure 'TT Total Medals' = ```
			
			CALCULATE(
			    [Total Medals],
			    ALLSELECTED(results)
			)
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: 6c60e2ab-23f1-4e71-9ea8-5ed0a0095475

	measure 'TT Medal Score' = ```
			
			CALCULATE(
			    [Medal Score],
			    ALLSELECTED(results)
			)
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: 1c2a5e00-7b25-4685-99af-df3a06cd7c98

	measure 'TT Top Athlete' = ```
			
			VAR _Athlete =
			    CALCULATE(
			        SELECTEDVALUE(athletes[Athlete]),
			        TOPN(
			            1,
			            ALL(athletes[Athlete]),
			            [Total Medals],
			            DESC
			        )
			    )
			RETURN
			_Athlete
			
			```
		displayFolder: Dash 1
		lineageTag: 2e79a3c5-0d94-4d51-bf01-b121550cf982

	measure 'TT Top Sport' = ```
			
			VAR _Sport =
			    CALCULATE(
			        SELECTEDVALUE(results[Discipline]),
			        TOPN(
			            1,
			            ALL(results[Discipline]),
			            [Medal Score],
			            DESC
			        )
			    )
			RETURN
			_Sport
			
			```
		displayFolder: Dash 1
		lineageTag: 16c15335-fd13-4d8a-a314-dbcb735870d4

	measure 'Tooltip Country Animated' = ```
			
			
			VAR _Country = SELECTEDVALUE(results[NOC])
			
			VAR _Total = FORMAT([Total Medals],"#,0")
			
			VAR _Score = FORMAT([Medal Score],"#,0")
			
			VAR _TopSport =
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(1,ALL(results[Discipline]),[Medal Score],DESC)
			)
			
			VAR _TopAthlete =
			CALCULATE(
			    SELECTEDVALUE(athletes[Athlete]),
			    TOPN(1,ALL(athletes[Athlete]),[Total Medals],DESC)
			)
			
			RETURN
			
			"
			<style>
			
			/* =====================
			   ANIMATIONS
			=====================*/
			
			@keyframes fadeIn {
			  from { opacity:0; transform:translateY(8px); }
			  to   { opacity:1; transform:translateY(0); }
			}
			
			@keyframes glow {
			  0% { box-shadow:0 0 8px rgba(56,189,248,.3); }
			  50%{ box-shadow:0 0 18px rgba(56,189,248,.8); }
			  100%{ box-shadow:0 0 8px rgba(56,189,248,.3); }
			}
			
			/* =====================
			   CONTAINER
			=====================*/
			
			.ttBox{
			  width:260px;
			  background:rgba(2,6,23,.92);
			  border-radius:16px;
			  padding:14px;
			  color:#e5f3ff;
			  font-family:Segoe UI;
			  border:1px solid rgba(56,189,248,.5);
			  animation:fadeIn .35s ease, glow 4s infinite;
			}
			
			/* =====================
			   HEADER
			=====================*/
			
			.ttHeader{
			  font-size:18px;
			  font-weight:900;
			  color:#38bdf8;
			  margin-bottom:6px;
			  text-shadow:0 0 6px rgba(56,189,248,.8);
			}
			
			.ttSub{
			  font-size:11px;
			  color:#94a3b8;
			  margin-bottom:10px;
			}
			
			/* =====================
			   STATS
			=====================*/
			
			.statRow{
			  display:flex;
			  justify-content:space-between;
			  font-size:12px;
			  padding:4px 0;
			  border-bottom:1px solid rgba(148,163,184,.15);
			}
			
			.statRow:last-child{
			  border:none;
			}
			
			.statLabel{
			  color:#94a3b8;
			}
			
			.statValue{
			  font-weight:800;
			  color:#e5f3ff;
			}
			
			/* =====================
			   HIGHLIGHTS
			=====================*/
			
			.highlight{
			  background:rgba(56,189,248,.12);
			  border-radius:10px;
			  padding:8px;
			  margin-top:8px;
			}
			
			.hTitle{
			  font-size:11px;
			  font-weight:700;
			  color:#38bdf8;
			  margin-bottom:2px;
			}
			
			.hValue{
			  font-size:13px;
			  font-weight:800;
			}
			
			</style>
			
			
			<div class='ttBox'>
			
			<div class='ttHeader'>
			🏳️ " & _Country & "
			</div>
			
			<div class='ttSub'>
			Live Olympic Profile
			</div>
			
			
			<div class='statRow'>
			<span class='statLabel'>🏅 Total Medals</span>
			<span class='statValue'>" & _Total & "</span>
			</div>
			
			<div class='statRow'>
			<span class='statLabel'>📊 Medal Score</span>
			<span class='statValue'>" & _Score & "</span>
			</div>
			
			
			<div class='highlight'>
			
			<div class='hTitle'>🏆 Top Sport</div>
			<div class='hValue'>" & _TopSport & "</div>
			
			</div>
			
			
			<div class='highlight'>
			
			<div class='hTitle'>⭐ Top Athlete</div>
			<div class='hValue'>" & _TopAthlete & "</div>
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: bac3f45f-54a1-4fce-926e-62c9b84d76ed

	measure 'Olympic Page Title ESPN Clean' = ```
			
			
			VAR _Total = FORMAT([Total Medals],"#,0")
			
			VAR _Editions =
			DISTINCTCOUNT(hosts[Game Slug])
			
			RETURN
			
			"
			<style>
			
			/* =====================
			   PAGE HEADER
			=====================*/
			
			.pageHeader{
			  background:#ffffff;
			  border:1px solid #e5e7eb;
			  border-radius:18px;
			  padding:16px 20px;
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			  font-family:Segoe UI;
			}
			
			/* Left */
			
			.headerLeft{
			  display:flex;
			  flex-direction:column;
			}
			
			.mainTitle{
			  font-size:26px;
			  font-weight:900;
			  color:#111827;
			  display:flex;
			  align-items:center;
			  gap:10px;
			}
			
			.badgeLive{
			  background:#dc2626;
			  color:white;
			  font-size:11px;
			  font-weight:800;
			  padding:2px 7px;
			  border-radius:4px;
			}
			
			/* Subtitle */
			
			.subTitle{
			  font-size:13px;
			  color:#6b7280;
			  margin-top:3px;
			}
			
			/* Right */
			
			.headerRight{
			  text-align:right;
			}
			
			.statBig{
			  font-size:20px;
			  font-weight:900;
			  color:#111827;
			}
			
			.statSub{
			  font-size:11px;
			  color:#6b7280;
			}
			
			</style>
			
			
			<div class='pageHeader'>
			
			
			<!-- LEFT -->
			<div class='headerLeft'>
			
			<div class='mainTitle'>
			🏅 Olympic Performance Dashboard
			<span class='badgeLive'>LIVE</span>
			</div>
			
			<div class='subTitle'>
			Global Medal History • 1896–2022 • " & _Editions & " Editions
			</div>
			
			</div>
			
			
			<!-- RIGHT -->
			<div class='headerRight'>
			
			<div class='statBig'>" & _Total & "</div>
			
			<div class='statSub'>Total Medals</div>
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 2601b66f-a1c1-41aa-b7df-d020c60de788

	measure 'Olympic Medal Table ESPN FINAL FLAGS v5' = ```
			
			
			/* =========================
			   BASE TABLE
			========================= */
			
			VAR _BaseTable =
			    SUMMARIZE(
			        'athlete medals',
			        'athlete medals'[NOC],
			
			        "Gold",
			            CALCULATE(
			                COUNTROWS('athlete medals'),
			                'athlete medals'[Medal] = "Gold"
			            ),
			
			        "Silver",
			            CALCULATE(
			                COUNTROWS('athlete medals'),
			                'athlete medals'[Medal] = "Silver"
			            ),
			
			        "Bronze",
			            CALCULATE(
			                COUNTROWS('athlete medals'),
			                'athlete medals'[Medal] = "Bronze"
			            ),
			
			        "Total",
			            COUNTROWS('athlete medals'),
			
			        "Score",
			            SUM('athlete medals'[Medal Value]),
			
			        /* PNG FLAG */
			        "Flag",
			            LOOKUPVALUE(
			                countrys[Flag_URL],
			                countrys[country_code],
			                MAX(results[country_code])
			            )
			    )
			
			
			/* =========================
			   RANK
			========================= */
			
			VAR _Table =
			    ADDCOLUMNS(
			        _BaseTable,
			
			        "Rank",
			        RANKX(
			            ALL('athlete medals'[NOC]),
			            CALCULATE( SUM('athlete medals'[Medal Value]) ),
			            ,
			            DESC,
			            DENSE
			        )
			    )
			
			
			/* =========================
			   HTML
			========================= */
			
			RETURN
			
			
			"
			<style>
			
			/* =========================
			   BASE
			========================= */
			
			.tableBox {
			  background:transparent;
			  border-radius:0;
			  padding:0;
			  border:none;
			  box-shadow:none;
			  font-family:Segoe UI;
			}
			
			
			/* =========================
			   HEADER SUPERIOR
			========================= */
			
			.tableHeader {
			  font-size:20px;
			  font-weight:900;
			
			  color:#000000; /* TÍTULO PRETO */
			
			  margin-bottom:6px;
			
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			
			  background:transparent;
			}
			
			.headerBadge {
			  background:#dc2626;
			  color:white;
			
			  font-size:11px;
			  font-weight:700;
			
			  padding:3px 7px;
			  border-radius:5px;
			}
			
			
			/* =========================
			   SCROLL
			========================= */
			
			.scrollBox {
			  max-height:430px;
			  overflow-y:auto;
			
			  background:transparent;
			  border:none;
			
			  position:relative;
			}
			
			
			/* =========================
			   TABLE
			========================= */
			
			table {
			  width:100%;
			  border-collapse:collapse;
			  font-size:13px;
			
			  background:transparent;
			}
			
			
			/* =========================
			   HEADER FIXO (PRETO)
			========================= */
			
			thead th {
			  background:rgba(255,255,255,0.8);
			
			  position:sticky;
			  top:0;
			  z-index:10;
			
			  padding:8px 6px;
			  text-align:left;
			
			  font-weight:900;
			  color:#000000;
			
			  backdrop-filter:blur(4px);
			
			  border-bottom:1px solid rgba(0,0,0,0.25);
			}
			
			
			/* =========================
			   CELLS
			========================= */
			
			td {
			  padding:7px 6px;
			
			  border-bottom:1px solid rgba(255,255,255,0.08);
			
			  background:transparent;
			
			  color:#e5e7eb;
			}
			
			
			/* =========================
			   HOVER
			========================= */
			
			tr:hover {
			  background:rgba(255,255,255,0.08);
			}
			
			
			/* =========================
			   PODIUM
			========================= */
			
			.rank1 { background:rgba(250,204,21,.18); }
			.rank2 { background:rgba(209,213,219,.15); }
			.rank3 { background:rgba(192,132,252,.18); }
			
			
			/* =========================
			   RANK (BRANCO)
			========================= */
			
			.rankCol {
			  font-weight:900;
			  color:#ffffff;
			  width:32px;
			}
			
			
			/* =========================
			   COUNTRY (BRANCO)
			========================= */
			
			.nocCol {
			  display:flex;
			  align-items:center;
			  gap:8px;
			
			  font-weight:800;
			  color:#ffffff;
			}
			
			
			/* =========================
			   FLAG
			========================= */
			
			.flagImg {
			  width:24px;
			  height:16px;
			
			  object-fit:cover;
			
			  border-radius:3px;
			
			  border:1px solid rgba(255,255,255,0.4);
			
			  box-shadow:0 1px 2px rgba(0,0,0,.25);
			}
			
			
			/* =========================
			   SCORE (PRETO)
			========================= */
			
			.scoreCol {
			  font-weight:900;
			  color:#000000;
			}
			
			</style>
			
			
			<div class='tableBox'>
			
			
			<!-- HEADER -->
			
			<div class='tableHeader'>
			
			<div>🏆 Medal Table</div>
			
			<div class='headerBadge'>LIVE</div>
			
			</div>
			
			
			<!-- TABLE -->
			
			<div class='scrollBox'>
			
			
			<table>
			
			
			<thead>
			<tr>
			
			  <th>#</th>
			  <th>Country</th>
			  <th>🥇</th>
			  <th>🥈</th>
			  <th>🥉</th>
			  <th>Total</th>
			  <th>Score</th>
			
			</tr>
			</thead>
			
			
			<tbody>
			
			
			" &
			
			
			CONCATENATEX(
			
			    _Table,
			
			    VAR _Rank = [Rank]
			
			    VAR _Class =
			        IF(
			            _Rank = 1, "rank1",
			            IF(_Rank = 2, "rank2",
			            IF(_Rank = 3, "rank3",""))
			        )
			
			    RETURN
			
			
			"
			<tr class='" & _Class & "'>
			
			<td class='rankCol'>" & _Rank & "</td>
			
			<td class='nocCol'>
			
			<img class='flagImg' src='" & [Flag] & "'/>
			
			" & [NOC] & "
			
			</td>
			
			
			<td>" & [Gold] & "</td>
			<td>" & [Silver] & "</td>
			<td>" & [Bronze] & "</td>
			
			<td><b>" & [Total] & "</b></td>
			
			<td class='scoreCol'>" &
			FORMAT([Score],"#,0") &
			"</td>
			
			</tr>
			
			",
			
			"",
			
			[Rank], ASC
			
			)
			
			
			&
			
			
			"
			</tbody>
			
			
			</table>
			
			
			</div>
			
			
			</div>
			
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 0b747375-6aa9-4b5b-908b-bb98f2d1e7c7

	measure 'Line Insight' = ```
			
			"📈 Olympic medal performance shows steady growth after 1950, driven by global participation."
			
			```
		displayFolder: Dash 1
		lineageTag: 35f5821e-3e7a-4a7c-a2e1-26a1c789aae6

	measure 'Medal Score by Year' = ```
			
			CALCULATE(
			    [Medal Score],
			    ALLEXCEPT('calendar', calendar[Year])
			)
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: 4d08a59a-a03d-49d7-a0dc-1d525186bb32

	measure 'Total Medals by Year' = ```
			
			CALCULATE(
			    [Total Medals],
			    ALLEXCEPT('calendar', calendar[Year])
			)
			
			```
		formatString: 0
		displayFolder: Dash 1
		lineageTag: a07d4a50-9861-4c90-9994-cd0fd7f95385

	measure 'Line Chart Title' = ```
			
			
			VAR _Start = MIN(calendar[Year])
			VAR _End = MAX(calendar[Year])
			
			VAR _Growth =
			DIVIDE(
			    [Medal Score by Year] -
			    CALCULATE([Medal Score by Year], PREVIOUSYEAR(calendar[Date])),
			    CALCULATE([Medal Score by Year], PREVIOUSYEAR(calendar[Date]))
			)
			
			RETURN
			"📈 Olympic Medal Performance (" &
			_Start & "–" & _End &
			")"
			
			```
		displayFolder: Dash 1
		lineageTag: 717dbb7d-7b18-470b-a102-cc4810ed0983

	measure 'Olympic Countdown Live' = ```
			
			
			VAR _EventDate =
			    DATE(2026,2,6) + TIME(0,0,0)
			
			VAR _Now = NOW()
			
			VAR _Diff =
			    _EventDate - _Now
			
			VAR _Seconds =
			    INT(_Diff * 86400)
			
			VAR _Days =
			    INT(_Seconds / 86400)
			
			VAR _Hours =
			    INT(MOD(_Seconds,86400)/3600)
			
			VAR _Minutes =
			    INT(MOD(_Seconds,3600)/60)
			
			VAR _Secs =
			    MOD(_Seconds,60)
			
			RETURN
			
			IF(
			    _Seconds > 0,
			
			    "⏱️ " &
			    _Days & "d " &
			    FORMAT(_Hours,"00") & ":" &
			    FORMAT(_Minutes,"00") & ":" &
			    FORMAT(_Secs,"00"),
			
			    "🎉 Olympic Games Started!"
			)
			
			```
		displayFolder: Dash 1
		lineageTag: dbcbcbc3-05ec-49a0-b1a5-b38168bea1ab

	measure 'Season Selector ESPN' = ```
			
			
			VAR _Season =
			SELECTEDVALUE(Season[Season],"Winter")
			
			VAR _WinterIcon =
			IF(_Season="Winter","◉","○")
			
			VAR _SummerIcon =
			IF(_Season="Summer","◉","○")
			
			RETURN
			
			"
			<div style='
			font-family:Segoe UI;
			font-size:13px;
			font-weight:700;
			color:#111827;
			display:flex;
			gap:16px;
			align-items:center;
			'>
			
			<span>" & _WinterIcon & " Winter</span>
			
			<span>" & _SummerIcon & " Summer</span>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 1e705678-dfd0-493b-9eb1-157665799740

	measure 'Olympic Athlete Cards ESPN GROUP v9' = ```
			
			
			VAR _Base =
			
			FILTER(
			
			    ADDCOLUMNS(
			
			        SUMMARIZE(
			            results,
			            results[athlete_full_name],
			            results[NOC],
			            results[Country]
			        ),
			
			        /* TOTAL MEDALS */
			        "TotalMedals",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] IN {"Gold","Silver","Bronze"}
			        ),
			
			        /* GOLD */
			        "Gold",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] = "Gold"
			        ),
			
			        /* SILVER */
			        "Silver",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] = "Silver"
			        ),
			
			        /* BRONZE */
			        "Bronze",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] = "Bronze"
			        ),
			
			        /* LAST YEAR */
			        "LastYear",
			
			        VAR _LastSlug =
			            CALCULATE(
			                MAX(results[Game Slug])
			            )
			
			        RETURN
			            CALCULATE(
			                MAX(hosts[Year]),
			                hosts[Game Slug] = _LastSlug
			            ),
			
			        /* TOP SPORT */
			        "TopSport",
			
			        VAR _Athlete =
			            SELECTEDVALUE(results[athlete_full_name])
			
			        VAR _SportTable =
			
			            SUMMARIZE(
			                FILTER(
			                    results,
			                    results[athlete_full_name] = _Athlete
			                ),
			                results[Discipline],
			                "Qtd", COUNTROWS(results)
			            )
			
			        RETURN
			            MAXX(
			                TOPN(1,_SportTable,[Qtd],DESC),
			                [Discipline]
			            ),
			
			        /* URL */
			        "URL",
			        CALCULATE(
			            MAX(results[athlete_url])
			        ),
			
			        /* FLAG */
			        "Flag",
			        SWITCH(
			            results[NOC],
			            "USA","🇺🇸","BRA","🇧🇷","GER","🇩🇪","FRA","🇫🇷","GBR","🇬🇧",
			            "CHN","🇨🇳","JPN","🇯🇵","RUS","🇷🇺","ITA","🇮🇹","ESP","🇪🇸",
			            "AUS","🇦🇺","CAN","🇨🇦","KOR","🇰🇷","NED","🇳🇱","SWE","🇸🇪",
			            "NOR","🇳🇴","POL","🇵🇱","ARG","🇦🇷","MEX","🇲🇽","POR","🇵🇹",
			            "🏳️"
			        )
			
			    ),
			
			    NOT ISBLANK(results[athlete_full_name]) &&
			    results[athlete_full_name] <> ""
			)
			
			
			
			VAR _Top =
			    TOPN(25,_Base,[TotalMedals],DESC)
			
			
			
			VAR _Cards =
			
			CONCATENATEX(
			
			    _Top,
			
			"
			
			<a href='https://www.olympics.com" & [URL] & "'
			   target='_blank'
			   class='cardLink'>
			
			<div class='card'>
			
			
			<!-- FRONT -->
			<div class='front'>
			
			<div class='name'>" & [athlete_full_name] & "</div>
			
			<div class='sport'>
			" & IF(ISBLANK([TopSport]),"Multiple Sports",[TopSport]) & "
			</div>
			
			<div class='country'>
			" & [Flag] & " " & [Country] & "
			</div>
			
			<div class='medalBadge'>
			🏅 " & FORMAT([TotalMedals],"#,0") & "
			</div>
			
			<div class='year'>
			Last Games: " & [LastYear] & "
			</div>
			
			</div>
			
			
			<!-- BACK -->
			<div class='back'>
			
			<div class='backHeader'>
			ATHLETE STATS
			</div>
			
			<div class='backBody'>
			
			<div class='line'>🥇 Gold: " & [Gold] & "</div>
			<div class='line'>🥈 Silver: " & [Silver] & "</div>
			<div class='line'>🥉 Bronze: " & [Bronze] & "</div>
			
			<div class='line'>🏟️ Main Sport: " & [TopSport] & "</div>
			
			</div>
			
			<div class='backFooter'>
			Official Olympic Profile
			</div>
			
			</div>
			
			</div>
			
			</a>
			
			",
			
			""
			
			)
			
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   CONTAINER
			=====================*/
			
			.olympicContainer{
			  width:100%;
			  max-width:730px;
			  height:168px;
			
			  background:transparent;
			
			  position:relative;
			
			  padding:4px;
			
			  box-sizing:border-box;
			
			  overflow:hidden;
			}
			
			
			/* =====================
			   HINT
			=====================*/
			
			.hoverHint{
			  position:absolute;
			  top:4px;
			  right:8px;
			
			  font-size:9px;
			  font-weight:600;
			
			  color:#6b7280;
			
			  background:rgba(255,255,255,0.35);
			  backdrop-filter:blur(4px);
			
			  padding:3px 6px;
			  border-radius:7px;
			}
			
			
			/* =====================
			   TITLE
			=====================*/
			
			.groupTitle{
			  font-size:15px;
			  font-weight:900;
			  color:#111827;
			
			  margin-bottom:2px;
			}
			
			.groupSub{
			  font-size:9px;
			  color:#6b7280;
			  margin-bottom:2px;
			}
			
			
			/* =====================
			   SCROLL
			=====================*/
			
			.scrollOuter{
			  overflow-x:auto;
			  overflow-y:hidden;
			
			  width:100%;
			  height:128px;
			}
			
			.scrollWrap{
			  display:flex;
			  gap:10px;
			  padding:3px;
			
			  width:max-content;
			
			  animation:autoScroll 70s linear infinite;
			}
			
			.scrollOuter:hover .scrollWrap{
			  animation-play-state:paused;
			}
			
			
			@keyframes autoScroll{
			  0%{ transform:translateX(0); }
			  100%{ transform:translateX(-50%); }
			}
			
			
			/* =====================
			   CARD
			=====================*/
			
			.card{
			  min-width:190px;
			  height:120px;
			
			  background:rgba(255,255,255,0.6);
			  backdrop-filter:blur(6px);
			
			  border-radius:12px;
			
			  border:1px solid rgba(255,255,255,0.25);
			
			  box-shadow:0 2px 8px rgba(0,0,0,.12);
			
			  position:relative;
			  overflow:hidden;
			
			  transition:.3s ease;
			}
			
			.card:hover{
			  transform:translateY(-4px) scale(1.02);
			  box-shadow:0 10px 18px rgba(0,0,0,.22);
			}
			
			
			/* FRONT */
			
			.front{
			  height:100%;
			  padding:8px;
			
			  display:flex;
			  flex-direction:column;
			  justify-content:space-between;
			}
			
			.name{
			  font-size:12px;
			  font-weight:900;
			  color:#111827;
			
			  white-space:nowrap;
			  overflow:hidden;
			  text-overflow:ellipsis;
			}
			
			.sport{
			  font-size:10px;
			  font-weight:800;
			  color:#2563eb;
			}
			
			.country{
			  font-size:10px;
			  font-weight:700;
			  color:#374151;
			}
			
			.medalBadge{
			  background:rgba(254,226,226,0.7);
			  color:#dc2626;
			
			  font-size:10px;
			  font-weight:900;
			
			  padding:2px 5px;
			  border-radius:6px;
			
			  width:fit-content;
			}
			
			.year{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* BACK */
			
			.back{
			  position:absolute;
			  bottom:-100%;
			  left:0;
			
			  width:100%;
			  height:100%;
			
			  background:rgba(248,250,252,0.9);
			
			  backdrop-filter:blur(6px);
			
			  padding:9px;
			
			  display:flex;
			  flex-direction:column;
			  justify-content:space-between;
			
			  transition:.45s ease;
			
			  border-top:3px solid #dc2626;
			}
			
			.card:hover .back{
			  bottom:0;
			}
			
			
			.backHeader{
			  background:#dc2626;
			  color:white;
			
			  font-size:9px;
			  font-weight:900;
			
			  text-align:center;
			
			  padding:2px;
			  border-radius:5px;
			}
			
			.backBody{
			  font-size:10px;
			  line-height:1.3;
			}
			
			.line{
			  margin-bottom:2px;
			}
			
			.backFooter{
			  font-size:8px;
			  text-align:center;
			  color:#6b7280;
			
			  border-top:1px solid #e5e7eb;
			  padding-top:2px;
			}
			
			
			/* =====================
			   RESPONSIVE
			=====================*/
			
			@media(max-width:600px){
			
			  .card{
			    min-width:160px;
			    height:110px;
			  }
			
			  .groupTitle{
			    font-size:14px;
			  }
			
			  .hoverHint{
			    font-size:8px;
			  }
			
			}
			
			</style>
			
			
			
			<div class='olympicContainer'>
			
			
			<div class='hoverHint'>
			Hover over the cards to see details
			</div>
			
			
			<div>
			
			  <div class='groupTitle'>
			  🏅 Top Olympic Athletes
			  </div>
			
			  <div class='groupSub'>
			  Leading medalists across Olympic history
			  </div>
			
			</div>
			
			
			<div class='scrollOuter'>
			
			  <div class='scrollWrap'>
			
			  " & _Cards & _Cards & "
			
			  </div>
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 6396db52-2d4e-43c3-9833-62832b9f8a26

	measure 'Olympic Athlete Rank Flip Carousel' = ```
			
			
			VAR _Base =
			
			ADDCOLUMNS(
			
			    SUMMARIZE(
			        results,
			        results[athlete_full_name]
			    ),
			
			    /* Medals */
			    "Medals",
			    CALCULATE([Total Medals]),
			
			    /* Score */
			    "Score",
			    CALCULATE([Medal Score]),
			
			    /* Country */
			    "Country",
			    CALCULATE(SELECTEDVALUE(results[NOC])),
			
			    /* Main Sport */
			    "Sport",
			    CALCULATE(
			        SELECTEDVALUE(results[Discipline]),
			        TOPN(
			            1,
			            SUMMARIZE(
			                results,
			                results[Discipline],
			                "S", SUM(results[Medal Value])
			            ),
			            [S],
			            DESC
			        )
			    ),
			
			    /* Last Year */
			    "MaxYear",
			    MAX(hosts[Year]),
			
			    /* URL */
			    "URL",
			    CALCULATE(SELECTEDVALUE(results[athlete_url]))
			)
			
			
			VAR _Top =
			
			TOPN(
			    15,
			    _Base,
			    [Score],
			    DESC
			)
			
			
			VAR _Cards =
			
			CONCATENATEX(
			
			    _Top,
			
			    VAR _Name = [athlete_full_name]
			    VAR _Medals = [Medals]
			    VAR _Score = [Score]
			    VAR _Country = [Country]
			    VAR _Sport = [Sport]
			    VAR _Year = [MaxYear]
			    VAR _URL = [URL]
			
			    VAR _FinalURL =
			        IF(
			            LEFT(_URL,1)="/",
			            "https://www.olympics.com" & _URL,
			            _URL
			        )
			
			    RETURN
			
			"
			<div class='flipCard'
			     onclick=""window.open('" & _FinalURL & "','_blank')"">
			
			<div class='flipInner'>
			
			
			<!-- FRONT -->
			<div class='flipFront'>
			
			<div class='cardHeader'>
			🏅 " & _Name & " (" & _Year & ")
			</div>
			
			<div class='cardMain'>
			
			<div class='mainValue'>" & FORMAT(_Medals,"#,0") & "</div>
			
			<div class='mainSub'>Total Medals</div>
			
			</div>
			
			<div class='cardFooter'>
			Score: " & FORMAT(_Score,"#,0") & "
			</div>
			
			</div>
			
			
			<!-- BACK -->
			<div class='flipBack'>
			
			<div class='cardHeader backHeader'>
			📊 Athlete Profile
			</div>
			
			<div class='backBody'>
			
			<div>🌍 <b>" & _Country & "</b></div>
			
			<div>🏟️ " & IF(ISBLANK(_Sport),"—",_Sport) & "</div>
			
			<div>🥇 Medals: " & FORMAT(_Medals,"#,0") & "</div>
			
			<div>📈 Score: " & FORMAT(_Score,"#,0") & "</div>
			
			<div>📅 Last Games: " & _Year & "</div>
			
			</div>
			
			<div class='backHint'>
			Click to open official profile
			</div>
			
			</div>
			
			</div>
			
			</div>
			",
			
			""
			
			)
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   CONTAINER
			=====================*/
			
			.carouselBox{
			  width:100%;
			  background:#ffffff;
			  border-radius:18px;
			  border:1px solid #e5e7eb;
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			  padding:12px 14px;
			  font-family:Segoe UI;
			  overflow:hidden;
			}
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.carouselHeader{
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			  margin-bottom:8px;
			}
			
			.carouselTitle{
			  font-size:16px;
			  font-weight:900;
			  color:#111827;
			}
			
			.carouselBadge{
			  background:#dc2626;
			  color:white;
			  font-size:10px;
			  font-weight:700;
			  padding:2px 6px;
			  border-radius:4px;
			}
			
			
			/* =====================
			   CAROUSEL
			=====================*/
			
			.carousel{
			  overflow:hidden;
			  position:relative;
			}
			
			.track{
			  display:flex;
			  gap:14px;
			  width:max-content;
			  animation:scrollLoop 55s linear infinite;
			}
			
			
			/* =====================
			   CARD
			=====================*/
			
			.flipCard{
			  width:190px;
			  height:145px;
			  perspective:1200px;
			  cursor:pointer;
			}
			
			.flipInner{
			  width:100%;
			  height:100%;
			  position:relative;
			  transform-style:preserve-3d;
			  transition:.8s;
			}
			
			.flipCard:hover .flipInner{
			  transform:rotateY(180deg);
			}
			
			
			/* Faces */
			
			.flipFront,
			.flipBack{
			  position:absolute;
			  width:100%;
			  height:100%;
			  backface-visibility:hidden;
			  border-radius:14px;
			  background:#f8fafc;
			  border:1px solid #e5e7eb;
			  box-shadow:0 2px 6px rgba(0,0,0,.1);
			  display:flex;
			  flex-direction:column;
			  justify-content:space-between;
			}
			
			.flipBack{
			  transform:rotateY(180deg);
			  background:#f1f5f9;
			}
			
			
			/* Header */
			
			.cardHeader{
			  background:#dc2626;
			  color:white;
			  font-size:11px;
			  font-weight:800;
			  padding:6px 8px;
			  text-align:center;
			  white-space:nowrap;
			  overflow:hidden;
			  text-overflow:ellipsis;
			}
			
			.backHeader{
			  background:#2563eb;
			}
			
			
			/* Front body */
			
			.cardMain{
			  text-align:center;
			  padding:8px;
			}
			
			.mainValue{
			  font-size:28px;
			  font-weight:900;
			  color:#111827;
			}
			
			.mainSub{
			  font-size:11px;
			  color:#6b7280;
			}
			
			.cardFooter{
			  background:#f1f5f9;
			  text-align:center;
			  font-size:11px;
			  font-weight:700;
			  color:#16a34a;
			  padding:4px;
			}
			
			
			/* Back */
			
			.backBody{
			  padding:8px;
			  font-size:12px;
			  color:#111827;
			  line-height:1.4;
			}
			
			.backHint{
			  font-size:10px;
			  text-align:center;
			  color:#6b7280;
			  padding:4px;
			  background:#e5e7eb;
			}
			
			
			/* =====================
			   ANIMATION
			=====================*/
			
			@keyframes scrollLoop{
			
			  0%{ transform:translateX(0); }
			
			  100%{ transform:translateX(-50%); }
			
			}
			
			</style>
			
			
			<div class='carouselBox'>
			
			
			<!-- HEADER -->
			<div class='carouselHeader'>
			
			<div class='carouselTitle'>
			📰 Olympic Athletes — Top Performers
			</div>
			
			<div class='carouselBadge'>LIVE</div>
			
			</div>
			
			
			<!-- CAROUSEL -->
			<div class='carousel'>
			
			<div class='track'>
			
			" & _Cards & _Cards & "
			
			</div>
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 6fd4b9c5-111b-42fa-93eb-89df208efc6e

	measure Medida
		displayFolder: Dash 1
		lineageTag: 291cc245-32d8-412e-9d3a-daf0381f8f07

		annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":null}

		annotation 277cc1b9-af89-4597-8e15-cacc25c0886b = Para usar caracteres especiais em um nome de medida, coloque todo o nome entre colchetes ( [] ) e adicione ] a quaisquer colchetes de fechamento no nome.

	measure 'Olympic Athlete Cards ESPN FINAL v7' = ```
			
			
			VAR BaseTable =
			
			FILTER(
			
			    ADDCOLUMNS(
			
			        SUMMARIZE(
			            results,
			            results[athlete_full_name],
			            results[NOC],
			            results[Country],
			            results[athlete_url]
			        ),
			
			
			        /* TOTAL MEDALS */
			        "TotalMedals",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] IN {"Gold","Silver","Bronze"}
			        ),
			
			
			        /* GOLD */
			        "Gold",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] = "Gold"
			        ),
			
			
			        /* SILVER */
			        "Silver",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] = "Silver"
			        ),
			
			
			        /* BRONZE */
			        "Bronze",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] = "Bronze"
			        ),
			
			
			        /* LAST YEAR */
			        "LastYear",
			        CALCULATE(
			            MAX(hosts[Year])
			        ),
			
			
			        /* MAIN SPORT */
			        "MainSport",
			
			        VAR A = SELECTEDVALUE(results[athlete_full_name])
			
			        VAR T =
			
			            SUMMARIZE(
			                FILTER(
			                    results,
			                    results[athlete_full_name] = A
			                ),
			                results[Discipline],
			                "Qtd", COUNTROWS(results)
			            )
			
			        RETURN
			            MAXX(TOPN(1,T,[Qtd],DESC),[Discipline]),
			
			
			        /* BIO (Bridge Safe) */
			        "Bio",
			        CALCULATE(
			            MAX(athletes[Bio]),
			            TREATAS(
			                VALUES(results[athlete_url]),
			                athletes[Athlete URL]
			            )
			        ),
			
			
			        /* FLAG */
			        "Flag",
			        SWITCH(
			            results[NOC],
			            "USA","🇺🇸","BRA","🇧🇷","GER","🇩🇪","FRA","🇫🇷","GBR","🇬🇧",
			            "CHN","🇨🇳","JPN","🇯🇵","ITA","🇮🇹","ESP","🇪🇸","AUS","🇦🇺",
			            "CAN","🇨🇦","KOR","🇰🇷","NED","🇳🇱","NOR","🇳🇴","SWE","🇸🇪",
			            "🏳️"
			        )
			
			    ),
			
			    NOT ISBLANK(results[athlete_full_name]) &&
			    results[athlete_full_name] <> ""
			
			)
			
			
			VAR TopAthletes =
			    TOPN(20,BaseTable,[TotalMedals],DESC)
			
			
			VAR Cards =
			
			CONCATENATEX(
			
			    TopAthletes,
			
			"
			
			<a href='https://www.olympics.com" & [athlete_url] & "'
			   target='_blank'
			   class='cardLink'>
			
			
			<div class='card'>
			
			
			<!-- FRONT -->
			<div class='front tooltipWrap'>
			
			
			<div class='tooltipBox'>
			<b>Bio</b><br/>
			" & LEFT([Bio],320) & "...
			</div>
			
			
			<div class='name'>
			" & [athlete_full_name] & "
			</div>
			
			
			<div class='sport'>
			" & IF(ISBLANK([MainSport]),"Multiple Sports",[MainSport]) & "
			</div>
			
			
			<div class='country'>
			" & [Flag] & " " & [Country] & "
			</div>
			
			
			<div class='medal'>
			🏅 " & [TotalMedals] & "
			</div>
			
			
			<div class='year'>
			Last Games: " & [LastYear] & "
			</div>
			
			
			</div>
			
			
			<!-- BACK -->
			<div class='back'>
			
			
			<div class='backHeader'>
			ATHLETE STATS
			</div>
			
			
			<div class='backBody'>
			
			<div>🥇 Gold: " & [Gold] & "</div>
			<div>🥈 Silver: " & [Silver] & "</div>
			<div>🥉 Bronze: " & [Bronze] & "</div>
			<div>🏟️ Main: " & [MainSport] & "</div>
			
			</div>
			
			
			<div class='backFooter'>
			Official Olympic Profile
			</div>
			
			
			</div>
			
			
			</div>
			
			</a>
			
			",
			
			"")
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   GROUP TITLE
			=====================*/
			
			.groupTitle{
			  font-size:22px;
			  font-weight:900;
			  color:#111827;
			  margin-bottom:6px;
			}
			
			.groupSub{
			  font-size:13px;
			  color:#6b7280;
			  margin-bottom:12px;
			}
			
			
			/* =====================
			   AUTO SCROLL
			=====================*/
			
			.scrollOuter{
			  overflow-x:auto;
			  width:100%;
			}
			
			.scrollWrap{
			  display:flex;
			  gap:14px;
			  padding:6px;
			  width:max-content;
			
			  animation:autoScroll 90s linear infinite;
			}
			
			.scrollOuter:hover .scrollWrap{
			  animation-play-state:paused;
			}
			
			
			@keyframes autoScroll{
			  from{ transform:translateX(0); }
			  to{ transform:translateX(-50%); }
			}
			
			
			/* Scrollbar */
			
			.scrollOuter::-webkit-scrollbar{
			  height:6px;
			}
			
			.scrollOuter::-webkit-scrollbar-thumb{
			  background:#dc2626;
			  border-radius:10px;
			}
			
			
			/* =====================
			   LINK
			=====================*/
			
			.cardLink{
			  text-decoration:none;
			  color:inherit;
			}
			
			
			/* =====================
			   CARD
			=====================*/
			
			.card{
			  width:210px;
			  height:175px;
			
			  background:#ffffff;
			  border-radius:14px;
			  border:1px solid #e5e7eb;
			
			  box-shadow:0 3px 10px rgba(0,0,0,.12);
			
			  position:relative;
			  overflow:hidden;
			
			  transition:.3s;
			}
			
			.card:hover{
			  transform:translateY(-4px);
			  box-shadow:0 10px 22px rgba(0,0,0,.18);
			}
			
			
			/* FRONT */
			
			.front{
			  padding:12px;
			
			  height:100%;
			
			  display:flex;
			  flex-direction:column;
			  justify-content:space-between;
			}
			
			.name{
			  font-size:14px;
			  font-weight:900;
			  color:#111827;
			
			  white-space:nowrap;
			  overflow:hidden;
			  text-overflow:ellipsis;
			}
			
			.sport{
			  font-size:12px;
			  font-weight:800;
			  color:#2563eb;
			}
			
			.country{
			  font-size:12px;
			  font-weight:700;
			  color:#374151;
			}
			
			.medal{
			  background:#fee2e2;
			  color:#dc2626;
			
			  font-size:12px;
			  font-weight:900;
			
			  padding:4px 7px;
			  border-radius:7px;
			
			  width:fit-content;
			}
			
			.year{
			  font-size:11px;
			  color:#6b7280;
			}
			
			
			/* BACK */
			
			.back{
			  position:absolute;
			  bottom:-100%;
			  width:100%;
			  height:100%;
			
			  background:#f8fafc;
			
			  padding:12px;
			
			  transition:.4s ease;
			
			  border-top:3px solid #dc2626;
			}
			
			.card:hover .back{
			  bottom:0;
			}
			
			.backHeader{
			  background:#dc2626;
			  color:white;
			
			  font-size:11px;
			  font-weight:900;
			
			  padding:4px;
			  border-radius:6px;
			
			  text-align:center;
			}
			
			.backBody{
			  font-size:12px;
			  line-height:1.5;
			}
			
			.backFooter{
			  font-size:9px;
			  color:#6b7280;
			  text-align:center;
			  margin-top:4px;
			}
			
			
			/* =====================
			   TOOLTIP
			=====================*/
			
			.tooltipWrap{
			  position:relative;
			}
			
			.tooltipBox{
			  position:absolute;
			
			  bottom:115%;
			  left:50%;
			  transform:translateX(-50%);
			
			  width:260px;
			
			  background:#111827;
			  color:#f9fafb;
			
			  padding:10px 12px;
			
			  border-radius:10px;
			
			  font-size:11px;
			  line-height:1.5;
			
			  box-shadow:0 8px 20px rgba(0,0,0,.35);
			
			  opacity:0;
			  pointer-events:none;
			
			  transition:.25s ease;
			
			  z-index:50;
			}
			
			.tooltipBox:after{
			  content:'';
			  position:absolute;
			
			  top:100%;
			  left:50%;
			  transform:translateX(-50%);
			
			  border-width:6px;
			  border-style:solid;
			  border-color:#111827 transparent transparent transparent;
			}
			
			.tooltipWrap:hover .tooltipBox{
			  opacity:1;
			}
			
			</style>
			
			
			<!-- TITLE -->
			<div>
			
			<div class='groupTitle'>
			🏅 Top Olympic Athletes
			</div>
			
			<div class='groupSub'>
			Leading medalists across Olympic history
			</div>
			
			</div>
			
			
			<div class='scrollOuter'>
			
			<div class='scrollWrap'>
			
			" & Cards & Cards & "
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 1
		lineageTag: 8081d3b0-b324-4329-84bd-101562070c3a

	measure 'Top Discipline' = ```
			
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(1,ALL(results[Discipline]),[Total Medals])
			)
			
			```
		displayFolder: Dash 2
		lineageTag: 7c9379d9-3a01-4a35-8e94-61c66c427862

	measure 'Best Nation' = ```
			
			CALCULATE(
			    SELECTEDVALUE(results[NOC]),
			    TOPN(1,ALL(results[NOC]),[Medal Score])
			)
			
			```
		displayFolder: Dash 2
		lineageTag: c88cf20d-09b5-4b9e-8d58-ff351ca66e88

	measure 'Olympic Country Tooltip HTML v5' = ```
			
			
			/* ==========================
			   BASIC DATA
			========================== */
			
			VAR _Country =
			SELECTEDVALUE(results[Country])
			
			VAR _Score =
			FORMAT([Medal Score],"#,0")
			
			VAR _Total =
			FORMAT([Total Medals],"#,0")
			
			VAR _Gold =
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    'athlete medals'[Medal] = "Gold"
			)
			
			VAR _Silver =
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    'athlete medals'[Medal] = "Silver"
			)
			
			VAR _Bronze =
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    'athlete medals'[Medal] = "Bronze"
			)
			
			VAR _TopDiscipline =
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(
			        1,
			        ALL(results[Discipline]),
			        [Total Medals],
			        DESC
			    )
			)
			
			VAR _Season =
			SELECTEDVALUE(hosts[Season],"All")
			
			
			/* ==========================
			   HTML OUTPUT
			========================== */
			
			RETURN
			
			"
			<div style='
			width:320px;
			height:386px;
			background:#ffffff;
			border-radius:16px;
			border:1px solid #e5e7eb;
			box-shadow:0 4px 12px rgba(0,0,0,.18);
			padding:14px;
			font-family:Segoe UI;
			display:flex;
			flex-direction:column;
			justify-content:space-between;
			'>
			
			
			<!-- HEADER -->
			<div style='border-bottom:2px solid #dc2626;padding-bottom:6px;margin-bottom:6px;'>
			
			<div style='
			font-size:17px;
			font-weight:900;
			color:#111827;
			white-space:nowrap;
			overflow:hidden;
			text-overflow:ellipsis;
			'>
			🌍 " & _Country & "
			</div>
			
			<div style='
			font-size:11px;
			font-weight:800;
			color:#dc2626;
			text-transform:uppercase;
			'>
			" & _Season & " • Performance Summary
			</div>
			
			</div>
			
			
			<!-- KPIs -->
			<div style='display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:10px;'>
			
			
			<div>
			<div style='font-size:11px;color:#6b7280;'>Medal Score</div>
			<div style='font-size:20px;font-weight:900;color:#16a34a;'>" & _Score & "</div>
			</div>
			
			
			<div>
			<div style='font-size:11px;color:#6b7280;'>Total Medals</div>
			<div style='font-size:20px;font-weight:900;color:#111827;'>" & _Total & "</div>
			</div>
			
			
			<div>
			<div style='font-size:11px;color:#6b7280;'>Gold</div>
			<div style='font-size:16px;font-weight:800;'>🥇 " & _Gold & "</div>
			</div>
			
			
			<div>
			<div style='font-size:11px;color:#6b7280;'>Silver / Bronze</div>
			<div style='font-size:14px;font-weight:700;'>
			🥈 " & _Silver & " / 🥉 " & _Bronze & "
			</div>
			</div>
			
			</div>
			
			
			<!-- EMPTY SPACE (CHART PLACEHOLDER) -->
			<div style='
			width:100%;
			height:130px;
			background:#f8fafc;
			border:1px dashed #e5e7eb;
			border-radius:10px;
			display:flex;
			align-items:center;
			justify-content:center;
			margin-bottom:10px;
			color:#9ca3af;
			font-size:12px;
			font-weight:600;
			'>
			
			
			
			</div>
			
			
			<!-- FOOTER -->
			<div style='
			border-top:1px solid #e5e7eb;
			padding-top:6px;
			font-size:12px;
			color:#374151;
			white-space:nowrap;
			overflow:hidden;
			text-overflow:ellipsis;
			'>
			🏟️ Top Discipline: <b>" & _TopDiscipline & "</b>
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 2
		lineageTag: 4a4c91cb-8c09-4d59-844e-576947e570f6

	measure 'Olympic Comparison Table ESPN – Page 2' = ```
			
			
			VAR BaseTable =
			
			SUMMARIZE(
			
			    results,
			    results[Country],
			    results[NOC],
			
			    "Gold",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] = "Gold"
			        ),
			
			    "Silver",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] = "Silver"
			        ),
			
			    "Bronze",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] = "Bronze"
			        ),
			
			    "Total",
			        CALCULATE(
			            COUNTROWS(results),
			            results[Medal (Raw)] IN {"Gold","Silver","Bronze"}
			        ),
			
			    "Score",
			        CALCULATE(
			            [Medal Score]
			        )
			)
			
			
			VAR RankedTable =
			
			ADDCOLUMNS(
			
			    BaseTable,
			
			    "Rank",
			    RANKX(
			        BaseTable,
			        [Score],
			        ,
			        DESC,
			        DENSE
			    )
			)
			
			
			VAR TopCountries =
			    TOPN(15,RankedTable,[Score],DESC)
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   TABLE CONTAINER
			=====================*/
			
			.compBox{
			  background:#ffffff;
			  border-radius:18px;
			  border:1px solid #e5e7eb;
			  padding:14px;
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			
			  font-family:Segoe UI;
			}
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.compHeader{
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			
			  margin-bottom:10px;
			}
			
			.compTitle{
			  font-size:20px;
			  font-weight:900;
			  color:#111827;
			}
			
			.compBadge{
			  background:#dc2626;
			  color:white;
			
			  font-size:11px;
			  font-weight:800;
			
			  padding:2px 6px;
			  border-radius:4px;
			}
			
			
			/* =====================
			   TABLE
			=====================*/
			
			.tableWrap{
			  overflow:hidden;
			  border-radius:12px;
			  border:1px solid #e5e7eb;
			}
			
			.compTable{
			  width:100%;
			  border-collapse:collapse;
			  font-size:13px;
			}
			
			
			/* HEADER */
			
			.compTable thead{
			  background:#f1f5f9;
			}
			
			.compTable th{
			  padding:8px 6px;
			
			  text-align:left;
			
			  font-weight:800;
			  color:#374151;
			
			  border-bottom:1px solid #e5e7eb;
			}
			
			
			/* BODY */
			
			.compTable td{
			  padding:7px 6px;
			  border-bottom:1px solid #f1f5f9;
			
			  color:#111827;
			}
			
			.compTable tr:hover{
			  background:#f9fafb;
			}
			
			
			/* RANK */
			
			.rankCol{
			  font-weight:900;
			  color:#dc2626;
			}
			
			
			/* COUNTRY */
			
			.countryCol{
			  font-weight:800;
			}
			
			
			/* SCORE */
			
			.scoreCol{
			  font-weight:900;
			  color:#16a34a;
			}
			
			
			/* PODIUM */
			
			.rank1{ background:rgba(250,204,21,.15); }
			.rank2{ background:rgba(209,213,219,.18); }
			.rank3{ background:rgba(192,132,252,.15); }
			
			</style>
			
			
			<div class='compBox'>
			
			
			<!-- HEADER -->
			<div class='compHeader'>
			
			<div class='compTitle'>
			🌍 Country Performance Comparison
			</div>
			
			<div class='compBadge'>
			LIVE
			</div>
			
			</div>
			
			
			<!-- TABLE -->
			<div class='tableWrap'>
			
			
			<table class='compTable'>
			
			
			<thead>
			
			<tr>
			  <th>#</th>
			  <th>Country</th>
			  <th>🥇</th>
			  <th>🥈</th>
			  <th>🥉</th>
			  <th>Total</th>
			  <th>Score</th>
			</tr>
			
			</thead>
			
			
			<tbody>
			
			" &
			
			
			CONCATENATEX(
			
			    TopCountries,
			
			    VAR R = [Rank]
			
			    VAR Class =
			        IF(
			            R=1,"rank1",
			            IF(R=2,"rank2",
			            IF(R=3,"rank3",""))
			        )
			
			    RETURN
			
			"
			<tr class='" & Class & "'>
			
			  <td class='rankCol'>" & R & "</td>
			
			  <td class='countryCol'>" & [Country] & "</td>
			
			  <td>" & [Gold] & "</td>
			
			  <td>" & [Silver] & "</td>
			
			  <td>" & [Bronze] & "</td>
			
			  <td><b>" & [Total] & "</b></td>
			
			  <td class='scoreCol'>" &
			        FORMAT([Score],"#,0") &
			  "</td>
			
			</tr>
			",
			
			"",
			
			[Rank], ASC
			
			)
			
			
			&
			
			"
			
			</tbody>
			
			</table>
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 2
		lineageTag: 6f9230de-1963-4605-b07e-63c674705241

	measure 'Olympic Master Header ESPN Live v5 – Page 2' = ```
			
			
			/* =====================
			   CORE METRICS
			=====================*/
			
			VAR _BestCountry =
			CALCULATE(
			    SELECTEDVALUE(results[Country]),
			    TOPN(1,ALL(results[Country]),[Medal Score],DESC)
			)
			
			VAR _BestCountryScore =
			CALCULATE(
			    [Medal Score],
			    results[Country]=_BestCountry
			)
			
			
			VAR _TopDiscipline =
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(1,ALL(results[Discipline]),[Total Medals],DESC)
			)
			
			VAR _TopDisciplineMedals =
			CALCULATE(
			    [Total Medals],
			    results[Discipline]=_TopDiscipline
			)
			
			
			VAR _AvgMedals =
			FORMAT(
			    AVERAGEX(
			        VALUES(hosts[Game Slug]),
			        [Total Medals]
			    ),
			"#,0"
			)
			
			
			VAR _Countries =
			DISTINCTCOUNT(results[Country])
			
			
			VAR _Editions =
			DISTINCTCOUNT(hosts[Game Slug])
			
			
			/* =====================
			   COUNTDOWN — WINTER
			=====================*/
			
			VAR _WinterDate = DATE(2026,2,6)
			VAR _Now = NOW()
			
			VAR _DiffW = _WinterDate - _Now
			VAR _SecW = INT(_DiffW * 86400)
			
			VAR _DaysW = INT(_SecW / 86400)
			VAR _HoursW = INT(MOD(_SecW,86400)/3600)
			VAR _MinW = INT(MOD(_SecW,3600)/60)
			VAR _SecR = MOD(_SecW,60)
			
			VAR _ClockW =
			IF(
			    _SecW > 0,
			    FORMAT(_DaysW,"0") & "d " &
			    FORMAT(_HoursW,"00") & ":" &
			    FORMAT(_MinW,"00") & ":" &
			    FORMAT(_SecR,"00"),
			    "LIVE"
			)
			
			
			/* =====================
			   COUNTDOWN — SUMMER
			=====================*/
			
			VAR _SummerDate = DATE(2028,7,14)
			
			VAR _DiffS = _SummerDate - _Now
			VAR _SecS = INT(_DiffS * 86400)
			
			VAR _DaysS = INT(_SecS / 86400)
			VAR _HoursS = INT(MOD(_SecS,86400)/3600)
			VAR _MinS = INT(MOD(_SecS,3600)/60)
			VAR _SecS2 = MOD(_SecS,60)
			
			VAR _ClockS =
			IF(
			    _SecS > 0,
			    FORMAT(_DaysS,"0") & "d " &
			    FORMAT(_HoursS,"00") & ":" &
			    FORMAT(_MinS,"00") & ":" &
			    FORMAT(_SecS2,"00"),
			    "LIVE"
			)
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   MASTER
			=====================*/
			
			.masterBox{
			  width:100%;
			  background:#ffffff;
			  border-radius:16px;
			  border:1px solid #e5e7eb;
			
			  padding:10px 12px;
			
			  box-shadow:0 2px 6px rgba(0,0,0,.07);
			  font-family:Segoe UI;
			}
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.pageHeader{
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			
			  margin-bottom:8px;
			
			  flex-wrap:wrap;
			  gap:8px;
			}
			
			.headerLeft{
			  display:flex;
			  flex-direction:column;
			}
			
			.mainTitle{
			  font-size:17px;
			  font-weight:900;
			  color:#111827;
			
			  display:flex;
			  align-items:center;
			  gap:6px;
			}
			
			.badgeLive{
			  background:#dc2626;
			  color:white;
			
			  font-size:9px;
			  font-weight:800;
			
			  padding:2px 5px;
			  border-radius:4px;
			}
			
			.subTitle{
			  font-size:9px;
			  color:#6b7280;
			  margin-top:1px;
			}
			
			
			/* =====================
			   COUNTDOWN
			=====================*/
			
			.countWrap{
			  display:flex;
			  gap:10px;
			}
			
			.countBox{
			  text-align:right;
			  min-width:100px;
			}
			
			.countTitle{
			  font-size:8px;
			  font-weight:700;
			  color:#dc2626;
			  text-transform:uppercase;
			}
			
			.countTime{
			  font-size:12px;
			  font-weight:900;
			  color:#111827;
			}
			
			.countSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   GRID
			=====================*/
			
			.flipGrid{
			  display:grid;
			  grid-template-columns:repeat(auto-fit,minmax(120px,1fr));
			  gap:7px;
			}
			
			
			/* =====================
			   CARD
			=====================*/
			
			.flipCard{
			  width:100%;
			  height:73px;
			  perspective:1000px;
			}
			
			.flipInner{
			  width:100%;
			  height:100%;
			
			  position:relative;
			
			  transition:transform .6s ease;
			  transform-style:preserve-3d;
			}
			
			.flipCard:hover .flipInner{
			  transform:rotateY(180deg);
			}
			
			
			/* =====================
			   FACES
			=====================*/
			
			.flipFront,
			.flipBack{
			  position:absolute;
			
			  width:100%;
			  height:100%;
			
			  backface-visibility:hidden;
			
			  border-radius:10px;
			  overflow:hidden;
			
			  border:1px solid #e5e7eb;
			  background:white;
			
			  box-shadow:0 2px 5px rgba(0,0,0,.07);
			
			  padding:6px;
			
			  display:flex;
			  flex-direction:column;
			  justify-content:center;
			  align-items:center;
			
			  text-align:center;
			}
			
			.flipBack{
			  transform:rotateY(180deg);
			  background:#f8fafc;
			}
			
			
			/* =====================
			   HEADER CARD
			=====================*/
			
			.cardHeader{
			  width:100%;
			  text-align:center;
			
			  font-size:10px;
			  font-weight:900;
			  color:#dc2626;
			
			  text-transform:uppercase;
			
			  padding-bottom:2px;
			  margin-bottom:3px;
			
			  border-bottom:2px solid #dc2626;
			}
			
			
			/* =====================
			   CONTENT
			=====================*/
			
			.cardValue{
			  font-size:17px;
			  font-weight:900;
			  color:#111827;
			
			  margin:2px 0;
			
			  white-space:nowrap;
			  overflow:hidden;
			  text-overflow:ellipsis;
			}
			
			.cardSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   BACK
			=====================*/
			
			.backIcon{
			  font-size:14px;
			  margin-bottom:3px;
			}
			
			.backText{
			  font-size:9px;
			  color:#374151;
			  line-height:1.25;
			
			  text-align:center;
			}
			
			</style>
			
			
			<div class='masterBox'>
			
			
			<!-- HEADER -->
			<div class='pageHeader'>
			
			
			<!-- LEFT -->
			<div class='headerLeft'>
			
			<div class='mainTitle'>
			📊 Nations & Sports Analysis
			<span class='badgeLive'>LIVE</span>
			</div>
			
			<div class='subTitle'>
			Country & Discipline Performance • " & _Editions & " Editions
			</div>
			
			</div>
			
			
			<!-- RIGHT -->
			<div class='countWrap'>
			
			
			<!-- WINTER -->
			<div class='countBox'>
			
			<div class='countTitle'>Winter Games</div>
			
			<div class='countTime'>" & _ClockW & "</div>
			
			<div class='countSub'>Milano Cortina 2026</div>
			
			</div>
			
			
			<!-- SUMMER -->
			<div class='countBox'>
			
			<div class='countTitle'>Summer Games</div>
			
			<div class='countTime'>" & _ClockS & "</div>
			
			<div class='countSub'>Los Angeles 2028</div>
			
			</div>
			
			</div>
			
			</div>
			
			
			<!-- KPI GRID -->
			<div class='flipGrid'>
			
			
			<!-- BEST COUNTRY -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Top Nation</div>
			
			<!-- FONTE MENOR AQUI -->
			<div class='cardValue' style='font-size:14px;'>
			" & _BestCountry & "
			</div>
			
			<div class='cardSub'>Score " & FORMAT(_BestCountryScore,"#,0") & "</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🌍</div>
			<div class='backText'>
			" & _BestCountry & " leads Olympic rankings.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- TOP DISCIPLINE -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Top Discipline</div>
			<div class='cardValue' style='font-size:14px;'>" & _TopDiscipline & "</div>
			<div class='cardSub'>" & FORMAT(_TopDisciplineMedals,"#,0") & " Medals</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🏟️</div>
			<div class='backText'>
			" & _TopDiscipline & " dominates Olympic history.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- AVERAGE -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Avg Medals</div>
			<div class='cardValue'>" & _AvgMedals & "</div>
			<div class='cardSub'>Per Games</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>📈</div>
			<div class='backText'>
			Average medals per edition.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- COUNTRIES -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Countries</div>
			<div class='cardValue'>" & _Countries & "</div>
			<div class='cardSub'>Participating</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🌐</div>
			<div class='backText'>
			Global participation growth.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- EDITIONS -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='cardHeader'>Editions</div>
			<div class='cardValue'>" & _Editions & "</div>
			<div class='cardSub'>Total Games</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🏛️</div>
			<div class='backText'>
			Historical Olympic depth.
			</div>
			</div>
			
			</div></div>
			
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 2
		lineageTag: 4d4f4421-3d00-4bbc-a4a5-2e0cee37d511

	measure 'Country Rank' = VAR _Rank = RANKX( ALLSELECTED(results[Country]), [Medal Score], , DESC, DENSE ) RETURN IF( NOT ISBLANK([Medal Score]), _Rank )
		formatString: 0
		displayFolder: Dash 2
		lineageTag: f5e7572a-efcb-4458-9405-bc8a84c66e30

	measure 'Medal Score Trend' = ```
			
			
			CALCULATE(
			    [Medal Score],
			    FILTER(
			        ALL('calendar'),
			        calendar[Year] <= MAX(calendar[Year])
			    )
			)
			
			```
		formatString: 0
		displayFolder: Dash 2
		lineageTag: 378ffe36-a5dc-4dc0-9c79-19b1b85c298f

	measure 'Olympic Trend Title' = ```
			
			
			"📈 Medal Performance Trend (" &
			SELECTEDVALUE(hosts[Season],"All Seasons") &
			")"
			
			```
		displayFolder: Dash 2
		lineageTag: 21310140-2632-4852-b305-1edbc3485619

	measure 'Medal Score Trend (Sparkline)' = ```
			
			
			CALCULATE(
			    [Medal Score],
			    ALLSELECTED(calendar[Year])
			)
			
			```
		formatString: 0
		displayFolder: Dash 2
		lineageTag: b0e36aa2-8be6-4aef-a25b-ab52018944c0

	measure 'Tooltip Medal Score' = ```
			
			FORMAT([Medal Score],"#,0")
			
			```
		displayFolder: Dash 2
		lineageTag: d814dd24-9615-45f4-ab4e-528fa83064a8

	measure 'Tooltip Total Medals' = ```
			
			FORMAT([Total Medals],"#,0")
			
			```
		displayFolder: Dash 2
		lineageTag: 9ac127e3-04b8-4fec-9e87-3cbdc7b27b2f

	measure 'Tooltip Top Discipline' = ```
			
			
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(
			        1,
			        ALL(results[Discipline]),
			        [Total Medals],
			        DESC
			    )
			)
			
			```
		displayFolder: Dash 2
		lineageTag: 6dbccb93-f2d7-40be-9f7f-6494d960384b

	measure 'Medida 2'
		displayFolder: Dash 2
		lineageTag: fa5e2f03-d383-4f5d-8830-82e39a10f008

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Tooltip Season' = ```
			
			SELECTEDVALUE(hosts[Season],"All")
			
			```
		displayFolder: Dash 2
		lineageTag: 0941739b-5f33-47a6-980f-b77ea2049c32

	measure 'Olympic Tooltip Mini Trend HTML' = ```
			
			
			VAR _Data =
			
			TOPN(
			    12,
			    SUMMARIZE(
			        calendar,
			        calendar[Year],
			        "Score", [Medal Score]
			    ),
			    calendar[Year],
			    DESC
			)
			
			VAR _Min =
			MINX(_Data,[Score])
			
			VAR _Max =
			MAXX(_Data,[Score])
			
			VAR _Range =
			IF(_Max-_Min=0,1,_Max-_Min)
			
			
			VAR _Points =
			
			CONCATENATEX(
			
			    _Data,
			
			    VAR _X =
			        FORMAT(
			            DIVIDE(
			                RANKX(_Data,calendar[Year],,ASC)-1,
			                COUNTROWS(_Data)-1
			            )*100,
			        "0.0"
			        )
			
			    VAR _Y =
			        FORMAT(
			            100 -
			            DIVIDE(
			                [Score]-_Min,
			                _Range
			            )*100,
			        "0.0"
			        )
			
			    RETURN
			
			    _X & "," & _Y,
			
			    " "
			
			)
			
			RETURN
			
			"
			<svg
			 width='300'
			 height='40'
			 viewBox='0 0 100 100'
			 preserveAspectRatio='none'
			 style='margin-top:4px;'
			>
			
			<!-- Background -->
			<rect
			 x='0' y='0'
			 width='100' height='100'
			 fill='#f8fafc'
			 rx='6'
			/>
			
			<!-- Line -->
			<polyline
			 fill='none'
			 stroke='#dc2626'
			 stroke-width='3'
			 stroke-linecap='round'
			 stroke-linejoin='round'
			 points='" & _Points & "'
			/>
			
			<!-- Glow -->
			<polyline
			 fill='none'
			 stroke='#fca5a5'
			 stroke-width='6'
			 opacity='0.3'
			 points='" & _Points & "'
			/>
			
			</svg>
			"
			
			```
		displayFolder: Dash 2
		lineageTag: 5867e78c-fc55-401d-aa8a-dc44658cf85c

	measure 'Country Comparison Title' = ```
			
			
			VAR _Season =
			SELECTEDVALUE(
			    hosts[Season],
			    "All Seasons"
			)
			
			VAR _MinYear =
			MIN(hosts[Year])
			
			VAR _MaxYear =
			MAX(hosts[Year])
			
			VAR _Period =
			IF(
			    _MinYear = _MaxYear,
			    FORMAT(_MinYear,"0"),
			    FORMAT(_MinYear,"0") & "–" & FORMAT(_MaxYear,"0")
			)
			
			RETURN
			
			"🌍 Country Performance Comparison — " &
			_Season & " (" & _Period & ")"
			
			```
		displayFolder: Dash 2
		lineageTag: aa98461b-1f34-4839-81ba-c08ce087cdac

	measure 'Athletes Legends Header v1' = ```
			
			
			VAR _Athlete =
			SELECTEDVALUE(athletes[Athlete],"All Athletes")
			
			VAR _Discipline =
			SELECTEDVALUE(results[Discipline],"All Sports")
			
			RETURN
			
			
			"
			<style>
			
			.headerBox{
			  background:white;
			  border-radius:18px;
			  padding:16px 22px;
			  border:1px solid #e5e7eb;
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			  font-family:Segoe UI;
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			}
			
			.headerLeft{
			  display:flex;
			  gap:12px;
			  align-items:center;
			}
			
			.title{
			  font-size:22px;
			  font-weight:900;
			  color:#111827;
			}
			
			.live{
			  background:#dc2626;
			  color:white;
			  font-size:11px;
			  font-weight:700;
			  padding:3px 7px;
			  border-radius:5px;
			}
			
			.sub{
			  font-size:12px;
			  color:#6b7280;
			  margin-top:2px;
			}
			
			.headerRight{
			  font-size:12px;
			  color:#374151;
			  text-align:right;
			}
			
			.filter{
			  font-weight:700;
			  color:#dc2626;
			}
			
			</style>
			
			
			<div class='headerBox'>
			
			
			<div>
			
			  <div class='headerLeft'>
			
			    <div class='title'>🏅 Athletes & Legends</div>
			
			    <div class='live'>LIVE</div>
			
			  </div>
			
			  <div class='sub'>
			  Career Performance • Olympic History 1896–2022
			  </div>
			
			</div>
			
			
			<div class='headerRight'>
			
			<div>Selected Athlete</div>
			<div class='filter'>" & _Athlete & "</div>
			
			<div style='margin-top:4px;'>Sport</div>
			<div class='filter'>" & _Discipline & "</div>
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 3
		lineageTag: 69df453b-d36e-479e-8aa8-b1dc0a55544e

	measure 'Olympic Athletes Header ESPN Flip FINAL v9' = ```
			
			
			
			/* =====================
			   ATHLETE CONTEXT
			=====================*/
			
			VAR _AthleteFilter =
			TREATAS(
			    VALUES(athletes[Athlete URL]),
			    'results'[athlete_url]
			)
			
			
			/* =====================
			   CORE METRICS
			=====================*/
			
			VAR _Score =
			CALCULATE(
			    [Medal Score],
			    _AthleteFilter
			)
			
			VAR _AvgCareer =
			CALCULATE(
			    AVERAGEX(
			        VALUES(athletes[Athlete]),
			        DISTINCTCOUNT(results[Game Slug])
			    ),
			    _AthleteFilter
			)
			
			VAR _TotalAthletes =
			CALCULATE(
			    DISTINCTCOUNT(athletes[Athlete]),
			    _AthleteFilter
			)
			
			VAR _Multi =
			CALCULATE(
			    [Multi Medalists],
			    _AthleteFilter
			)
			
			
			/* =====================
			   TOP MEDALS
			=====================*/
			
			VAR _WinterMedals =
			CALCULATE(
			    [Total Medals],
			    hosts[Season] = "Winter"
			)
			
			VAR _SummerMedals =
			CALCULATE(
			    [Total Medals],
			    hosts[Season] = "Summer"
			)
			
			
			/* =====================
			   FORMAT
			=====================*/
			
			VAR _FmtScore = FORMAT(_Score,"#,##0")
			VAR _FmtAth = FORMAT(_TotalAthletes,"#,##0")
			VAR _FmtMulti = FORMAT(_Multi,"#,##0")
			VAR _FmtAvg = FORMAT(_AvgCareer,"0.0")
			
			VAR _FmtWinter = FORMAT(_WinterMedals,"#,##0")
			VAR _FmtSummer = FORMAT(_SummerMedals,"#,##0")
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   MASTER (PADRÃO PAGE 2)
			=====================*/
			
			.masterBox{
			  width:100%;
			  background:#ffffff;
			  border-radius:16px;
			  border:1px solid #e5e7eb;
			
			  padding:10px 12px;
			
			  box-shadow:0 2px 6px rgba(0,0,0,.07);
			  font-family:'Segoe UI','Inter',Arial,sans-serif;
			}
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.pageHeader{
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			
			  margin-bottom:8px;
			
			  flex-wrap:wrap;
			  gap:8px;
			}
			
			.mainTitle{
			  font-size:17px;
			  font-weight:900;
			  color:#111827;
			
			  display:flex;
			  gap:6px;
			  align-items:center;
			}
			
			.badgeLive{
			  background:#dc2626;
			  color:white;
			
			  font-size:9px;
			  font-weight:800;
			
			  padding:2px 5px;
			  border-radius:4px;
			}
			
			
			/* =====================
			   COUNTS
			=====================*/
			
			.countWrap{
			  display:flex;
			  gap:10px;
			}
			
			.countBox{
			  text-align:right;
			  min-width:100px;
			}
			
			.countTitle{
			  font-size:8px;
			  font-weight:700;
			  color:#dc2626;
			  text-transform:uppercase;
			}
			
			.countTime{
			  font-size:12px;
			  font-weight:900;
			  color:#111827;
			}
			
			.countSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   GRID
			=====================*/
			
			.flipGrid{
			  display:grid;
			  grid-template-columns:repeat(auto-fit,minmax(120px,1fr));
			  gap:7px;
			}
			
			
			/* =====================
			   CARD
			=====================*/
			
			.flipCard{
			  width:100%;
			  height:73px;
			  perspective:1000px;
			}
			
			.flipInner{
			  width:100%;
			  height:100%;
			
			  position:relative;
			
			  transition:transform .6s ease;
			  transform-style:preserve-3d;
			}
			
			.flipCard:hover .flipInner{
			  transform:rotateY(180deg);
			}
			
			
			/* =====================
			   FACES
			=====================*/
			
			.face{
			  position:absolute;
			
			  width:100%;
			  height:100%;
			
			  backface-visibility:hidden;
			
			  border-radius:10px;
			  overflow:hidden;
			
			  border:1px solid #e5e7eb;
			  background:white;
			
			  box-shadow:0 2px 5px rgba(0,0,0,.07);
			
			  padding:6px;
			
			  display:flex;
			  flex-direction:column;
			  justify-content:center;
			  align-items:center;
			
			  text-align:center;
			}
			
			.back{
			  transform:rotateY(180deg);
			  background:#f8fafc;
			}
			
			
			/* =====================
			   CARD HEADER
			=====================*/
			
			.cardTitle{
			  width:100%;
			  text-align:center;
			
			  font-size:10px;
			  font-weight:900;
			  color:#dc2626;
			
			  text-transform:uppercase;
			
			  padding-bottom:2px;
			  margin-bottom:3px;
			
			  border-bottom:2px solid #dc2626;
			}
			
			
			/* =====================
			   CONTENT
			=====================*/
			
			.cardValue{
			  font-size:17px;
			  font-weight:900;
			  color:#111827;
			
			  margin:2px 0;
			
			  white-space:nowrap;
			  overflow:hidden;
			  text-overflow:ellipsis;
			}
			
			.cardSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   BACK
			=====================*/
			
			.backIcon{
			  font-size:14px;
			  margin-bottom:3px;
			}
			
			.backText{
			  font-size:9px;
			  color:#374151;
			  line-height:1.25;
			
			  text-align:center;
			}
			
			</style>
			
			
			<div class='masterBox'>
			
			
			<!-- HEADER -->
			<div class='pageHeader'>
			
			<div class='mainTitle'>
			🏅 Athletes & Legends
			<span class='badgeLive'>LIVE</span>
			</div>
			
			
			<div class='countWrap'>
			
			
			<!-- WINTER -->
			
			<div class='countBox'>
			
			<div class='countTitle'>Winter Medals</div>
			
			<div class='countTime'>" & _FmtWinter & "</div>
			
			<div class='countSub'>Current Selection</div>
			
			</div>
			
			
			<!-- SUMMER -->
			
			<div class='countBox'>
			
			<div class='countTitle'>Summer Medals</div>
			
			<div class='countTime'>" & _FmtSummer & "</div>
			
			<div class='countSub'>Current Selection</div>
			
			</div>
			
			
			</div>
			
			</div>
			
			
			<!-- GRID -->
			<div class='flipGrid'>
			
			
			<!-- SCORE -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='face front'>
			
			<div class='cardTitle'>Medal Score</div>
			<div class='cardValue'>" & _FmtScore & "</div>
			<div class='cardSub'>Weighted Index</div>
			
			</div>
			
			<div class='face back'>
			
			<div class='backIcon'>🏆</div>
			
			<div class='backText'>
			Overall performance score weighted by medal type.
			</div>
			
			</div>
			
			</div></div>
			
			
			<!-- AVG -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='face front'>
			
			<div class='cardTitle'>Avg Career</div>
			<div class='cardValue'>" & _FmtAvg & "</div>
			<div class='cardSub'>Games / Athlete</div>
			
			</div>
			
			<div class='face back'>
			
			<div class='backIcon'>📊</div>
			
			<div class='backText'>
			Average Olympic participations.
			</div>
			
			</div>
			
			</div></div>
			
			
			<!-- ATHLETES -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='face front'>
			
			<div class='cardTitle'>Athletes</div>
			<div class='cardValue'>" & _FmtAth & "</div>
			<div class='cardSub'>In Selection</div>
			
			</div>
			
			<div class='face back'>
			
			<div class='backIcon'>🏃‍♂️</div>
			
			<div class='backText'>
			Distinct athletes filtered.
			</div>
			
			</div>
			
			</div></div>
			
			
			<!-- MULTI -->
			<div class='flipCard'><div class='flipInner'>
			
			<div class='face front'>
			
			<div class='cardTitle'>Multi-Medalists</div>
			<div class='cardValue'>" & _FmtMulti & "</div>
			<div class='cardSub'>5+ Medals</div>
			
			</div>
			
			<div class='face back'>
			
			<div class='backIcon'>🥇</div>
			
			<div class='backText'>
			Athletes with 5+ medals.
			</div>
			
			</div>
			
			</div></div>
			
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 3
		lineageTag: e7947d82-0eec-4e1f-b7c8-ff28d4a96ee6

	measure 'Athlete Spotlight Vertical v6 HD' = ```
			
			
			
			/* =====================
			   SELECTED ATHLETE
			=====================*/
			
			VAR _Athlete =
			SELECTEDVALUE(athletes[Athlete])
			
			VAR _AthleteURL =
			SELECTEDVALUE(athletes[Athlete URL])
			
			VAR _Bio =
			SELECTEDVALUE(athletes[Bio])
			
			
			
			/* =====================
			   FORCE CONTEXT
			=====================*/
			
			VAR _AthleteFilter =
			TREATAS(
			    VALUES(athletes[Athlete URL]),
			    results[athlete_url]
			)
			
			
			
			/* =====================
			   METRICS
			=====================*/
			
			VAR _Score =
			CALCULATE(
			    [Medal Score],
			    _AthleteFilter
			)
			
			
			VAR _Total =
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    _AthleteFilter
			)
			
			
			VAR _Games =
			CALCULATE(
			    DISTINCTCOUNT(results[Game Slug]),
			    _AthleteFilter
			)
			
			
			VAR _Discipline =
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    _AthleteFilter
			)
			
			
			VAR _Country =
			CALCULATE(
			    SELECTEDVALUE(results[Country]),
			    _AthleteFilter
			)
			
			
			
			/* =====================
			   FLAG
			=====================*/
			
			VAR _Flag =
			CALCULATE(
			    MAX(countrys[Flag_URL]),
			    _AthleteFilter
			)
			
			
			
			/* =====================
			   MEDALS
			=====================*/
			
			VAR _Gold =
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    'athlete medals'[Medal] = "Gold",
			    _AthleteFilter
			)
			
			
			VAR _Silver =
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    'athlete medals'[Medal] = "Silver",
			    _AthleteFilter
			)
			
			
			VAR _Bronze =
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    'athlete medals'[Medal] = "Bronze",
			    _AthleteFilter
			)
			
			
			
			/* =====================
			   FORMAT
			=====================*/
			
			VAR _FmtScore = FORMAT(_Score,"#,##0")
			VAR _FmtTotal = FORMAT(_Total,"#,0")
			VAR _FmtGames = FORMAT(_Games,"0")
			
			VAR _BioFinal =
			IF(
			    NOT ISBLANK(_Bio),
			    _Bio,
			    "No biography available."
			)
			
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   SPOTLIGHT CARD 440x300
			=====================*/
			
			.cardBox{
			  width:100%;
			  max-width:300px;
			  min-width:240px;
			
			  height:440px;
			
			  background:transparent;
			
			  border-radius:22px;
			  border:1px solid rgba(255,255,255,0.25);
			
			  padding:14px 14px 12px;
			
			  box-shadow:none;
			
			  font-family:Segoe UI, Inter, Arial;
			
			  display:flex;
			  flex-direction:column;
			  align-items:center;
			  justify-content:space-between;
			
			  box-sizing:border-box;
			}
			
			
			/* =====================
			   PHOTO
			=====================*/
			
			.photoWrap{
			  width:120px;
			  height:120px;
			
			  border-radius:50%;
			  background:rgba(241,245,249,0.3);
			
			  display:flex;
			  justify-content:center;
			  align-items:center;
			
			  margin-bottom:6px;
			
			  border:3px solid #dc2626;
			}
			
			.photoWrap img{
			  width:92%;
			  height:92%;
			  border-radius:50%;
			  object-fit:cover;
			}
			
			
			/* =====================
			   NAME
			=====================*/
			
			.name{
			  font-size:20px;
			  font-weight:900;
			  color:#111827;
			  text-align:center;
			
			  line-height:1.2;
			}
			
			
			/* =====================
			   COUNTRY
			=====================*/
			
			.country{
			  display:flex;
			  align-items:center;
			  gap:6px;
			
			  font-size:13px;
			  font-weight:700;
			
			  color:#374151;
			}
			
			.flag{
			  width:22px;
			  height:15px;
			
			  border-radius:2px;
			  border:1px solid rgba(0,0,0,0.15);
			}
			
			
			/* =====================
			   DISCIPLINE
			=====================*/
			
			.discipline{
			  font-size:12px;
			
			  background:rgba(248,250,252,0.6);
			  border:1px solid rgba(229,231,235,0.4);
			
			  border-radius:10px;
			  padding:5px 10px;
			
			  color:#374151;
			
			  text-align:center;
			}
			
			
			/* =====================
			   KPI
			=====================*/
			
			.kpiRow{
			  display:flex;
			  justify-content:space-between;
			  width:100%;
			  gap:6px;
			}
			
			.kpi{
			  text-align:center;
			  flex:1;
			}
			
			.kpiVal{
			  font-size:19px;
			  font-weight:900;
			  color:#111827;
			}
			
			.kpiLab{
			  font-size:10px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   BIO
			=====================*/
			
			.bioBox{
			  width:100%;
			
			  background:rgba(249,250,251,0.6);
			  border:1px solid rgba(229,231,235,0.4);
			
			  border-radius:12px;
			
			  padding:9px 10px;
			
			  font-size:11px;
			  color:#374151;
			  line-height:1.45;
			
			  flex:1;
			
			  overflow-y:auto;
			
			  box-sizing:border-box;
			}
			
			
			/* =====================
			   MEDALS
			=====================*/
			
			.medals{
			  display:flex;
			  gap:12px;
			
			  font-size:19px;
			  font-weight:800;
			}
			
			.gold{ color:#facc15; }
			.silver{ color:#9ca3af; }
			.bronze{ color:#fb923c; }
			
			
			/* =====================
			   RESPONSIVE
			=====================*/
			
			@media(max-width:500px){
			
			  .cardBox{
			    max-width:260px;
			    height:400px;
			  }
			
			  .photoWrap{
			    width:100px;
			    height:100px;
			  }
			
			  .name{
			    font-size:18px;
			  }
			
			}
			
			</style>
			
			
			<div class='cardBox'>
			
			
			<!-- PHOTO -->
			
			<div class='photoWrap'>
			<img src='" & _AthleteURL & "'/>
			</div>
			
			
			<!-- NAME -->
			
			<div class='name'>" & _Athlete & "</div>
			
			
			<!-- COUNTRY -->
			
			<div class='country'>
			<img class='flag' src='" & _Flag & "'/>
			" & _Country & "
			</div>
			
			
			<!-- DISCIPLINE -->
			
			<div class='discipline'>
			" & _Discipline & "
			</div>
			
			
			<!-- KPIs -->
			
			<div class='kpiRow'>
			
			
			<div class='kpi'>
			<div class='kpiVal'>" & _FmtScore & "</div>
			<div class='kpiLab'>Score</div>
			</div>
			
			
			<div class='kpi'>
			<div class='kpiVal'>" & _FmtGames & "</div>
			<div class='kpiLab'>Games</div>
			</div>
			
			
			<div class='kpi'>
			<div class='kpiVal'>" & _FmtTotal & "</div>
			<div class='kpiLab'>Medals</div>
			</div>
			
			
			</div>
			
			
			<!-- BIO -->
			
			<div class='bioBox'>
			" & _BioFinal & "
			</div>
			
			
			<!-- MEDALS -->
			
			<div class='medals'>
			
			<span class='gold'>🥇 " & _Gold & "</span>
			<span class='silver'>🥈 " & _Silver & "</span>
			<span class='bronze'>🥉 " & _Bronze & "</span>
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 3
		lineageTag: a0543167-443d-4f63-87e9-9fb7b944375e

	measure 'Winter Athletes' = ```
			
			
			CALCULATE(
			    DISTINCTCOUNT(athletes[Athlete]),
			
			    TREATAS(
			        VALUES(Season[Season]),
			        hosts[Season]
			    ),
			
			    hosts[Season] = "Winter"
			)
			
			```
		formatString: 0
		displayFolder: Dash 3
		lineageTag: 0402ae1b-bf98-40c9-a04d-cf8bd7084b75

	measure 'Summer Athletes' = ```
			
			
			CALCULATE(
			    DISTINCTCOUNT(athletes[Athlete]),
			
			    TREATAS(
			        VALUES(Season[Season]),
			        hosts[Season]
			    ),
			
			    hosts[Season] = "Summer"
			)
			
			```
		formatString: 0
		displayFolder: Dash 3
		lineageTag: 71b3cb71-91ad-4400-9aa3-12d067e479f6

	measure 'Multi Medalists' = ```
			
			
			COUNTROWS(
			    FILTER(
			        VALUES(athletes[Athlete]),
			        [Total Medals] >= 5
			    )
			)
			
			```
		formatString: 0
		displayFolder: Dash 3
		lineageTag: 7d20bf0e-8702-4cdc-8594-be85f02f85cc

	measure 'Olympic Athlete Medal Table SAFE' = ```
			
			
			
			/* =========================
			   BASE
			========================= */
			
			VAR _BaseTable =
			SUMMARIZE(
			    athletes,
			    athletes[Athlete],
			
			    "Gold",
			        CALCULATE(
			            COUNTROWS('athlete medals'),
			            'athlete medals'[Medal] = "Gold"
			        ),
			
			    "Silver",
			        CALCULATE(
			            COUNTROWS('athlete medals'),
			            'athlete medals'[Medal] = "Silver"
			        ),
			
			    "Bronze",
			        CALCULATE(
			            COUNTROWS('athlete medals'),
			            'athlete medals'[Medal] = "Bronze"
			        ),
			
			    "Total",
			        COUNTROWS('athlete medals'),
			
			    "Score",
			        SUM(results[Medal Value])
			)
			
			
			
			/* =========================
			   RANK
			========================= */
			
			VAR _Ranked =
			ADDCOLUMNS(
			    _BaseTable,
			
			    "Rank",
			    RANKX(
			        _BaseTable,
			        [Score],
			        ,
			        DESC,
			        DENSE
			    )
			)
			
			
			
			/* =========================
			   TOP 50
			========================= */
			
			VAR _Top =
			TOPN(
			    50,
			    _Ranked,
			    [Score], DESC
			)
			
			
			
			/* =========================
			   HTML
			========================= */
			
			RETURN
			
			
			"
			<style>
			.t{background:#f8fafc;border-radius:16px;padding:12px;border:1px solid #e5e7eb;font-family:Segoe UI}
			.h{font-size:18px;font-weight:900;color:#111827;margin-bottom:8px;display:flex;justify-content:space-between}
			.b{background:#dc2626;color:#fff;font-size:10px;font-weight:700;padding:2px 6px;border-radius:4px}
			.s{max-height:420px;overflow-y:auto;border-radius:10px;border:1px solid #e5e7eb;background:#fff}
			table{width:100%;border-collapse:collapse;font-size:12px}
			th{background:#f1f5f9;position:sticky;top:0;padding:6px;font-weight:700;color:#374151;border-bottom:1px solid #e5e7eb}
			td{padding:6px;border-bottom:1px solid #f1f5f9}
			tr:hover{background:#f9fafb}
			.r1{background:rgba(250,204,21,.15)}
			.r2{background:rgba(209,213,219,.18)}
			.r3{background:rgba(192,132,252,.15)}
			.r{font-weight:800;color:#dc2626;width:28px}
			.a{font-weight:700;white-space:nowrap}
			.sc{font-weight:800;color:#16a34a}
			</style>
			
			
			<div class='t'>
			
			
			<div class='h'>
			<div>🏅 Athlete Ranking</div>
			<div class='b'>LIVE</div>
			</div>
			
			
			<div class='s'>
			
			
			<table>
			
			<thead>
			<tr>
			<th>#</th>
			<th>Athlete</th>
			<th>🥇</th>
			<th>🥈</th>
			<th>🥉</th>
			<th>Total</th>
			<th>Score</th>
			</tr>
			</thead>
			
			
			<tbody>
			
			
			" &
			
			
			CONCATENATEX(
			
			    _Top,
			
			    VAR k = [Rank]
			
			    VAR c =
			        IF(
			            k = 1,"r1",
			            IF(k = 2,"r2",
			            IF(k = 3,"r3",""))
			        )
			
			    RETURN
			
			
			"
			<tr class='" & c & "'>
			
			<td class='r'>" & k & "</td>
			
			<td class='a'>" & [Athlete] & "</td>
			
			<td>" & [Gold] & "</td>
			<td>" & [Silver] & "</td>
			<td>" & [Bronze] & "</td>
			
			<td><b>" & [Total] & "</b></td>
			
			<td class='sc'>" &
			FORMAT([Score],"#,##0") &
			"</td>
			
			</tr>
			
			",
			
			"",
			
			[Rank],ASC
			
			)
			
			
			&
			
			
			"
			
			</tbody>
			
			</table>
			
			
			</div>
			
			</div>
			"
			
			```
		displayFolder: Dash 3
		lineageTag: d04e357e-9660-4ce1-890a-19ce45705fc3

	measure 'Rank Atlete' =
			
			RANKX(
			    ALL(results[NOC]),
			    [Medal Score],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		displayFolder: Dash 3
		lineageTag: f047784e-9b3c-40c8-9bbb-aab303bfbfbc

	measure 'Atlhetes Comparison Title' = ```
			
			
			VAR _Season =
			SELECTEDVALUE(
			    hosts[Season],
			    "All Seasons"
			)
			
			VAR _MinYear =
			MIN(hosts[Year])
			
			VAR _MaxYear =
			MAX(hosts[Year])
			
			VAR _Period =
			IF(
			    _MinYear = _MaxYear,
			    FORMAT(_MinYear,"0"),
			    FORMAT(_MinYear,"0") & "–" & FORMAT(_MaxYear,"0")
			)
			
			RETURN
			
			"🌍 Athletes Performance Comparison — " &
			_Season & " (" & _Period & ")"
			
			```
		displayFolder: Dash 3
		lineageTag: 47c2fcd8-3ff2-41e2-a07e-f9b07a0ad02c

	measure 'Gold Medals athlets' = ```
			
			
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    'athlete medals'[Medal] = "Gold"
			)
			
			```
		formatString: 0
		displayFolder: Dash 3
		lineageTag: 0fa27d25-e87c-4799-95cc-52f85da265fc

	measure 'Silver Medals athlets' = ```
			
			
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    'athlete medals'[Medal] = "Silver"
			)
			
			```
		formatString: 0
		displayFolder: Dash 3
		lineageTag: 6edac2e7-2760-443c-9ef4-e3c6171aa830

	measure 'Bronze Medals athlets' = ```
			
			
			CALCULATE(
			    COUNTROWS('athlete medals'),
			    'athlete medals'[Medal] = "Bronze"
			)
			
			```
		formatString: 0
		displayFolder: Dash 3
		lineageTag: d74fcc4a-8563-40e5-b2ae-e15991dd60d1

	measure 'Medals Athlets' = COUNTROWS('athlete medals')
		formatString: 0
		displayFolder: Dash 3
		lineageTag: ff6ce30d-370b-4ff3-85d2-3eac8b05c557

	measure 'Medal Score atlhets' = ```
			
			SUM ( 'athlete medals'[Medal Value])
			
			```
		formatString: #,0
		displayFolder: Dash 3
		lineageTag: 6254fa6c-c681-4da9-a5c4-020d1a87bff1

	measure 'Athlete Rank by Medals' = ```
			
			
			RANKX(
			    ALL(athletes[Athlete]),
			    [Medals Athlets],
			    ,
			    DESC,
			    DENSE
			)
			
			```
		formatString: 0
		displayFolder: Dash 3
		lineageTag: 62f7e44a-fcd4-4997-b2b8-eb52019fce9d

	measure 'ESPN Frame Full Border' = ```
			
			
			VAR _HTML =
			"
			<style>
			
			/* =====================
			   FULL BORDER FRAME
			=====================*/
			
			html, body{
			  width:100%;
			  height:100%;
			  margin:0;
			  padding:0;
			}
			
			.frameBox{
			
			  width:100%;
			  height:100%;
			
			  background:white;
			
			  border-radius:22px;
			  border:1.5px solid #e5e7eb;
			
			  box-shadow:0 3px 10px rgba(0,0,0,.10);
			
			  font-family:Segoe UI, Inter, Arial;
			
			  box-sizing:border-box;
			
			  position:absolute;
			  top:0;
			  left:0;
			}
			
			</style>
			
			
			<div class='frameBox'></div>
			"
			
			RETURN
			_HTML
			
			```
		displayFolder: Dash ext
		lineageTag: 313e4dbe-5e92-498e-b9f1-10fffdaae16d

	measure 'Athlete Tooltip Career v1' = ```
			
			
			
			/* =====================
			   SELECTED ATHLETE
			=====================*/
			
			VAR _Athlete =
			SELECTEDVALUE(athletes[Athlete])
			
			VAR _AthleteURL =
			SELECTEDVALUE(athletes[Athlete URL])
			
			VAR _Bio =
			SELECTEDVALUE(athletes[Bio])
			
			
			
			/* =====================
			   FORCE CONTEXT
			=====================*/
			
			VAR _AthleteFilter =
			TREATAS(
			    VALUES(athletes[Athlete URL]),
			    results[athlete_url]
			)
			
			
			
			/* =====================
			   GAMES LIST
			=====================*/
			
			VAR _GamesTable =
			SUMMARIZE(
			    CALCULATETABLE(
			        results,
			        _AthleteFilter
			    ),
			    results[Game Slug],
			    "GameName",
			        LOOKUPVALUE(
			            hosts[Game Name],
			            hosts[Game Slug],
			            results[Game Slug]
			        ),
			    "Year",
			        MAX(results[Game Year])
			)
			
			
			
			VAR _GamesHTML =
			CONCATENATEX(
			
			    _GamesTable,
			
			    "<li>" &
			    [GameName] & " (" & [Year] & ")" &
			    "</li>",
			
			    "",
			
			    [Year], ASC
			)
			
			
			
			/* =====================
			   BIO
			=====================*/
			
			VAR _BioFinal =
			IF(
			    NOT ISBLANK(_Bio),
			    _Bio,
			    "No biography available."
			)
			
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   TOOLTIP STYLE
			=====================*/
			
			.tipBox{
			
			  width:300px;
			  max-height:380px;
			
			  background:white;
			
			  border-radius:16px;
			  border:1px solid #e5e7eb;
			
			  padding:12px;
			
			  box-shadow:0 4px 12px rgba(0,0,0,.15);
			
			  font-family:Segoe UI, Inter, Arial;
			
			  box-sizing:border-box;
			}
			
			
			/* Header */
			
			.tipName{
			  font-size:15px;
			  font-weight:900;
			  color:#111827;
			  margin-bottom:4px;
			}
			
			.tipLine{
			  width:100%;
			  height:2px;
			  background:#dc2626;
			  margin:4px 0 8px;
			}
			
			
			/* Section */
			
			.tipSection{
			  font-size:11px;
			  font-weight:800;
			  color:#374151;
			  margin-top:6px;
			  margin-bottom:3px;
			  text-transform:uppercase;
			}
			
			
			/* Games */
			
			.gamesBox{
			  max-height:110px;
			  overflow-y:auto;
			
			  background:#f9fafb;
			
			  border:1px solid #e5e7eb;
			  border-radius:8px;
			
			  padding:6px;
			
			  font-size:11px;
			  color:#111827;
			}
			
			.gamesBox ul{
			  padding-left:16px;
			  margin:0;
			}
			
			.gamesBox li{
			  margin-bottom:3px;
			}
			
			
			/* Bio */
			
			.bioBox{
			  max-height:90px;
			  overflow-y:auto;
			
			  background:#f9fafb;
			
			  border:1px solid #e5e7eb;
			  border-radius:8px;
			
			  padding:6px;
			
			  font-size:11px;
			  color:#374151;
			
			  line-height:1.4;
			}
			
			</style>
			
			
			<div class='tipBox'>
			
			
			<!-- NAME -->
			
			<div class='tipName'>
			" & _Athlete & "
			</div>
			
			<div class='tipLine'></div>
			
			
			<!-- GAMES -->
			
			<div class='tipSection'>Olympic Games</div>
			
			<div class='gamesBox'>
			
			<ul>
			
			" & _GamesHTML & "
			
			</ul>
			
			</div>
			
			
			<!-- BIO -->
			
			<div class='tipSection'>Biography</div>
			
			<div class='bioBox'>
			
			" & _BioFinal & "
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash ext
		lineageTag: 25911725-6fbc-4c3c-b3fe-aa432bda541f

	measure 'Medal Share %' = ```
			
			DIVIDE(
			    [Medal Score],
			    CALCULATE([Medal Score], ALL(results[Country]))
			)
			
			```
		displayFolder: Dash 4
		lineageTag: 30415963-13b8-43c7-86e6-23410c0dfddc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Peak Edition Score' = ```
			
			MAXX(
			    VALUES(results[Game Slug]),
			    [Medal Score]
			)
			
			```
		formatString: 0
		displayFolder: Dash 4
		lineageTag: f671cb65-1634-4b83-9c3b-fe4909df37bb

	measure 'Top Nation Era' = ```
			
			CALCULATE(
			    SELECTEDVALUE(results[Country]),
			    TOPN(1,ALL(results[Country]),[Medal Score],DESC)
			)
			
			```
		displayFolder: Dash 4
		lineageTag: 094de1d3-f606-460e-a5f9-bbb5efd54418

	measure 'Olympic Evolution Header Page 4 FINAL v3' = ```
			
			
			
			/* =====================
			   METRICS
			=====================*/
			
			VAR _TopNationEra =
			CALCULATE(
			    SELECTEDVALUE(results[Country]),
			    TOPN(1,ALL(results[Country]),[Medal Score],DESC)
			)
			
			
			VAR _TopNationScore =
			CALCULATE(
			    [Medal Score],
			    results[Country] = _TopNationEra
			)
			
			
			VAR _PeakEdition =
			CALCULATE(
			    SELECTEDVALUE(hosts[Game Name]),
			    TOPN(
			        1,
			        VALUES(results[Game Slug]),
			        [Medal Score],
			        DESC
			    )
			)
			
			
			VAR _PeakScore =
			MAXX(
			    VALUES(results[Game Slug]),
			    [Medal Score]
			)
			
			
			VAR _BestDecade =
			CALCULATE(
			    SELECTEDVALUE(calendar[Decade]),
			    TOPN(1,ALL(calendar[Decade]),[Medal Score],DESC)
			)
			
			
			VAR _NewPowers =
			CALCULATE(
			    DISTINCTCOUNT(results[Country]),
			    results[Game Year] >= 1990
			)
			
			
			
			/* =====================
			   WINTER / SUMMER
			=====================*/
			
			VAR _WinterScore =
			CALCULATE(
			    [Medal Score],
			    hosts[Season] = "Winter"
			)
			
			VAR _SummerScore =
			CALCULATE(
			    [Medal Score],
			    hosts[Season] = "Summer"
			)
			
			
			
			/* =====================
			   FORMAT
			=====================*/
			
			VAR _FmtTopScore   = FORMAT(_TopNationScore,"#,##0")
			VAR _FmtPeakScore  = FORMAT(_PeakScore,"#,##0")
			VAR _FmtWinter     = FORMAT(_WinterScore,"#,##0")
			VAR _FmtSummer     = FORMAT(_SummerScore,"#,##0")
			VAR _FmtNewPowers  = FORMAT(_NewPowers,"#,0")
			
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   PAGE BOX
			=====================*/
			
			.pageBox{
			  width:100%;
			  background:#ffffff;
			  border-radius:16px;
			  border:1px solid #e5e7eb;
			
			  padding:10px 12px;
			
			  box-shadow:0 2px 6px rgba(0,0,0,.07);
			
			  font-family:Segoe UI, Inter, Arial;
			  box-sizing:border-box;
			}
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.pageHeader{
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			
			  margin-bottom:8px;
			
			  flex-wrap:wrap;
			  gap:8px;
			}
			
			.headerLeft{
			  display:flex;
			  flex-direction:column;
			}
			
			.mainTitle{
			  font-size:17px;
			  font-weight:900;
			  color:#111827;
			
			  display:flex;
			  align-items:center;
			  gap:6px;
			}
			
			.liveBadge{
			  background:#dc2626;
			  color:white;
			
			  font-size:9px;
			  font-weight:800;
			
			  padding:2px 5px;
			  border-radius:4px;
			}
			
			.subTitle{
			  font-size:9px;
			  color:#6b7280;
			  margin-top:1px;
			}
			
			
			/* =====================
			   RIGHT INFO
			=====================*/
			
			.headerRight{
			  display:flex;
			  gap:10px;
			}
			
			.seasonBox{
			  text-align:right;
			  min-width:100px;
			}
			
			.seasonTitle{
			  font-size:8px;
			  font-weight:700;
			  color:#dc2626;
			  text-transform:uppercase;
			}
			
			.seasonVal{
			  font-size:12px;
			  font-weight:900;
			  color:#111827;
			}
			
			.seasonSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   GRID
			=====================*/
			
			.kpiGrid{
			  display:grid;
			  grid-template-columns:repeat(auto-fit,minmax(120px,1fr));
			  gap:7px;
			}
			
			
			/* =====================
			   FLIP CARD
			=====================*/
			
			.flipCard{
			  height:73px;
			  perspective:1000px;
			}
			
			.flipInner{
			  width:100%;
			  height:100%;
			  position:relative;
			  transition:transform .6s ease;
			  transform-style:preserve-3d;
			}
			
			.flipCard:hover .flipInner{
			  transform:rotateY(180deg);
			}
			
			
			/* =====================
			   FACES
			=====================*/
			
			.flipFront,
			.flipBack{
			  position:absolute;
			  width:100%;
			  height:100%;
			
			  backface-visibility:hidden;
			
			  border-radius:10px;
			  border:1px solid #e5e7eb;
			  background:white;
			
			  box-shadow:0 2px 5px rgba(0,0,0,.07);
			
			  padding:6px;
			
			  display:flex;
			  flex-direction:column;
			  align-items:center;
			  justify-content:center;
			
			  text-align:center;
			}
			
			.flipBack{
			  transform:rotateY(180deg);
			  background:#f8fafc;
			}
			
			
			/* =====================
			   KPI TITLE
			=====================*/
			
			.kpiTitle{
			  width:100%;
			  text-align:center;
			
			  font-size:10px;
			  font-weight:900;
			  color:#dc2626;
			
			  text-transform:uppercase;
			
			  border-bottom:2px solid #dc2626;
			
			  padding-bottom:2px;
			  margin-bottom:3px;
			}
			
			
			/* =====================
			   VALUES
			=====================*/
			
			.kpiValue{
			  font-size:17px;     /* PADRÃO GLOBAL */
			  font-weight:900;
			  color:#111827;
			
			  white-space:nowrap;
			  overflow:hidden;
			  text-overflow:ellipsis;
			
			  max-width:100%;
			}
			
			.kpiSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   BACK
			=====================*/
			
			.backIcon{
			  font-size:14px;
			  margin-bottom:3px;
			}
			
			.backText{
			  font-size:9px;
			  color:#374151;
			  line-height:1.25;
			}
			
			</style>
			
			
			<div class='pageBox'>
			
			
			<!-- HEADER -->
			
			<div class='pageHeader'>
			
			
			<!-- LEFT -->
			
			<div class='headerLeft'>
			
			<div class='mainTitle'>
			📊 Olympic Evolution & Dynasties
			<span class='liveBadge'>LIVE</span>
			</div>
			
			<div class='subTitle'>
			Power Shifts • Dominance • Eras • 1896–2022
			</div>
			
			</div>
			
			
			<!-- RIGHT -->
			
			<div class='headerRight'>
			
			
			<div class='seasonBox'>
			<div class='seasonTitle'>Winter Sports</div>
			<div class='seasonVal'>" & _FmtWinter & "</div>
			<div class='seasonSub'>Score</div>
			</div>
			
			
			<div class='seasonBox'>
			<div class='seasonTitle'>Summer Sports</div>
			<div class='seasonVal'>" & _FmtSummer & "</div>
			<div class='seasonSub'>Score</div>
			</div>
			
			
			</div>
			
			</div>
			
			
			<!-- KPI GRID -->
			
			<div class='kpiGrid'>
			
			
			<!-- ERA LEADER -->
			
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='kpiTitle'>Era Leader</div>
			<div class='kpiValue'>" & _TopNationEra & "</div>
			<div class='kpiSub'>Score " & _FmtTopScore & "</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🏆</div>
			<div class='backText'>
			Country with the highest cumulative medal score.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- PEAK EDITION -->
			
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='kpiTitle'>Peak Edition</div>
			
			<!-- TAMANHO PADRONIZADO -->
			<div class='kpiValue'>" & _PeakEdition & "</div>
			
			<div class='kpiSub'>" & _FmtPeakScore & " Score</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🔥</div>
			<div class='backText'>
			Highest single-edition performance.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- GOLDEN AGE -->
			
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='kpiTitle'>Golden Age</div>
			<div class='kpiValue'>" & _BestDecade & "</div>
			<div class='kpiSub'>Top Decade</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>⏳</div>
			<div class='backText'>
			Peak decade of elite performance.
			</div>
			</div>
			
			</div></div>
			
			
			<!-- NEW POWERS -->
			
			<div class='flipCard'><div class='flipInner'>
			
			<div class='flipFront'>
			<div class='kpiTitle'>New Powers</div>
			<div class='kpiValue'>" & _FmtNewPowers & "</div>
			<div class='kpiSub'>Post-1990</div>
			</div>
			
			<div class='flipBack'>
			<div class='backIcon'>🚀</div>
			<div class='backText'>
			Emerging Olympic nations.
			</div>
			</div>
			
			</div></div>
			
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 4
		lineageTag: 8958c250-a288-4123-9b0d-bb0f777b70d8

	measure 'Top Nation by Decade HTML FINAL v2' = ```
			
			
			
			/* =====================
			   BASE
			=====================*/
			
			VAR _Base =
			
			SUMMARIZE(
			
			    results,
			
			    calendar[Decade],
			    results[Country],
			
			    "Score",  [Medal Score],
			    "Total",  [Total Medals]
			
			)
			
			
			
			/* =====================
			   RANK BY DECADE
			=====================*/
			
			VAR _Ranked =
			
			ADDCOLUMNS(
			
			    _Base,
			
			    "Rank",
			
			    VAR _CurrentDecade = calendar[Decade]
			
			    RETURN
			
			    RANKX(
			
			        FILTER(
			            _Base,
			            calendar[Decade] = _CurrentDecade
			        ),
			
			        [Score],
			
			        ,
			
			        DESC,
			
			        DENSE
			    )
			)
			
			
			
			/* =====================
			   TOP 5
			=====================*/
			
			VAR _Top =
			
			FILTER(
			    _Ranked,
			    [Rank] <= 5
			)
			
			
			
			/* =====================
			   HTML
			=====================*/
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   ESPN TABLE
			=====================*/
			
			.tableBox{
			  width:100%;
			
			  background:#ffffff;
			
			  border-radius:16px;
			  border:1px solid #e5e7eb;
			
			  padding:10px 12px;
			
			  box-shadow:0 2px 6px rgba(0,0,0,.07);
			
			  font-family:Segoe UI, Inter, Arial;
			
			  box-sizing:border-box;
			
			  display:flex;
			  flex-direction:column;
			}
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.tableHeader{
			  display:flex;
			  flex-direction:column;
			  gap:4px;
			
			  margin-bottom:8px;
			}
			
			.tableTitle{
			  font-size:17px;
			  font-weight:900;
			  color:#111827;
			}
			
			.tableSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   BADGE
			=====================*/
			
			.liveBadge{
			  background:#dc2626;
			  color:white;
			
			  font-size:9px;
			  font-weight:800;
			
			  padding:2px 5px;
			  border-radius:4px;
			
			  width:fit-content;
			}
			
			
			/* =====================
			   SCROLL (ONLY TABLE)
			=====================*/
			
			.scrollBox{
			  flex:1;
			
			  overflow-y:auto;
			
			  border-radius:12px;
			  border:1px solid #e5e7eb;
			
			  min-height:0;
			}
			
			
			/* =====================
			   TABLE
			=====================*/
			
			table{
			  width:100%;
			  border-collapse:collapse;
			  font-size:13px;
			}
			
			
			/* =====================
			   HEADER ROW
			=====================*/
			
			th{
			  position:sticky;
			  top:0;
			
			  background:#f1f5f9;
			
			  padding:8px 6px;
			
			  font-weight:800;
			  color:#374151;
			
			  border-bottom:1px solid #e5e7eb;
			
			  z-index:2;
			}
			
			
			/* =====================
			   CELLS
			=====================*/
			
			td{
			  padding:7px 6px;
			  border-bottom:1px solid #f1f5f9;
			}
			
			
			/* =====================
			   HOVER
			=====================*/
			
			tr:hover{
			  background:#f9fafb;
			}
			
			
			/* =====================
			   RANK
			=====================*/
			
			.rankCol{
			  font-weight:900;
			  color:#dc2626;
			  width:34px;
			}
			
			
			/* =====================
			   PODIUM
			=====================*/
			
			.rank1{ background:rgba(250,204,21,.15); }
			.rank2{ background:rgba(209,213,219,.18); }
			.rank3{ background:rgba(192,132,252,.15); }
			
			
			/* =====================
			   COUNTRY
			=====================*/
			
			.countryCol{
			  font-weight:700;
			  color:#111827;
			}
			
			
			/* =====================
			   SCORE
			=====================*/
			
			.scoreCol{
			  font-weight:900;
			  color:#16a34a;
			}
			
			
			/* =====================
			   RESPONSIVE
			=====================*/
			
			@media(max-width:600px){
			
			  table{
			    font-size:12px;
			  }
			
			  th, td{
			    padding:6px 4px;
			  }
			
			}
			
			</style>
			
			
			<div class='tableBox'>
			
			
			<!-- HEADER -->
			
			<div class='tableHeader'>
			
			<div class='tableTitle'>
			🏆 Top Nations by Decade
			</div>
			
			<div class='tableSub'>
			Leading countries ranked by medal performance within each Olympic decade
			</div>
			
			<div class='liveBadge'>LIVE</div>
			
			</div>
			
			
			<!-- TABLE -->
			
			<div class='scrollBox'>
			
			
			<table>
			
			
			<thead>
			
			<tr>
			  <th>Decade</th>
			  <th>#</th>
			  <th>Country</th>
			  <th>Total</th>
			  <th>Score</th>
			</tr>
			
			</thead>
			
			
			<tbody>
			
			
			" &
			
			
			CONCATENATEX(
			
			    _Top,
			
			    VAR _Rank = [Rank]
			
			    VAR _Class =
			        IF(
			            _Rank = 1, "rank1",
			            IF(_Rank = 2, "rank2",
			            IF(_Rank = 3, "rank3",""))
			        )
			
			    RETURN
			
			
			"
			<tr class='" & _Class & "'>
			
			<td><b>" & calendar[Decade] & "</b></td>
			
			<td class='rankCol'>" & _Rank & "</td>
			
			<td class='countryCol'>" & results[Country] & "</td>
			
			<td>" & FORMAT([Total],"#,0") & "</td>
			
			<td class='scoreCol'>" & FORMAT([Score],"#,##0") & "</td>
			
			</tr>
			
			",
			
			"",
			
			calendar[Decade], ASC,
			[Rank], ASC
			
			)
			
			
			&
			
			
			"
			</tbody>
			
			
			</table>
			
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 4
		lineageTag: 597fbf50-963b-42a8-a49a-fb9030d651d3

	measure 'Animated Era Transition HTML' = ```
			
			
			
			/* =====================
			   BASE
			=====================*/
			
			VAR _Base =
			
			SUMMARIZE(
			
			    results,
			
			    calendar[Decade],
			    results[Country],
			
			    "Score", [Medal Score]
			
			)
			
			
			
			/* =====================
			   RANK
			=====================*/
			
			VAR _Ranked =
			
			ADDCOLUMNS(
			
			    _Base,
			
			    "Rank",
			
			    VAR _Dec = calendar[Decade]
			
			    RETURN
			
			    RANKX(
			        FILTER(_Base, calendar[Decade] = _Dec),
			        [Score],
			        ,
			        DESC,
			        DENSE
			    )
			)
			
			
			
			/* =====================
			   TOP 3 PER DECADE
			=====================*/
			
			VAR _Top =
			
			FILTER(
			    _Ranked,
			    [Rank] <= 3
			)
			
			
			
			/* =====================
			   HTML
			=====================*/
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   ANIMATION FRAME
			=====================*/
			
			.animBox{
			  width:100%;
			  height:100%;
			
			  background:white;
			
			  border-radius:20px;
			  border:1px solid #e5e7eb;
			
			  padding:14px;
			
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			
			  font-family:Segoe UI, Inter, Arial;
			
			  overflow:hidden;
			}
			
			
			/* Header */
			
			.animHeader{
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			  margin-bottom:10px;
			}
			
			.animTitle{
			  font-size:18px;
			  font-weight:900;
			  color:#111827;
			}
			
			.animSub{
			  font-size:11px;
			  color:#6b7280;
			}
			
			.liveBadge{
			  background:#dc2626;
			  color:white;
			
			  font-size:11px;
			  font-weight:800;
			
			  padding:3px 7px;
			  border-radius:5px;
			}
			
			
			/* Track */
			
			.track{
			  position:relative;
			  height:100%;
			  width:100%;
			  overflow:hidden;
			}
			
			
			/* Row */
			
			.row{
			  display:flex;
			  align-items:center;
			  gap:10px;
			
			  padding:8px 6px;
			
			  font-size:14px;
			
			  border-bottom:1px solid #f1f5f9;
			}
			
			
			/* Rank */
			
			.rank{
			  font-weight:900;
			  color:#dc2626;
			  width:24px;
			}
			
			
			/* Country */
			
			.country{
			  font-weight:800;
			  color:#111827;
			  width:160px;
			}
			
			
			/* Bar */
			
			.barWrap{
			  flex:1;
			  background:#f1f5f9;
			  height:10px;
			  border-radius:10px;
			  overflow:hidden;
			}
			
			.bar{
			  height:100%;
			  background:#dc2626;
			  animation:grow 2s ease-in-out infinite;
			}
			
			
			/* Decade Label */
			
			.decade{
			  font-size:11px;
			  font-weight:800;
			  color:#374151;
			  margin-bottom:6px;
			}
			
			
			/* =====================
			   ANIMATION
			=====================*/
			
			@keyframes grow{
			  0%{ width:0%; opacity:.3;}
			  40%{ opacity:1;}
			  100%{ width:100%;}
			}
			
			.slide{
			  animation:slide 15s linear infinite;
			}
			
			@keyframes slide{
			
			  0%{ transform:translateY(0);}
			  20%{ transform:translateY(0);}
			
			  25%{ transform:translateY(-25%);}
			  45%{ transform:translateY(-25%);}
			
			  50%{ transform:translateY(-50%);}
			  70%{ transform:translateY(-50%);}
			
			  75%{ transform:translateY(-75%);}
			  95%{ transform:translateY(-75%);}
			
			  100%{ transform:translateY(0);}
			}
			
			</style>
			
			
			<div class='animBox'>
			
			
			<!-- HEADER -->
			
			<div class='animHeader'>
			
			<div>
			
			<div class='animTitle'>
			📈 Era Transitions — Power Shifts
			</div>
			
			<div class='animSub'>
			Top 3 nations evolving across Olympic decades
			</div>
			
			</div>
			
			<div class='liveBadge'>LIVE</div>
			
			</div>
			
			
			<!-- TRACK -->
			
			<div class='track'>
			
			
			<div class='slide'>
			
			
			" &
			
			
			CONCATENATEX(
			
			    _Top,
			
			    VAR _W = ROUND(DIVIDE([Score],MAXX(_Top,[Score]),0)*100,0)
			
			    RETURN
			
			
			"
			<div>
			
			<div class='decade'>" & calendar[Decade] & "s</div>
			
			
			<div class='row'>
			
			<div class='rank'>" & [Rank] & "</div>
			
			<div class='country'>" & results[Country] & "</div>
			
			<div class='barWrap'>
			<div class='bar' style='width:" & _W & "%'></div>
			</div>
			
			</div>
			
			</div>
			
			",
			
			"",
			
			calendar[Decade], ASC,
			[Rank], ASC
			
			)
			
			
			&
			
			
			"
			
			
			</div>
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 4
		lineageTag: 32f52ab0-7d4a-4dba-9deb-70ea47a354e7

	measure 'Era Dominance Score HTML RESPONSIVE' = ```
			
			
			
			/* =====================
			   BASE
			=====================*/
			
			VAR _Base =
			
			SUMMARIZE(
			
			    results,
			
			    calendar[Decade],
			    results[Country],
			
			    "Score", [Medal Score]
			
			)
			
			
			
			/* =====================
			   RANK + DOMINANCE
			=====================*/
			
			VAR _Ranked =
			
			ADDCOLUMNS(
			
			    _Base,
			
			    /* Rank per Decade */
			
			    "Rank",
			
			    VAR _D = calendar[Decade]
			
			    RETURN
			
			    RANKX(
			        FILTER(_Base, calendar[Decade] = _D),
			        [Score],
			        ,
			        DESC,
			        DENSE
			    ),
			
			
			    /* Decade Total */
			
			    "DecadeTotal",
			
			    VAR _D2 = calendar[Decade]
			
			    RETURN
			
			    CALCULATE(
			        SUMX(
			            FILTER(_Base, calendar[Decade] = _D2),
			            [Score]
			        )
			    )
			
			)
			
			
			
			/* =====================
			   DOMINANCE %
			=====================*/
			
			VAR _WithDom =
			
			ADDCOLUMNS(
			
			    _Ranked,
			
			    "Dominance",
			
			    DIVIDE(
			        [Score],
			        [DecadeTotal],
			        0
			    )
			
			)
			
			
			
			/* =====================
			   TOP 1
			=====================*/
			
			VAR _TopEra =
			
			FILTER(
			    _WithDom,
			    [Rank] = 1
			)
			
			
			
			/* =====================
			   HTML
			=====================*/
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   ROOT
			=====================*/
			
			html, body{
			  width:100%;
			  height:100%;
			  margin:0;
			  padding:0;
			}
			
			
			/* =====================
			   CONTAINER
			=====================*/
			
			.domBox{
			  width:100%;
			  height:100%;
			
			  background:white;
			
			  border-radius:clamp(14px,2vw,20px);
			  border:1px solid #e5e7eb;
			
			  padding:clamp(10px,2vw,14px);
			
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			
			  font-family:Segoe UI, Inter, Arial;
			
			  box-sizing:border-box;
			
			  display:flex;
			  flex-direction:column;
			}
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.domHeader{
			  margin-bottom:clamp(6px,1.5vw,10px);
			}
			
			.domTitle{
			  font-size:clamp(15px,3vw,18px);
			  font-weight:900;
			  color:#111827;
			}
			
			.domSub{
			  font-size:clamp(9px,2vw,11px);
			  color:#6b7280;
			}
			
			
			/* =====================
			   SCROLL
			=====================*/
			
			.domScroll{
			  flex:1;
			
			  overflow-y:auto;
			
			  border-radius:clamp(10px,2vw,14px);
			  border:1px solid #e5e7eb;
			}
			
			
			/* =====================
			   ROW
			=====================*/
			
			.domRow{
			  display:grid;
			
			  grid-template-columns:
			    minmax(48px,0.7fr)
			    minmax(100px,1.6fr)
			    minmax(60px,1fr)
			    minmax(80px,3fr)
			    minmax(44px,0.9fr);
			
			  align-items:center;
			
			  gap:clamp(4px,1vw,6px);
			
			  padding:clamp(6px,1.5vw,8px);
			
			  font-size:clamp(11px,2.4vw,13px);
			
			  border-bottom:1px solid #f1f5f9;
			}
			
			.domRow:hover{
			  background:#f9fafb;
			}
			
			
			/* =====================
			   COLUMNS
			=====================*/
			
			.domDec{
			  font-weight:900;
			  color:#374151;
			}
			
			.domCountry{
			  font-weight:800;
			  color:#111827;
			
			  overflow:hidden;
			  text-overflow:ellipsis;
			  white-space:nowrap;
			}
			
			.domScore{
			  font-weight:900;
			  color:#16a34a;
			
			  text-align:right;
			}
			
			
			/* =====================
			   BAR
			=====================*/
			
			.domBarWrap{
			  width:100%;
			  height:clamp(8px,1.5vw,10px);
			
			  background:#f1f5f9;
			
			  border-radius:20px;
			
			  overflow:hidden;
			}
			
			.domBar{
			  height:100%;
			  background:#dc2626;
			}
			
			
			/* =====================
			   PERCENT
			=====================*/
			
			.domPct{
			  font-size:clamp(10px,2vw,12px);
			  font-weight:800;
			  color:#dc2626;
			
			  text-align:right;
			}
			
			</style>
			
			
			<div class='domBox'>
			
			
			<!-- HEADER -->
			
			<div class='domHeader'>
			
			<div class='domTitle'>
			👑 Era Dominance Score
			</div>
			
			<div class='domSub'>
			Leading nation and share of total medal power in each decade
			</div>
			
			</div>
			
			
			<!-- LIST -->
			
			<div class='domScroll'>
			
			
			" &
			
			
			CONCATENATEX(
			
			    _TopEra,
			
			    VAR _Pct = ROUND([Dominance]*100,1)
			
			    RETURN
			
			
			"
			<div class='domRow'>
			
			<div class='domDec'>" & calendar[Decade] & "s</div>
			
			<div class='domCountry'>" & results[Country] & "</div>
			
			<div class='domScore'>" & FORMAT([Score],"#,##0") & "</div>
			
			<div class='domBarWrap'>
			  <div class='domBar' style='width:" & _Pct & "%'></div>
			</div>
			
			<div class='domPct'>" & FORMAT(_Pct,"0.0") & "%</div>
			
			</div>
			
			",
			
			"",
			
			calendar[Decade], ASC
			
			)
			
			
			&
			
			
			"
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 4
		lineageTag: 274bdd06-1c70-40e9-a23c-b678132471e9

	measure 'Olympic Legacy Header Page 5 FINAL' = ```
			
			
			
			/* =====================
			   CORE METRICS
			=====================*/
			
			VAR _GOAT =
			CALCULATE(
			    SELECTEDVALUE(athletes[Athlete]),
			    TOPN(1,ALL(athletes[Athlete]),[Medal Score],DESC)
			)
			
			VAR _GOATScore =
			CALCULATE(
			    [Medal Score],
			    athletes[Athlete]=_GOAT
			)
			
			
			VAR _TopNation =
			CALCULATE(
			    SELECTEDVALUE(results[Country]),
			    TOPN(1,ALL(results[Country]),[Medal Score],DESC)
			)
			
			VAR _TopNationScore =
			CALCULATE(
			    [Medal Score],
			    results[Country]=_TopNation
			)
			
			
			VAR _TopSport =
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(1,ALL(results[Discipline]),[Total Medals],DESC)
			)
			
			
			VAR _GoldenEra =
			CALCULATE(
			    SELECTEDVALUE(calendar[Decade]),
			    TOPN(1,ALL(calendar[Decade]),[Medal Score],DESC)
			)
			
			
			
			/* =====================
			   WINTER / SUMMER
			=====================*/
			
			VAR _WinterMedals =
			CALCULATE(
			    [Total Medals],
			    hosts[Season] = "Winter"
			)
			
			VAR _SummerMedals =
			CALCULATE(
			    [Total Medals],
			    hosts[Season] = "Summer"
			)
			
			
			VAR _FmtWinter = FORMAT(_WinterMedals,"#,##0")
			VAR _FmtSummer = FORMAT(_SummerMedals,"#,##0")
			
			
			
			/* =====================
			   FORMAT
			=====================*/
			
			VAR _FmtGOAT = FORMAT(_GOATScore,"#,##0")
			VAR _FmtNation = FORMAT(_TopNationScore,"#,##0")
			
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   MASTER
			=====================*/
			
			.legacyBox{
			  width:100%;
			  background:white;
			
			  border-radius:20px;
			  border:1px solid #e5e7eb;
			
			  padding:clamp(12px,2vw,16px);
			
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			
			  font-family:Segoe UI, Inter, Arial;
			
			  box-sizing:border-box;
			}
			
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.pageHeader{
			  display:flex;
			  justify-content:space-between;
			  align-items:flex-start;
			
			  gap:12px;
			  margin-bottom:14px;
			
			  flex-wrap:wrap;
			}
			
			
			.headerLeft{
			  display:flex;
			  flex-direction:column;
			}
			
			
			.mainTitle{
			  font-size:clamp(20px,3vw,24px);
			  font-weight:900;
			  color:#111827;
			
			  display:flex;
			  align-items:center;
			  gap:8px;
			}
			
			
			.badgeLive{
			  background:#dc2626;
			  color:white;
			
			  font-size:11px;
			  font-weight:800;
			
			  padding:3px 7px;
			  border-radius:5px;
			}
			
			
			.subTitle{
			  font-size:clamp(11px,2vw,12px);
			  color:#6b7280;
			  margin-top:2px;
			}
			
			
			
			/* =====================
			   SEASON BOX
			=====================*/
			
			.seasonWrap{
			  display:flex;
			  gap:14px;
			}
			
			
			.seasonBox{
			  text-align:right;
			  min-width:120px;
			}
			
			
			.seasonTitle{
			  font-size:10px;
			  font-weight:800;
			  color:#dc2626;
			  text-transform:uppercase;
			}
			
			
			.seasonValue{
			  font-size:16px;
			  font-weight:900;
			  color:#111827;
			}
			
			
			.seasonSub{
			  font-size:11px;
			  color:#6b7280;
			}
			
			
			
			/* =====================
			   GRID
			=====================*/
			
			.flipGrid{
			  display:grid;
			
			  grid-template-columns:
			  repeat(auto-fit,minmax(150px,1fr));
			
			  gap:10px;
			}
			
			
			
			/* =====================
			   CARD
			=====================*/
			
			.flipCard{
			  width:100%;
			  height:110px;
			  perspective:1000px;
			}
			
			
			.flipInner{
			  width:100%;
			  height:100%;
			
			  position:relative;
			
			  transition:transform .7s ease;
			  transform-style:preserve-3d;
			}
			
			
			.flipCard:hover .flipInner{
			  transform:rotateY(180deg);
			}
			
			
			
			/* Faces */
			
			.flipFront,
			.flipBack{
			  position:absolute;
			
			  width:100%;
			  height:100%;
			
			  backface-visibility:hidden;
			
			  border-radius:14px;
			
			  border:1px solid #e5e7eb;
			  background:white;
			
			  box-shadow:0 2px 6px rgba(0,0,0,.08);
			
			  padding:8px 10px;
			
			  box-sizing:border-box;
			
			  display:flex;
			  flex-direction:column;
			  justify-content:center;
			  align-items:center;
			
			  text-align:center;
			}
			
			
			.flipBack{
			  transform:rotateY(180deg);
			  background:#f8fafc;
			}
			
			
			
			/* Header */
			
			.cardHeader{
			  width:100%;
			
			  font-size:11px;
			  font-weight:900;
			
			  color:#dc2626;
			  text-transform:uppercase;
			
			  border-bottom:2px solid #dc2626;
			
			  padding-bottom:2px;
			  margin-bottom:4px;
			}
			
			
			
			/* Value */
			
			.cardValue{
			  font-size:clamp(16px,3vw,20px);
			  font-weight:900;
			  color:#111827;
			}
			
			
			.cardSub{
			  font-size:11px;
			  color:#6b7280;
			}
			
			
			
			/* Back */
			
			.backIcon{
			  font-size:18px;
			  margin-bottom:4px;
			}
			
			.backText{
			  font-size:11px;
			  color:#374151;
			  line-height:1.4;
			}
			
			</style>
			
			
			<div class='legacyBox'>
			
			
			<!-- HEADER -->
			
			<div class='pageHeader'>
			
			
			<!-- LEFT -->
			
			<div class='headerLeft'>
			
			
			<div class='mainTitle'>
			🌍 Olympic Legacy & Future
			<span class='badgeLive'>LIVE</span>
			</div>
			
			
			<div class='subTitle'>
			Icons • Dynasties • Next Chapters
			</div>
			
			
			</div>
			
			
			
			<!-- RIGHT -->
			
			<div class='seasonWrap'>
			
			
			<div class='seasonBox'>
			
			<div class='seasonTitle'>Winter</div>
			<div class='seasonValue'>" & _FmtWinter & "</div>
			<div class='seasonSub'>Total Medals</div>
			
			</div>
			
			
			<div class='seasonBox'>
			
			<div class='seasonTitle'>Summer</div>
			<div class='seasonValue'>" & _FmtSummer & "</div>
			<div class='seasonSub'>Total Medals</div>
			
			</div>
			
			
			</div>
			
			
			</div>
			
			
			
			<!-- KPI GRID -->
			
			<div class='flipGrid'>
			
			
			<!-- GOAT -->
			
			<div class='flipCard'><div class='flipInner'>
			
			
			<div class='flipFront'>
			
			<div class='cardHeader'>GOAT</div>
			
			<div class='cardValue'>" & _GOAT & "</div>
			
			<div class='cardSub'>" & _FmtGOAT & " pts</div>
			
			</div>
			
			
			<div class='flipBack'>
			
			<div class='backIcon'>🐐</div>
			
			<div class='backText'>
			Greatest athlete in Olympic history based on total medal score.
			</div>
			
			</div>
			
			
			</div></div>
			
			
			
			<!-- TOP NATION -->
			
			<div class='flipCard'><div class='flipInner'>
			
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Top Nation</div>
			
			<div class='cardValue'>" & _TopNation & "</div>
			
			<div class='cardSub'>" & _FmtNation & " pts</div>
			
			</div>
			
			
			<div class='flipBack'>
			
			<div class='backIcon'>🏆</div>
			
			<div class='backText'>
			Most dominant country across all Olympic editions.
			</div>
			
			</div>
			
			
			</div></div>
			
			
			
			<!-- ICONIC SPORT -->
			
			<div class='flipCard'><div class='flipInner'>
			
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Iconic Sport</div>
			
			<div class='cardValue' style='font-size:14px;'>" & _TopSport & "</div>
			
			<div class='cardSub'>Most medals</div>
			
			</div>
			
			
			<div class='flipBack'>
			
			<div class='backIcon'>⭐</div>
			
			<div class='backText'>
			Discipline that shaped Olympic history through medals and stars.
			</div>
			
			</div>
			
			
			</div></div>
			
			
			
			<!-- GOLDEN ERA -->
			
			<div class='flipCard'><div class='flipInner'>
			
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Golden Era</div>
			
			<div class='cardValue'>" & _GoldenEra & "s</div>
			
			<div class='cardSub'>Peak decade</div>
			
			</div>
			
			
			<div class='flipBack'>
			
			<div class='backIcon'>🕰️</div>
			
			<div class='backText'>
			Decade with the highest concentration of medal performance.
			</div>
			
			</div>
			
			
			</div></div>
			
			
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash ext
		lineageTag: 7200ae96-cf65-4b7c-a95e-d995511e46cc

	measure 'Legacy Timeline Animated HTML FINAL' = ```
			
			
			
			/* =====================
			   BASE
			=====================*/
			
			VAR _Base =
			
			SUMMARIZE(
			
			    calendar,
			
			    calendar[Year],
			
			    "Score",
			        CALCULATE( [Medal Score] )
			
			)
			
			
			
			/* =====================
			   FILTER VALID
			=====================*/
			
			VAR _Valid =
			
			FILTER(
			    _Base,
			    NOT ISBLANK([Score])
			)
			
			
			
			/* =====================
			   HTML
			=====================*/
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   TIMELINE FRAME
			=====================*/
			
			.timelineBox{
			  width:100%;
			  height:100%;
			
			  background:white;
			
			  border-radius:20px;
			  border:1px solid #e5e7eb;
			
			  padding:14px;
			
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			
			  font-family:Segoe UI, Inter, Arial;
			
			  box-sizing:border-box;
			
			  overflow:hidden;
			}
			
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.timeHeader{
			  margin-bottom:10px;
			}
			
			.timeTitle{
			  font-size:18px;
			  font-weight:900;
			  color:#111827;
			}
			
			.timeSub{
			  font-size:11px;
			  color:#6b7280;
			}
			
			
			
			/* =====================
			   CHART
			=====================*/
			
			.chartWrap{
			  position:relative;
			  width:100%;
			  height:calc(100% - 50px);
			
			  display:flex;
			  align-items:flex-end;
			  gap:4px;
			}
			
			
			/* Bar */
			
			.bar{
			  flex:1;
			
			  background:linear-gradient(
			    to top,
			    #dc2626,
			    #f87171
			  );
			
			  border-radius:6px 6px 0 0;
			
			  animation:grow 6s ease-in-out infinite;
			
			  transform-origin:bottom;
			}
			
			
			
			/* Tooltip */
			
			.bar::after{
			  content:attr(data-year) " - " attr(data-score);
			
			  position:absolute;
			
			  bottom:100%;
			  left:50%;
			
			  transform:translateX(-50%);
			
			  background:#111827;
			
			  color:white;
			
			  font-size:9px;
			
			  padding:2px 5px;
			
			  border-radius:4px;
			
			  opacity:0;
			
			  pointer-events:none;
			
			  transition:.3s;
			}
			
			.bar:hover::after{
			  opacity:1;
			}
			
			
			
			/* =====================
			   ANIMATION
			=====================*/
			
			@keyframes grow{
			
			  0%{
			    transform:scaleY(.1);
			    opacity:.4;
			  }
			
			  30%{
			    transform:scaleY(1);
			    opacity:1;
			  }
			
			  80%{
			    transform:scaleY(1);
			    opacity:1;
			  }
			
			  100%{
			    transform:scaleY(.1);
			    opacity:.4;
			  }
			
			}
			
			</style>
			
			
			<div class='timelineBox'>
			
			
			<!-- HEADER -->
			
			<div class='timeHeader'>
			
			<div class='timeTitle'>
			📈 Olympic Legacy Timeline
			</div>
			
			<div class='timeSub'>
			Evolution of medal performance across Olympic history
			</div>
			
			</div>
			
			
			<!-- CHART -->
			
			<div class='chartWrap'>
			
			
			" &
			
			
			CONCATENATEX(
			
			    _Valid,
			
			    VAR _Max = MAXX(_Valid,[Score])
			
			    VAR _H = ROUND( DIVIDE([Score],_Max,0) * 100 ,0)
			
			    RETURN
			
			
			"
			<div class='bar'
			     style='height:" & _H & "%'
			     data-year='" & calendar[Year] & "'
			     data-score='" & FORMAT([Score],"#,##0") & "'>
			</div>
			",
			
			"",
			
			calendar[Year], ASC
			
			)
			
			
			&
			
			
			"
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash ext
		lineageTag: d0981320-c778-4043-9344-91102e566abf

	measure 'Olympic Sports Header Page 5 FINAL v2' = ```
			
			
			
			/* =====================
			   CORE METRICS
			=====================*/
			
			-- Top Sport (Most Medals)
			
			VAR _TopSport =
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(1,ALL(results[Discipline]),[Total Medals],DESC)
			)
			
			VAR _TopSportMedals =
			CALCULATE(
			    [Total Medals],
			    results[Discipline] = _TopSport
			)
			
			
			
			-- Highest Score Sport
			
			VAR _PeakSport =
			CALCULATE(
			    SELECTEDVALUE(results[Discipline]),
			    TOPN(1,ALL(results[Discipline]),[Medal Score],DESC)
			)
			
			VAR _PeakScore =
			CALCULATE(
			    [Medal Score],
			    results[Discipline] = _PeakSport
			)
			
			
			
			-- Top Nation in Top Sport
			
			VAR _TopNationSport =
			CALCULATE(
			    SELECTEDVALUE(results[Country]),
			    TOPN(
			        1,
			        FILTER(
			            ALL(results),
			            results[Discipline] = _TopSport
			        ),
			        [Medal Score],
			        DESC
			    )
			)
			
			
			
			-- Rising Sport (Growth after 2000)
			
			VAR _RisingSport =
			
			TOPN(
			    1,
			
			    ADDCOLUMNS(
			
			        VALUES(results[Discipline]),
			
			        "Growth",
			
			        CALCULATE(
			            [Medal Score],
			            calendar[Year] >= 2000
			        )
			
			        -
			        CALCULATE(
			            [Medal Score],
			            calendar[Year] < 2000
			        )
			    ),
			
			    [Growth],
			    DESC
			)
			
			
			VAR _RisingName =
			MAXX(_RisingSport, results[Discipline])
			
			
			
			/* =====================
			   WINTER / SUMMER
			=====================*/
			
			VAR _WinterSports =
			CALCULATE(
			    DISTINCTCOUNT(results[Discipline]),
			    hosts[Season] = "Winter"
			)
			
			VAR _SummerSports =
			CALCULATE(
			    DISTINCTCOUNT(results[Discipline]),
			    hosts[Season] = "Summer"
			)
			
			
			VAR _FmtWinter = FORMAT(_WinterSports,"#,0")
			VAR _FmtSummer = FORMAT(_SummerSports,"#,0")
			
			
			
			/* =====================
			   FORMAT
			=====================*/
			
			VAR _FmtTopMedals = FORMAT(_TopSportMedals,"#,##0")
			VAR _FmtPeak = FORMAT(_PeakScore,"#,##0")
			
			
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   MASTER (PADRÃO GLOBAL)
			=====================*/
			
			.sportBox{
			  width:100%;
			  background:#ffffff;
			
			  border-radius:16px;
			  border:1px solid #e5e7eb;
			
			  padding:10px 12px;
			
			  box-shadow:0 2px 6px rgba(0,0,0,.07);
			
			  font-family:Segoe UI, Inter, Arial;
			
			  box-sizing:border-box;
			}
			
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.pageHeader{
			  display:flex;
			  justify-content:space-between;
			  align-items:center;
			
			  gap:8px;
			  margin-bottom:8px;
			
			  flex-wrap:wrap;
			}
			
			
			.headerLeft{
			  display:flex;
			  flex-direction:column;
			}
			
			
			.mainTitle{
			  font-size:17px;        /* PADRÃO */
			  font-weight:900;
			  color:#111827;
			
			  display:flex;
			  align-items:center;
			  gap:6px;
			}
			
			
			.badgeLive{
			  background:#dc2626;
			  color:white;
			
			  font-size:9px;
			  font-weight:800;
			
			  padding:2px 5px;
			  border-radius:4px;
			}
			
			
			.subTitle{
			  font-size:9px;
			  color:#6b7280;
			  margin-top:1px;
			}
			
			
			
			/* =====================
			   SEASON BOX
			=====================*/
			
			.seasonWrap{
			  display:flex;
			  gap:10px;
			}
			
			
			.seasonBox{
			  text-align:right;
			  min-width:100px;
			}
			
			
			.seasonTitle{
			  font-size:8px;
			  font-weight:700;
			  color:#dc2626;
			  text-transform:uppercase;
			}
			
			
			.seasonValue{
			  font-size:12px;
			  font-weight:900;
			  color:#111827;
			}
			
			
			.seasonSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			
			/* =====================
			   GRID
			=====================*/
			
			.flipGrid{
			  display:grid;
			
			  grid-template-columns:
			  repeat(auto-fit,minmax(120px,1fr));
			
			  gap:7px;
			}
			
			
			
			/* =====================
			   CARD
			=====================*/
			
			.flipCard{
			  width:100%;
			  height:73px;      /* PADRÃO GLOBAL */
			  perspective:1000px;
			}
			
			
			.flipInner{
			  width:100%;
			  height:100%;
			
			  position:relative;
			
			  transition:transform .6s ease;
			  transform-style:preserve-3d;
			}
			
			
			.flipCard:hover .flipInner{
			  transform:rotateY(180deg);
			}
			
			
			
			/* =====================
			   FACES
			=====================*/
			
			.flipFront,
			.flipBack{
			  position:absolute;
			
			  width:100%;
			  height:100%;
			
			  backface-visibility:hidden;
			
			  border-radius:10px;
			
			  border:1px solid #e5e7eb;
			  background:white;
			
			  box-shadow:0 2px 5px rgba(0,0,0,.07);
			
			  padding:6px;
			
			  box-sizing:border-box;
			
			  display:flex;
			  flex-direction:column;
			  justify-content:center;
			  align-items:center;
			
			  text-align:center;
			}
			
			
			.flipBack{
			  transform:rotateY(180deg);
			  background:#f8fafc;
			}
			
			
			
			/* =====================
			   CARD HEADER
			=====================*/
			
			.cardHeader{
			  width:100%;
			
			  font-size:10px;
			  font-weight:900;
			
			  color:#dc2626;
			  text-transform:uppercase;
			
			  border-bottom:2px solid #dc2626;
			
			  padding-bottom:2px;
			  margin-bottom:3px;
			}
			
			
			
			/* =====================
			   VALUE
			=====================*/
			
			.cardValue{
			  font-size:17px;
			  font-weight:900;
			  color:#111827;
			
			  white-space:nowrap;
			  overflow:hidden;
			  text-overflow:ellipsis;
			}
			
			
			.cardSub{
			  font-size:9px;
			  color:#6b7280;
			}
			
			
			
			/* =====================
			   BACK
			=====================*/
			
			.backIcon{
			  font-size:14px;
			  margin-bottom:3px;
			}
			
			.backText{
			  font-size:9px;
			  color:#374151;
			  line-height:1.25;
			}
			
			</style>
			
			
			<div class='sportBox'>
			
			
			<!-- HEADER -->
			
			<div class='pageHeader'>
			
			
			<!-- LEFT -->
			
			<div class='headerLeft'>
			
			
			<div class='mainTitle'>
			🏟️ Sports & Disciplines Intelligence
			<span class='badgeLive'>LIVE</span>
			</div>
			
			
			<div class='subTitle'>
			Performance • Dominance • Evolution
			</div>
			
			
			</div>
			
			
			
			<!-- RIGHT -->
			
			<div class='seasonWrap'>
			
			
			<div class='seasonBox'>
			
			<div class='seasonTitle'>Winter Sports</div>
			<div class='seasonValue'>" & _FmtWinter & "</div>
			<div class='seasonSub'>Disciplines</div>
			
			</div>
			
			
			<div class='seasonBox'>
			
			<div class='seasonTitle'>Summer Sports</div>
			<div class='seasonValue'>" & _FmtSummer & "</div>
			<div class='seasonSub'>Disciplines</div>
			
			</div>
			
			
			</div>
			
			
			</div>
			
			
			
			<!-- KPI GRID -->
			
			<div class='flipGrid'>
			
			
			<!-- TOP SPORT -->
			
			<div class='flipCard'><div class='flipInner'>
			
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Top Sport</div>
			
			<div class='cardValue'>" & _TopSport & "</div>
			
			<div class='cardSub'>" & _FmtTopMedals & " medals</div>
			
			</div>
			
			
			<div class='flipBack'>
			
			<div class='backIcon'>🥇</div>
			
			<div class='backText'>
			Discipline with the highest number of medals.
			</div>
			
			</div>
			
			
			</div></div>
			
			
			
			<!-- PEAK SCORE -->
			
			<div class='flipCard'><div class='flipInner'>
			
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Peak Score</div>
			
			<div class='cardValue'>" & _PeakSport & "</div>
			
			<div class='cardSub'>" & _FmtPeak & " pts</div>
			
			</div>
			
			
			<div class='flipBack'>
			
			<div class='backIcon'>🔥</div>
			
			<div class='backText'>
			Sport with highest cumulative score.
			</div>
			
			</div>
			
			
			</div></div>
			
			
			
			<!-- TOP NATION -->
			
			<div class='flipCard'><div class='flipInner'>
			
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Top Nation</div>
			
			<div class='cardValue'>" & _TopNationSport & "</div>
			
			<div class='cardSub'>In " & _TopSport & "</div>
			
			</div>
			
			
			<div class='flipBack'>
			
			<div class='backIcon'>🌍</div>
			
			<div class='backText'>
			Strongest dominance in discipline.
			</div>
			
			</div>
			
			
			</div></div>
			
			
			
			<!-- RISING SPORT -->
			
			<div class='flipCard'><div class='flipInner'>
			
			
			<div class='flipFront'>
			
			<div class='cardHeader'>Rising Sport</div>
			
			<div class='cardValue'>" & _RisingName & "</div>
			
			<div class='cardSub'>Post-2000 growth</div>
			
			</div>
			
			
			<div class='flipBack'>
			
			<div class='backIcon'>🚀</div>
			
			<div class='backText'>
			Fastest growing discipline.
			</div>
			
			</div>
			
			
			</div></div>
			
			
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 5
		lineageTag: 2a66805d-79d7-42e7-b83d-69a66bd7a158

	measure 'Discipline Leaders HTML COMPACT' = ```
			
			
			
			/* =====================
			   BASE
			=====================*/
			
			VAR _Base =
			
			SUMMARIZE(
			
			    results,
			
			    results[Discipline],
			    results[Country],
			
			    "Score", [Medal Score],
			    "Total", [Total Medals]
			
			)
			
			
			
			/* =====================
			   RANK
			=====================*/
			
			VAR _Ranked =
			
			ADDCOLUMNS(
			
			    _Base,
			
			    "Rank",
			
			    VAR _Disc = results[Discipline]
			
			    RETURN
			
			    RANKX(
			        FILTER(_Base, results[Discipline] = _Disc),
			        [Score],
			        ,
			        DESC,
			        DENSE
			    )
			
			)
			
			
			
			/* =====================
			   TOTAL
			=====================*/
			
			VAR _WithTotal =
			
			ADDCOLUMNS(
			
			    _Ranked,
			
			    "DiscTotal",
			
			    VAR _D = results[Discipline]
			
			    RETURN
			
			    CALCULATE(
			        SUMX(
			            FILTER(_Ranked, results[Discipline] = _D),
			            [Score]
			        )
			    )
			
			)
			
			
			
			/* =====================
			   DOMINANCE
			=====================*/
			
			VAR _WithDom =
			
			ADDCOLUMNS(
			
			    _WithTotal,
			
			    "Dominance",
			
			    DIVIDE([Score],[DiscTotal],0)
			
			)
			
			
			
			/* =====================
			   TOP 3
			=====================*/
			
			VAR _Top =
			
			FILTER(
			    _WithDom,
			    [Rank] <= 3
			)
			
			
			
			/* =====================
			   HTML
			=====================*/
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   CONTAINER
			=====================*/
			
			.discBox{
			  width:100%;
			  height:100%;
			
			  background:white;
			
			  border-radius:18px;
			  border:1px solid #e5e7eb;
			
			  padding:10px 12px;
			
			  box-shadow:0 2px 6px rgba(0,0,0,.07);
			
			  font-family:Segoe UI, Inter, Arial;
			
			  box-sizing:border-box;
			}
			
			
			/* =====================
			   HEADER
			=====================*/
			
			.discHeader{
			  margin-bottom:6px;
			}
			
			.discTitle{
			  font-size:16px;
			  font-weight:900;
			  color:#111827;
			}
			
			.discSub{
			  font-size:10px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   SCROLL
			=====================*/
			
			.discScroll{
			  max-height:420px;
			  overflow-y:auto;
			
			  border-radius:12px;
			  border:1px solid #e5e7eb;
			}
			
			
			/* =====================
			   ROW
			=====================*/
			
			.discRow{
			  display:grid;
			
			  grid-template-columns:
			    36px
			    minmax(90px,1.8fr)
			    minmax(70px,1.4fr)
			    64px
			    1.6fr
			    46px;
			
			  align-items:center;
			
			  gap:4px;
			
			  padding:4px 6px;
			
			  font-size:11.5px;
			
			  border-bottom:1px solid #f1f5f9;
			
			  white-space:nowrap;
			}
			
			.discRow:hover{
			  background:#f9fafb;
			}
			
			
			/* =====================
			   COLUMNS
			=====================*/
			
			.discRank{
			  font-weight:900;
			  color:#dc2626;
			  text-align:center;
			}
			
			
			/* Discipline */
			
			.discName{
			  font-weight:800;
			  color:#111827;
			
			  overflow:hidden;
			  text-overflow:ellipsis;
			}
			
			
			/* Country */
			
			.discCountry{
			  font-weight:700;
			  color:#374151;
			
			  overflow:hidden;
			  text-overflow:ellipsis;
			}
			
			
			/* Score */
			
			.discScore{
			  font-weight:900;
			  color:#16a34a;
			  text-align:right;
			}
			
			
			/* =====================
			   BAR
			=====================*/
			
			.discBarWrap{
			  width:100%;
			  height:6px;
			
			  background:#f1f5f9;
			
			  border-radius:6px;
			
			  overflow:hidden;
			}
			
			.discBar{
			  height:100%;
			  background:#dc2626;
			}
			
			
			/* =====================
			   PERCENT
			=====================*/
			
			.discPct{
			  font-size:10px;
			  font-weight:800;
			  color:#dc2626;
			  text-align:right;
			}
			
			</style>
			
			
			<div class='discBox'>
			
			
			<!-- HEADER -->
			
			<div class='discHeader'>
			
			<div class='discTitle'>
			🏆 Discipline Leaders
			</div>
			
			<div class='discSub'>
			Top countries by medal dominance per discipline
			</div>
			
			</div>
			
			
			<!-- LIST -->
			
			<div class='discScroll'>
			
			
			" &
			
			
			CONCATENATEX(
			
			    _Top,
			
			    VAR _Pct = ROUND([Dominance]*100,1)
			
			    RETURN
			
			
			"
			<div class='discRow'>
			
			<div class='discRank'>" & [Rank] & "</div>
			
			<div class='discName'>" & results[Discipline] & "</div>
			
			<div class='discCountry'>" & results[Country] & "</div>
			
			<div class='discScore'>" & FORMAT([Score],"#,##0") & "</div>
			
			<div class='discBarWrap'>
			  <div class='discBar' style='width:" & _Pct & "%'></div>
			</div>
			
			<div class='discPct'>" & FORMAT(_Pct,"0.0") & "%</div>
			
			</div>
			
			",
			
			"",
			
			results[Discipline], ASC,
			[Rank], ASC
			
			)
			
			
			&
			
			
			"
			
			</div>
			
			
			</div>
			"
			
			```
		displayFolder: Dash 5
		lineageTag: 8eab3db3-a763-415b-994d-7168c81872ed

	measure 'Discipline Evolution Line HTML FINAL' = ```
			
			
			/* =====================
			   BASE
			=====================*/
			
			VAR _Base =
			    SUMMARIZE(
			        results,
			        calendar[Year],
			        results[Discipline],
			        "Score", [Medal Score]
			    )
			
			
			/* =====================
			   TOP 5 DISCIPLINES
			=====================*/
			
			VAR _TopSports =
			    TOPN(
			        5,
			        VALUES(results[Discipline]),
			        CALCULATE([Medal Score]),
			        DESC
			    )
			
			
			/* =====================
			   FILTER BASE
			=====================*/
			
			VAR _Filtered =
			    FILTER(
			        _Base,
			        results[Discipline] IN _TopSports
			    )
			
			
			/* =====================
			   SCALE
			=====================*/
			
			VAR _MaxScore =
			    MAXX(_Filtered, [Score])
			
			
			/* =====================
			   HTML
			=====================*/
			
			RETURN
			"
			<style>
			
			/* FRAME */
			
			.evoBox{
			  width:100%;
			  height:100%;
			  background:white;
			  border-radius:20px;
			  border:1px solid #e5e7eb;
			  padding:12px 14px;
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			  font-family:Segoe UI, Inter, Arial;
			  box-sizing:border-box;
			  display:flex;
			  flex-direction:column;
			}
			
			/* HEADER */
			
			.evoHeader{ margin-bottom:8px; }
			.evoTitle{ font-size:18px; font-weight:900; color:#111827; }
			.evoSub{ font-size:11px; color:#6b7280; }
			
			/* LEGEND */
			
			.evoLegend{
			  display:flex;
			  gap:10px;
			  flex-wrap:wrap;
			  margin-bottom:6px;
			}
			
			.legItem{
			  display:flex;
			  align-items:center;
			  gap:4px;
			  font-size:10px;
			  font-weight:700;
			  color:#374151;
			}
			
			.legDot{
			  width:10px;
			  height:10px;
			  border-radius:50%;
			}
			
			/* CHART */
			
			.chartWrap{
			  flex:1;
			  display:flex;
			  align-items:flex-end;
			  gap:2px;
			}
			
			/* BAR */
			
			.bar{
			  width:100%;
			  border-radius:4px 4px 0 0;
			  animation:grow 5s ease-in-out infinite;
			  transform-origin:bottom;
			}
			
			/* COLORS */
			
			.c1{ background:#dc2626; }
			.c2{ background:#2563eb; }
			.c3{ background:#16a34a; }
			.c4{ background:#9333ea; }
			.c5{ background:#f97316; }
			
			/* TOOLTIP */
			
			.bar:hover::after{
			  content:attr(data-disc) "" - "" attr(data-year) "" - "" attr(data-score);
			  position:absolute;
			  bottom:100%;
			  left:50%;
			  transform:translateX(-50%);
			  background:#111827;
			  color:white;
			  font-size:9px;
			  padding:3px 6px;
			  border-radius:4px;
			  white-space:nowrap;
			}
			
			/* ANIMATION */
			
			@keyframes grow{
			  0%{ transform:scaleY(.2); opacity:.4;}
			  30%{ transform:scaleY(1); opacity:1;}
			  80%{ transform:scaleY(1); opacity:1;}
			  100%{ transform:scaleY(.2); opacity:.4;}
			}
			
			</style>
			
			
			<div class='evoBox'>
			
			<div class='evoHeader'>
			  <div class='evoTitle'>📈 Discipline Evolution</div>
			  <div class='evoSub'>Medal performance trends across Olympic history (Top 5)</div>
			</div>
			
			
			<div class='chartWrap'>
			
			" &
			
			CONCATENATEX(
			    _Filtered,
			
			    VAR _Height =
			        ROUND(
			            DIVIDE([Score], _MaxScore, 0) * 100,
			            0
			        )
			
			    VAR _Rank =
			        RANKX(
			            _TopSports,
			            CALCULATE([Medal Score]),
			            ,
			            DESC,
			            DENSE
			        )
			
			    VAR _Color =
			        SWITCH(
			            _Rank,
			            1,"c1",
			            2,"c2",
			            3,"c3",
			            4,"c4",
			            "c5"
			        )
			
			    RETURN
			    "
			    <div class='bar " & _Color & "'
			         style='height:" & _Height & "%'
			         data-disc='" & results[Discipline] & "'
			         data-year='" & calendar[Year] & "'
			         data-score='" & FORMAT([Score], "#,##0") & "'>
			    </div>
			    ",
			
			    "",
			    calendar[Year], ASC,
			    results[Discipline], ASC
			)
			
			& "
			
			</div>
			</div>
			"
			
			```
		lineageTag: 1d71e894-fcf8-4c80-9313-5ef3e67f4dfe

	measure 'Discipline Story Cards HTML FINAL' = ```
			
			
			
			/* =====================
			   BASE
			=====================*/
			
			VAR _Base =
			SUMMARIZE(
			    results,
			    results[Discipline],
			    results[Country],
			    "Score", [Medal Score],
			    "Total", [Total Medals]
			)
			
			
			
			/* =====================
			   LEADERS PER DISCIPLINE
			=====================*/
			
			VAR _Leaders =
			ADDCOLUMNS(
			
			    SUMMARIZE(
			        results,
			        results[Discipline]
			    ),
			
			    /* Top Country */
			    "TopCountry",
			    CALCULATE(
			        SELECTEDVALUE(results[Country]),
			        TOPN(
			            1,
			            SUMMARIZE(
			                results,
			                results[Country],
			                "S", [Medal Score]
			            ),
			            [S],
			            DESC
			        )
			    ),
			
			    /* Top Score */
			    "TopScore",
			    CALCULATE(
			        MAXX(
			            SUMMARIZE(
			                results,
			                results[Country],
			                "S", [Medal Score]
			            ),
			            [S]
			        )
			    ),
			
			    /* Total Medals */
			    "TopTotal",
			    CALCULATE(
			        COUNTROWS('athlete medals')
			    ),
			
			    /* Peak Era */
			    "PeakEra",
			    CALCULATE(
			        SELECTEDVALUE(hosts[Era]),
			        TOPN(
			            1,
			            SUMMARIZE(
			                results,
			                hosts[Era],
			                "E", [Medal Score]
			            ),
			            [E],
			            DESC
			        )
			    )
			
			)
			
			
			
			/* =====================
			   LIMIT (TOP 8)
			=====================*/
			
			VAR _TopDisc =
			TOPN(
			    8,
			    _Leaders,
			    [TopScore],
			    DESC
			)
			
			
			
			/* =====================
			   HTML
			=====================*/
			
			RETURN
			
			
			"
			<style>
			
			/* =====================
			   GRID
			=====================*/
			
			.storyGrid{
			  width:100%;
			  display:grid;
			  grid-template-columns:repeat(auto-fit,minmax(180px,1fr));
			  gap:12px;
			  font-family:Segoe UI, Inter, Arial;
			}
			
			
			/* =====================
			   CARD
			=====================*/
			
			.storyCard{
			  width:100%;
			  height:200px;
			  perspective:1000px;
			}
			
			
			/* INNER */
			
			.storyInner{
			  width:100%;
			  height:100%;
			  position:relative;
			  transition:transform .7s ease;
			  transform-style:preserve-3d;
			}
			
			.storyCard:hover .storyInner{
			  transform:rotateY(180deg);
			}
			
			
			/* =====================
			   FACES
			=====================*/
			
			.storyFront,
			.storyBack{
			  position:absolute;
			  width:100%;
			  height:100%;
			  backface-visibility:hidden;
			  border-radius:18px;
			  border:1px solid #e5e7eb;
			  background:white;
			  box-shadow:0 2px 8px rgba(0,0,0,.08);
			  padding:12px;
			  box-sizing:border-box;
			  display:flex;
			  flex-direction:column;
			  justify-content:space-between;
			}
			
			
			/* BACK */
			
			.storyBack{
			  transform:rotateY(180deg);
			  background:#f8fafc;
			}
			
			
			/* =====================
			   FRONT
			=====================*/
			
			.storyTitle{
			  font-size:14px;
			  font-weight:900;
			  color:#111827;
			  border-bottom:2px solid #dc2626;
			  padding-bottom:4px;
			}
			
			.storyCountry{
			  font-size:12px;
			  font-weight:800;
			  color:#374151;
			}
			
			.storyScore{
			  font-size:20px;
			  font-weight:900;
			  color:#16a34a;
			}
			
			.storySub{
			  font-size:10px;
			  color:#6b7280;
			}
			
			
			/* =====================
			   BACK
			=====================*/
			
			.storyText{
			  font-size:11px;
			  color:#374151;
			  line-height:1.4;
			}
			
			.storyEra{
			  font-size:11px;
			  font-weight:800;
			  color:#dc2626;
			}
			
			</style>
			
			
			
			<div class='storyGrid'>
			
			
			" &
			
			
			CONCATENATEX(
			
			    _TopDisc,
			
			    VAR _Story =
			        "In " &
			        results[Discipline] &
			        ", " &
			        [TopCountry] &
			        " established historical dominance with consistent medal performance, peaking during the " &
			        [PeakEra] &
			        " era."
			
			    RETURN
			
			
			"
			<div class='storyCard'>
			
			<div class='storyInner'>
			
			
			<!-- FRONT -->
			
			<div class='storyFront'>
			
			<div class='storyTitle'>
			" & results[Discipline] & "
			</div>
			
			<div class='storyCountry'>
			🏆 " & [TopCountry] & "
			</div>
			
			<div class='storyScore'>
			" & FORMAT([TopScore],"#,##0") & "
			</div>
			
			<div class='storySub'>
			Total Medals: " & FORMAT([TopTotal],"#,0") & "
			</div>
			
			</div>
			
			
			<!-- BACK -->
			
			<div class='storyBack'>
			
			<div class='storyText'>
			" & _Story & "
			</div>
			
			<div class='storyEra'>
			Peak Era: " & [PeakEra] & "
			</div>
			
			</div>
			
			
			</div>
			
			</div>
			
			",
			
			""
			
			)
			
			
			&
			
			
			"
			
			</div>
			"
			
			```
		displayFolder: Dash 5
		lineageTag: b24e383e-aea3-4b73-ac52-325b38d18e40

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Colunas Removidas" = Table.RemoveColumns(Fonte,{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

